### ISSUE TITLE
Naming of this repo

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-dotnet#1]
Hi Gurpreet,
Could you possibly rename to testcontainers-dotnet to be consistent with the java project?

The reason for dropping the inner hyphen was to make the project and package namespace consistent (you can't have hyphens in Java package names, so it feels weird to have project, maven artifact and package name be inconsistent).

Cheers
Rich

**Comment by swissarmykirpan** [comment]
oops!
