### ISSUE TITLE
[Enhancement]: Add ability to specify image tag

### ISSUE THREAD

**Issue by ar0311** [testcontainers/testcontainers-dotnet#1065]
### Problem

At the moment, it appears the database image tags (version) are hard coded into the library.

### Solution

Add the ability to pass in an image tag when creating a container so we can specify the version of the database being used?

### Benefit

Use versions of the database engine other than those hardcoded into the library.

### Alternatives

Fork the library?

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
You can always override the default module configuration. To override the image, use the `WithImage(string)` API. Please note that modules are developed and configured with specific versions in mind. There might be cases where a version is incompatible with module configurations. Here is an example:

    _ = new PostgreSqlBuilder().WithImage("postgres:15.5").Build();

If you have further questions, please do not hesitate to reopen the issue again.

**Comment by ar0311** [comment]
@HofmeisterAn Thank you
