### ISSUE TITLE
[Enhancement]: Renaming a file (very minor)

### ISSUE THREAD

**Issue by mgroves** [testcontainers/testcontainers-dotnet#1066]
### Problem

In the tests/Testcontainers.Couchbase.Tests folder, there is a file named CouchDbContainerTest.cs. The code itself is fine, there's a class called `CouchbaseContainerTest`. However, I think that class names and file names should match. Further, this might cause confusion (of which there is already a considerable amount) that CouchDb and Couchbase are the same thing.

### Solution

File rename from CouchDbContainerTest.cs -> CouchbaseContainerTest.cs

### Benefit

Reduction of potential confusion

### Alternatives

I can't think of an alternative, other than leaving it the way it is.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
Thanks for the PR.
