### ISSUE TITLE
[Enhancement]: support setting the target build stage

### ISSUE THREAD

**Issue by carlin-q-scott** [testcontainers/testcontainers-dotnet#1159]
### Problem

I'm using build stages for my docker image and the final stage hardens the container, removing the ability to debug the container. I would like to run the previous stage that I named "development" so that I can debug my container during testing.

The docker command argument is:
> --target string                 Set the target build stage to build

### Solution

```c#
ImageFromDockerfileBuilder.WithBuildTarget("development")
```

### Benefit

Ability to debug system under test during test execution.

### Alternatives

Comment out the image hardening stage when I need to debug the container.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
We are not exposing every single Docker Engine API explicitly, but we provide an API that allows all kinds of low-level configurations. Could you please try the `WithCreateParameterModifier` builder method?

```csharp
_ = new ImageFromDockerfileBuilder()
    .WithCreateParameterModifier(parameterModifier => parameterModifier.Target = "development");
```

**Comment by carlin-q-scott** [comment]
Thank you! That worked perfectly!
