### ISSUE TITLE
Publish random port

### ISSUE THREAD

**Issue by SbiCA** [testcontainers/testcontainers-dotnet#123]
**Is your feature request related to a problem? Please describe.**
At the moment it is possible to publish a port with a specified binding pair (host, container) whereas in some scenarios I'd like to be able  to just specify the container port and let the engine decide on the published host port e.g.  `docker run -p 80 XZY`. This helps in scenarios such as running a database in integration test scenarios on two points:
- You can still run for instance a postgres instance on the default port 
- You can run test in parallel

**Describe the solution you'd like**
Overload for `WithPortBinding` that accepts only the container port

**Describe alternatives you've considered**
New method `WithRandomPortBiding` would make it more clear to the user

Cheers & let me know if you like me to create a PR for it

**Comment by HofmeisterAn** [comment]
Hi @SbiCA, good feature request. The same applies here as for #122.
Help is always appreciated. I try to support as much as I can.
