### ISSUE TITLE
[Enhancement]: Docs reference removed logging API

### ISSUE THREAD

**Issue by jwm01cg** [testcontainers/testcontainers-dotnet#1242]
### Problem

The documentation for custom configuration at https://dotnet.testcontainers.org/custom_configuration/#enable-logging references the `TestContainersSettings.Logger` API which was obsoleted in #1100 and removed in #1146.

### Solution

The docs should be updated to reference the new `AbstractBuilder.WithLogger` API.

### Benefit

Avoids confusion when configuring logging.

### Alternatives

No

### Would you like to help contributing this enhancement?

Yes

**Comment by jwm01cg** [comment]
BTW, I held off opening a PR because I can see the former pull request references something about built-in integration with XUnit, so I'm not sure what kind of configuration, if any, is recommended now.

**Comment by HofmeisterAn** [comment]
Yes, the documentation is outdated, as mentioned here: https://github.com/testcontainers/testcontainers-dotnet/issues/1215#issuecomment-2241062725. I have updated the documentation along with #1235 ([1](https://github.com/testcontainers/testcontainers-dotnet/blob/a3e18543a52609a99552dabae37bd24b6f217035/docs/api/create_docker_container.md?plain=1#L79-L98), [2](https://github.com/testcontainers/testcontainers-dotnet/blob/a3e18543a52609a99552dabae37bd24b6f217035/docs/custom_configuration/index.md?plain=1#L58-L86)). The documentation should be up-to-date soon. If you don’t mind, I will close this issue as a duplicate.

Regarding xUnit.net, we will update the documentation again once the package is available. This update will address creating the logger for the test output helper and message sink.

**Comment by jwm01cg** [comment]
Ah, sorry for missing that duplicate issue. Happy for you to close this.
