### ISSUE TITLE
[Bug]: ExitCode unavailable when autoremove set to true

### ISSUE THREAD

**Issue by xas** [testcontainers/testcontainers-dotnet#1243]
### Testcontainers version

3.9.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

WSL on Windows 11

### .NET version

8.0

### Docker version

```shell
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.18.1
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

### Docker info

```shell
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### What happened?

I have a simple console application that exits after 5 seconds with a specific exit code.
Running on command line or with a `podman run`, I was able to get the right exit code.

But never with TestContainers. I always get a 0 exit code.

After a lot of tests, I was able to make it work. I just had to remove the parameter in the `ContainerBuilder` building code: `.WithAutoRemove(true)`

Is it normal ?

The cleaning is running too early ?

PS: RYUK is disabled

### Additional information

Sample code:

```csharp
using System;
using System.Threading;

Console.WriteLine("Hello, World!");

Console.WriteLine("--- Arguments ---");
foreach (string arg in args)
{
    Console.WriteLine(arg);
}

Console.WriteLine("--- Environment ---");
foreach (var arg in Environment.GetEnvironmentVariables())
{
    Console.WriteLine($"{arg}");
}

Environment.ExitCode = 11;

Thread.Sleep(5000);```

**Comment by HofmeisterAn** [comment]
When I first read the issue, I didn’t think it was possible, but I tried it anyway, and it works. It’s important to call `GetExitCodeAsync()` immediately after the container starts. This method completes as soon as the container stops or exits and returns the exit code.

If you call it after `StartAsync()` completes, you might encounter two issues (race-conditions). First, you won’t know exactly when the container exits. Second, if the container exits, the Docker daemon removes the resources, preventing us from sending the API call to retrieve the exit code.

Here is a working demo:

```csharp
public sealed class GitHub : IAsyncLifetime
{
    private readonly TaskCompletionSource<long> _containerExitCode;

    private readonly IContainer _container;

    public GitHub()
    {
        _containerExitCode = new TaskCompletionSource<long>();

        _container = new ContainerBuilder()
            .WithImage(CommonImages.Alpine)
            .WithCommand(["sh", "-c", "sleep 1 && exit 1"])
            .WithAutoRemove(true)
            .Build();

        _container.Starting += OnContainerStarting;
    }

    public Task InitializeAsync()
    {
        return _container.StartAsync();
    }

    public Task DisposeAsync()
    {
        return _container.StopAsync();
    }

    [Fact]
    public async Task Container_Should_ExitWithCode1()
    {
        var exitCode = await _containerExitCode.Task;
        Assert.Equal(1, exitCode);
    }

    private async void OnContainerStarting(object sender, EventArgs e)
    {
        var exitCode = await _container.GetExitCodeAsync()
            .ConfigureAwait(false);

        _containerExitCode.TrySetResult(exitCode);
    }
}
```

Does that help?

**Comment by xas** [comment]
Thanks, I understand now.

Your code helped me, and now I got it working.

I think I was in the "race condition", here's my original test code:

```csharp
[Test]
public async Task Legacy_ExitCode_Returns_11()
{
  await _container.StartAsync();
  var exitCode = await _container.GetExitCodeAsync();

  Assert.That(exitCode, Is.EqualTo(11));
}
```
