### ISSUE TITLE
[Enhancement]: Support image override

### ISSUE THREAD

**Issue by rudiv** [testcontainers/testcontainers-dotnet#1260]
### Problem

Image Names are currently constants within the Builders, example https://github.com/testcontainers/testcontainers-dotnet/blob/1d32bc86e902f4684c8b348dbb82a0f44a579c0e/src/Testcontainers.Azurite/AzuriteBuilder.cs#L7C5-L7C89

Given that, especially in the case of Azurite, to update the Storage packages from NuGet in consuming projects means that you have to match the corresponding API version on the container, this is very prohibitive.

The classes are also `sealed` for some reason. There's no way to override this without duplicating the class in your own project. 

### Solution

Provide an option to configure the Image that's used for these containers, whilst retaining the benefits of the rest of the module.

This could be easily achieved by allowing either a configuration object to be passed in or, at the very least, allow the image name to be overridden within the constructor.

```csharp
public sealed class AzuriteBuilder : ContainerBuilder<AzuriteBuilder, AzuriteContainer, AzuriteConfiguration>
{
    public readonly string AzuriteImage = "mcr.microsoft.com/azure-storage/azurite:3.28.0";

    // ...

    /// <summary>
    /// Initializes a new instance of the <see cref="AzuriteBuilder" /> class.
    /// </summary>
    public AzuriteBuilder(string? imageName = default)
        : this(new AzuriteConfiguration())
    {
        AzureiteImage = imageName ?? AzuriteImage;
        DockerResourceConfiguration = Init().DockerResourceConfiguration;
    }
```

I'm happy to go through and implement this where necessary, but this may be an intentional restriction for reasons I can't understand?

### Benefit

Allows more flexibility for tests without restricting projects to specific versions of images.

I understand that this might be done for major changes, but obviously it doesn't have to be a fully supported option when using these builders.

### Alternatives

Unseal the classes to allow overrides to be manually performed.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
> There's no way to override this without duplicating the class in your own project.

That's not right. Actually, we encourage and recommend overriding and pinning the image version in our [best practices](https://dotnet.testcontainers.org/api/best_practices/). Every container builder supports the `WithImage(string)` API, which lets you set the exact image and version used:

    _ = new AzuriteBuilder().WithImage("mcr.microsoft.com/azure-storage/azurite:3.32.0").Build();
    
There might be cases where a new image version breaks an existing module configuration, like we recently had with [MSSQL](https://github.com/testcontainers/testcontainers-dotnet/issues/1246). When that happens, we update the module configuration accordingly to support multiple versions. Another good example is our [MongoDB](https://github.com/testcontainers/testcontainers-dotnet/blob/1d32bc86e902f4684c8b348dbb82a0f44a579c0e/tests/Testcontainers.MongoDb.Tests/MongoDbContainerTest.cs#L102-L117) module that supports multiple major versions too.

**Comment by rudiv** [comment]
This is why you don't start doing thing things (especially publicly) late at night, kids!

Thank you for the information and being kind about my stupidity - I'll be sure to delete my classes 😃
