### ISSUE TITLE
[Bug]: Keycloak 25 healthcheck endpoint not configured properly when using custom keycloak docker image

### ISSUE THREAD

**Issue by vfrz** [testcontainers/testcontainers-dotnet#1272]
### Testcontainers version

3.10.0 (Keycloak test container)

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

8

### Docker version

```shell
N/A
```

### Docker info

```shell
N/A
```

### What happened?

Since Keycloak version 25, the ready check is not working properly even with latest TestContainers.Keycloak nuget package (3.10.0) because we are using custom keycloak docker image with custom versioning.
The new endpoint is configured based on the image version: https://github.com/testcontainers/testcontainers-dotnet/pull/1213
I don't have a perfect solution in mind, but maybe making an extension method on the builder would be the best solution?

**Comment by HofmeisterAn** [comment]
If your custom image does not follow the semantic versioning of the official image, you can either override the default wait strategy or use the generic builder to create your own container configuration from scratch. Modules are pre-configured and opinionated, so we cannot support all types of customizations.

**Comment by vfrz** [comment]
Alright, understandable.
We did just that, we overrode the wait strategy.
