### ISSUE TITLE
Testcontainers - Docker is either not running or misconfigured

### ISSUE THREAD

**Issue by geekcharming** [testcontainers/testcontainers-dotnet#1296]
**Testcontainers version**: 4.0.0

**.Net Version**: 8.0

**Pipeline**: AzureDevops Yaml Pipeline 

**Host**: Windows

**Issue**: I have written some integration tests with Kusto Emulator and have been successfully able to run all my tests using Testcontainers locally using Docker Desktop. However, when I try running these tests on my Azure Devops PR build pipeline, I get the following error:
Docker is either not running or misconfigured. Please ensure that Docker is running and that the endpoint is properly configured. You can customize your configuration using either the environment variables or the ~/.testcontainers.properties file. For more information, visit:
https://dotnet.testcontainers.org/custom_configuration/ (Parameter 'DockerEndpointAuthConfig')

The Azure Devops pipeline (Container based template) already runs as a container which means all the tasks that we run including the task for running the integration test is part of that container:
Docker daemon API version: '1.44'
Docker client API version: '1.44'

**Comment by HofmeisterAn** [comment]
Please add the output of `docker version` and `docker info` from your agent.

> The Onebranch Azure Devops pipeline (Container based template) already runs as a container which means all the tasks that we run including the task for running the integration test is part of that container:

What do you mean by that? Which `vmImage` do you use? Do you run a [container job](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=linux#single-job-examples)?

**Comment by geekcharming** [comment]
Yes, it is a windows container job. 

pool:
  vmImage: 'windows-2019'
container: mcr.microsoft.com/windows/servercore:ltsc2019
steps: script: set

The containers are initialized with (Docker daemon API version: '1.44', Docker client API version: '1.44'). As a task on this pipeline I have added the docker installer taken from this documentation: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/docker-installer-v0?view=azure-pipelines

It may be considered as docker in docker kinda scenario

Output of docker version is:
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3

**Comment by HofmeisterAn** [comment]
I see. Unfortunately, it appears this setup is not supported by Microsoft's Windows agents. As you can see [here](https://dev.azure.com/HofmeisterAn/GitHub/_build/results?buildId=2322&view=logs&j=a709c304-b433-588f-e4f7-5b5f8d596449&t=7e81667f-f365-5e56-3d9b-9e8d4648183c&l=12), the Docker daemon socket (npipe) is not available for Windows container jobs, unlike in Linux container jobs. There's nothing we can do here. You may need to reach out to https://github.com/actions/runner-images for further insights. I know that mounting the Docker named pipe socket generally works, but it is [not supported](https://github.com/actions/runner-images/issues/6688) out of the box for Windows agents. However, I'm not certain of the exact mechanism Microsoft uses to provide the Docker UNIX socket in a Linux container job.

**Comment by HofmeisterAn** [comment]
Do you mind if we close the issue? I don't think we can fix this, as it is something Microsoft needs to address.

Instead of running a container job, you can run a regular Windows [agent](https://github.com/testcontainers/testcontainers-dotnet/actions/runs/11763672427/job/32767955591#step:8:30). Please be aware that the Windows agent **cannot** run Linux containers:

> Windows requires the host operating system version to match the container operating system version. You will find further information about Windows container version compatibility [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility).

**Comment by geekcharming** [comment]
Sure...we can close this...thanks for your time.
