### ISSUE TITLE
[Enhancement]: Azure Service Bus emulator

### ISSUE THREAD

**Issue by KSemenenko** [testcontainers/testcontainers-dotnet#1302]
### Problem

It’s nice to have Azure Service Bus emulator

### Solution

https://learn.microsoft.com/en-us/azure/service-bus-messaging/test-locally-with-service-bus-emulator?tabs=docker-linux-container

And

https://mcr.microsoft.com/en-us/artifact/mar/azure-messaging/servicebus-emulator/about

### Benefit

Azure Service Bus emulator - useful for tests

### Alternatives

No

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
If I am correct, the Azure Service Bus Emulator is not as straightforward as other modules because it requires a database container as well. Fortunately, we already have a module with similar requirements. I believe we can follow the implementation of our [WebDriver](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src/Testcontainers.WebDriver) module, which also sets up a network, network alias and connects multiple containers together.

**Comment by HofmeisterAn** [comment]
I started to work on the [module](https://github.com/testcontainers/testcontainers-dotnet/compare/feature/add-azure-service-bus-emulator) implementation.

**Comment by HofmeisterAn** [comment]
I'm almost done and ready to create the PR, but unfortunately, I'm running into an issue with the tests. It's something we've encountered before with other Azure client libraries. When I try to send a message to the emulator, it fails and responds with an error message that isn't related to the container instance, but rather to Azure itself (it looks like it sends the request to the wrong endpoint):

> The messaging entity 'sb://sbemulatorns.servicebus.onebox.windows-int.net/hello-queue' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.  TrackingId:256027e76d1e4df6a348e1aa9d674be9_G0, SystemTracker:gateway1, Timestamp:2024-11-23T09:21:53 (MessagingEntityNotFound). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.

https://github.com/testcontainers/testcontainers-dotnet/blob/7ef14374e2a0e9d3cda059048819284b32ff2f49/tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs#L35-L36

The connection string looks like:

    Endpoint=sb://127.0.0.1:53590/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true

Does someone know to configure the client?

**Comment by HofmeisterAn** [comment]
It looks like this is not necessarily a client issue. If I add an additional [delay](https://github.com/testcontainers/testcontainers-dotnet/blob/bce269e1f29bedc2322be36a9104334f44998ab0/tests/Testcontainers.ServiceBus.Tests/ServiceBusContainerTest.cs#L36), the test runs fine. I assume the console [log message](https://github.com/testcontainers/testcontainers-dotnet/blob/bce269e1f29bedc2322be36a9104334f44998ab0/src/Testcontainers.ServiceBus/ServiceBusBuilder.cs#L87) indicates readiness too early?

**Comment by KSemenenko** [comment]
I found an example client https://github.com/Azure/azure-service-bus-emulator-installer/blob/main/Sample-Code-Snippets/NET/ServiceBus.Emulator.Console.Sample/ServiceBus.Emulator.Console.Sample/Program.cs

**Comment by KSemenenko** [comment]
Maybe it need time to create a queue?

**Comment by KSemenenko** [comment]
As I see emailtaor use config.json with wheee it define queue.
And this `string queueName = "queue.1` will work wideout delays?

**Comment by HofmeisterAn** [comment]
I copied the example from MS and changed the queue name 👍, but didn't change anything.

**Comment by tj-spyro** [comment]
The MS example docker compose config explicitly uses port 5672 on the host and then no port specified in the connection string. Perhaps the client SDK only works on that port?

**Comment by HofmeisterAn** [comment]
I tried the default port (without a randomly assigned host port) and a connection string without the port as well. Same behavior. Interestingly, it works with the extra delay...

**Comment by HofmeisterAn** [comment]
I've created an upstream issue, right now, I have no idea how to reliably indicate readiness ☝️.

**Comment by HofmeisterAn** [comment]
I created a PR that includes a workaround, which adds an additional two-second wait before indicating readiness. It would be great if someone could review the PR and do some tests to check if the module works as expected 🙏.

**Comment by zaritskyi1** [comment]
Thank you for creating the PR! I tested the changes on my setup (Docker with Windows 10), and the module works fine for me overall. However, I noticed that the Reuse feature isn't working in my case. I suspect it might be related to the inner MSSQL container.

Let me know if you’d like me to share more details or try something specific to help debug this issue.
Thanks again for your work on this!

**Comment by HofmeisterAn** [comment]
Thank you for the tests.

> I noticed that the Reuse feature isn't working in my case. I suspect it might be related to the inner MSSQL container.

Ah, that makes sense. We do not forward this configuration to the MSSQL container builder. We have the same issue in the WebDriver module. Thank you for bringing this to my attention. I need to think about how we can modify the API to allow forwarding such configurations to the nested builder.

**Comment by riezebosch** [comment]
Just a bit late to the party, I implemented this myself in this [integration test](https://github.com/riezebosch/hypothesist/blob/main/ServiceBus/Hypothesist.ServiceBus.IntegrationTests/Fixture.cs) and was about to ask if a contribution was appreciated. Let me know if I can be of any help.
