### ISSUE TITLE
Add docker api endpoint configuration

### ISSUE THREAD

**Issue by RustyCZ** [testcontainers/testcontainers-dotnet#160]
**Is your feature request related to a problem? Please describe.**
I would like to start containers on remote docker engine. Sometimes localhost might be hardware limited to execute some tests e.g. not enough memory. This option would also enable running tests in parallel on multiple machines. 

**Describe the solution you'd like**
Expose DockerApiClient.Endpoint. This configuration should not be static to enable different configuration per test.

**Describe alternatives you've considered**
There are not many alternatives at the moment except for some dirty reflection code since everything is internal code.

**Additional context**
No additional context

**Comment by HofmeisterAn** [comment]
Yes, we definitely need that. I was about to implement that. A pull request is always welcome, otherwise I’ll have look at it, as soon as I’m back.

**Comment by HofmeisterAn** [comment]
Yes, we definitely need that. I was about to implement that. A pull request is always welcome, otherwise I’ll have look at it, as soon as I’m back.

**Comment by RustyCZ** [comment]
I can have a look at it. I think we should expose it in ITestcontainersBuilder. Something like
`
var testcontainersBuilder = new TestcontainersBuilder().WithDockerEngine(new Uri("specified engine"))
`

**Comment by HofmeisterAn** [comment]
I think so too. Maybe we can cache the Docker clients for each Docker engine, so that we don’t have to recreate them all the time.

**Comment by HofmeisterAn** [comment]
@RustyCZ I did some changes, this ([feature/add-custom-docker-api-endpoint](https://github.com/HofmeisterAn/dotnet-testcontainers/compare/feature/add-custom-docker-api-endpoint?expand=1)) should probably work. However, I still need to take a closer look and clean up the code.

**Comment by HofmeisterAn** [comment]
@RustyCZ If you like, you can test the changes in the branch. I only have to add some more documentation and a way to purge orphaned containers. You should be able to set the Docker API endpoint with: `WithDockerEndpoint`.
