### ISSUE TITLE
Container's volumes not deleted with the containers itself

### ISSUE THREAD

**Issue by dortibi** [testcontainers/testcontainers-dotnet#168]
I used Postgres container and I also created a new type (Vault container).
each of the containers mounted a volume to the disk, after the tested finished and the container deleted, the volume was still in the disk and I needed to use `docker system prune` for deleted them.

**To Reproduce**
1. Run Postgres test container
2. Finish the UT gracefully saw the dispose will call
3. go to the terminal and run `docker volume ls -f dangling=true`
and see the unused volumes

I tried to override the dispose method in the container class I created but the details of the containers and the used volumes are private and I couldn't access it for calling the remove after the docker removed.
also I could use your docker api client since its internal so anyway I need to do the system call separately.

there is other way to do it, by calling the container remove with the flag `-v` that delete the *unnamed volumes* with it (only unnamed volumes, I'm not sure what kind of volumes you using)

**Desktop (please complete the following information):**
 - Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
- Nuget version - 0.0.9

**Comment by HofmeisterAn** [comment]
I guess we need to set the [ContainerRemoveParameters](https://github.com/microsoft/Docker.DotNet/blob/master/src/Docker.DotNet/Models/ContainerRemoveParameters.Generated.cs) property `RemoveVolumes` in:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/fc9e6566acbef849ce215b801406852f3395d811/src/DotNet.Testcontainers/Client/TestcontainersClient.cs#L64

Would you like to create a pull request?
