### ISSUE TITLE
ImageFromDockerfileBuilder does not have possibility to specify docker file name

### ISSUE THREAD

**Issue by paulvanbladel** [testcontainers/testcontainers-dotnet#180]
Nice project !
Would be cool to be able to specify name of dockerfile. Now you can only specify the directory.

**Comment by HofmeisterAn** [comment]
Do you talk about the `ImageFromDockerfileBuilder`? This should be pretty simple, we just need to extend the interfaces `IImageFromDockerfileBuilder` and `IImageFromDockerfileConfiguration` and pass the Dockerfile name to: https://github.com/HofmeisterAn/dotnet-testcontainers/blob/a379b7817a40565283ce268de934f8f88174c858/src/DotNet.Testcontainers/Clients/DockerImageOperations.cs#L87

I can probably take a look at it this weekend. Or would you like to create a PR?

**Comment by HofmeisterAn** [comment]
PR #182.

**Comment by paulvanbladel** [comment]
Thanks a lot Andrė.

**Comment by paulvanbladel** [comment]
@HofmeisterAn . 
Is this also on nuget André?
Cheers.

**Comment by HofmeisterAn** [comment]
@paulvanbladel Yes, each commit on develop publishes a new prerelease in your case [1.1.0-beta.20200110.4](https://www.nuget.org/packages/DotNet.Testcontainers/1.1.0-beta.20200110.4).
