### ISSUE TITLE
Support testcontainers to run inside a docker container with mounted docker.socket

### ISSUE THREAD

**Issue by farodin91** [testcontainers/testcontainers-dotnet#213]
**Is your feature request related to a problem? Please describe.**
testcontainers-java supports running testcontainers inside a containers and access side spawned containers

**Describe the solution you'd like**
Instead of using localhost(127.0.0.1), testcontainers should use the gateway ip container if it is running inside a container: https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/TestContainers/Core/Containers/Container.cs#L195-L212

**Comment by HofmeisterAn** [comment]
I think we just need to extend:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/173aa1ff6c854df79e603175db2d6c6b772f4507/src/DotNet.Testcontainers/Containers/Modules/TestcontainersContainer.cs#L73

A PR is welcome, would you like to do that? _I hope we get the official repository working in the next few days and are able to switch._

**Comment by farodin91** [comment]
I will work on it. It could be not that easy to add a test beside an unit test.

**Comment by HofmeisterAn** [comment]
@farodin91 Thanks, I'll check and merge it later that day.
