### ISSUE TITLE
ImageFromDockerfileBuilder does not honour the .dockerignore file.

### ISSUE THREAD

**Issue by paulvanbladel** [testcontainers/testcontainers-dotnet#218]
Trying to build image from docker file but fails because process cannot access stuff in .vs folder etc.
Normally, when building image from commandline, the dockerignore file makes sure that all these files are excluded.

```
 await new ImageFromDockerfileBuilder()
                .WithDeleteIfExists(true)
                .WithDockerfileDirectory(@"D:\tfs\OutboxPattern")
                .WithName("Subsystem1.Api.Dockerfile")
                .Build();
```
This is the structure of my project, so the dockerfile is in the root while the project that is references in the dockerfile is in a sub folder.
Any ideas to get this working?
Thanks a lot.

![image](https://user-images.githubusercontent.com/4886272/75607385-da59e300-5af6-11ea-8112-334a3e657800.png)

**Comment by HofmeisterAn** [comment]
The implementation of `DockerfileArchive` does not support `.dockerignore` yet. It adds all files in `DockerfileDirectory` to the temporary created `Dockerfile.tar`. Either you move your Dockerfile, to another directory which contains only Docker image related files or you contribute and implement the `.dockerignore` feature to `DockerfileArchive` - that would be really nice!

It should be enough to filter the ignored directories and files here: https://github.com/HofmeisterAn/dotnet-testcontainers/blob/d6fbb00422e33e3187f29713e7283e7f31bc06e3/src/DotNet.Testcontainers/Images/Archives/DockerfileArchive.cs#L63-L65

**Comment by HofmeisterAn** [comment]
PR #269.
