### ISSUE TITLE
Image name is not parsed correctly

### ISSUE THREAD

**Issue by superkartoffel** [testcontainers/testcontainers-dotnet#232]
When I try to start a TestContainer with an Azurite container (mcr.microsoft.com/azure-storage/azurite), it fails with the following message:
`Docker.DotNet.DockerApiException : Docker API responded with status code=NotFound, response={"message":"manifest for mcr.microsoft.com/azure-storage:latest not found: manifest unknown: manifest unknown"}`
It appears as if the name of the container is not parsed correctly (azure-storage/azurite vs azure-storage:latest).

**To Reproduce**
Dot not work:
>`            var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()`
>`              .WithImage("mcr.microsoft.com/azure-storage/azurite")`
>`              .WithName("azurite")`
>`              .WithPortBinding(10000)`
>`              .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(10000));`
>`            BlobContainer = testcontainersBuilder.Build();`
>`            await BlobContainer.StartAsync();`

Note: The problem does not appear if a version is added to the container name. e.g. mcr.microsoft.com/azure-storage/azurite:latest
Does work:
>`            var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()`
>`              .WithImage("mcr.microsoft.com/azure-storage/azurite:latest")`
>`              .WithName("azurite")`
>`              .WithPortBinding(10000)`
>`              .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(10000));`
>`            BlobContainer = testcontainersBuilder.Build();`
>`            await BlobContainer.StartAsync();`

**Expected behavior**
The container should start.

dotnet-testcontainers 1.2.0

**Comment by HofmeisterAn** [comment]
Should be fixed in #233 and published in `1.3.0-beta.20200409.3`.
