### ISSUE TITLE
Restoring Posgresql by commands

### ISSUE THREAD

**Issue by mubeda** [testcontainers/testcontainers-dotnet#243]
Basically the problem appears when i want to restore a posgresql via commands. I followed this tutorial:

[https://blog.koley.in/2019/backup-and-restore-postgresql-database-running-on-docker](url)

if i do it using the windows console works fine, but i didn't find a way to do it using the framework. In the code the first  three commands are executed without problems, but the one related with the restore from a file is doesn't . 

`
        await testcontainer.StartAsync();

        var task = testcontainer.ExecAsync(new[] { "/bin/sh", "-c", "psql -U postgres -c \"CREATE USER user01 PASSWORD 'user01 ';\"", "exit 255" });
        task.Wait();
        task = testcontainer.ExecAsync(new[] { "/bin/sh", "-c", "psql -U postgres -c \"CREATE DATABASE user01DB ;\"" });
        task.Wait();
        task = testcontainer.ExecAsync(new[] { "/bin/sh", "-c", "psql -U postgres -c \"GRANT ALL PRIVILEGES ON DATABASE user01DB TO user01; \"", "exit 255" });
        task.Wait();
        task = testcontainer.ExecAsync(new[] { "/bin/sh", "-c", "psql -U postgres -d user01DB < \"X:\\tmp\\mybackup.sql\"", "exit 255" });
        task.Wait();
   
`
The command using the windows console is:
`docker exec -i <instancename> psql -U postgres -d user01DB  < "X:\temp\mybackup.sql"`
It works without problems
I also downloaded your source code and i discovered that ContainerExecCreateParameters is not exposed in .ExecAsync in order to set Privileged = true. i changed that to do a quick test, but no success.
Do you have any idea on how i can solve this problem? Also it will be great to expose ContainerExecCreateParameters as parameter so an user can have more grain control on how to execute commands in docker.

**Comment by HofmeisterAn** [comment]
Based on your issue it's hard to tell which part is not working. I don't see any error message or stack trace. As you already mentioned, not all properties of `ContainerExecCreateParameters` are exposed, but I don't think you really need them.

Are the other PostgreSQL commands running or is just the command with `mybackup.sql` failing? What error code do you get back?

Instead you can do:

- Create a custom image which initializes the database.
- Mount a volume and load the script `mybackup.sql` from the volume.

If you dig deeper into the issue and find some framework related issues a PR would be really nice. I'm also happy to help. Maybe you can setup a branch to reproduce the issue.

**Edit**: Your link is not working.

**Comment by HofmeisterAn** [comment]
@mubeda I did some small tests. In case of an error it would be nice to get the error message in addition to the exit code (maybe you would like to create an PR?). Anyway, I had no major issues to execute the examples above, see my example code and comments below:

```csharp
var testcontainersBuilder = new TestcontainersBuilder<PostgreSqlTestcontainer>()
  .WithDatabase(new PostgreSqlTestcontainerConfiguration
  {
    Database = "db",
    Username = "postgres",
    Password = "postgres",
  })
  .WithMount("C:/Users/myusername/Desktop", "/tmp");

await using (var testcontainer = testcontainersBuilder.Build())
{
  await testcontainer.StartAsync();

  // (1) Runs a simple psql command in the container. 
  var exitCode = await testcontainer.ExecAsync(new[] { "/bin/sh", "-c",
    "psql --host localhost --username postgres --password postgres --dbname db --command SELECT 1"});

  // (2) Runs a psql script in the container.
  // You need to mount the volume to the script first (see `WithMount`) or use any other technique to place the script in the container.
  exitCode = await testcontainer.ExecAsync(new[] { "/bin/sh", "-c",
    "psql --host localhost --username postgres --password postgres --dbname db < /tmp/foo.sql"});

  // (3) !ATTENTION! This WON'T work, because the command is executed in the container.
  // You can't access `C:/Users/myusername/Desktop/foo.sql`.
  exitCode = await testcontainer.ExecAsync(new[]  { "/bin/sh", "-c",
    "psql --host localhost --username postgres --password postgres --dbname db < C:/Users/myusername/Desktop/foo.sql"});

  // (4) Reads the psql script from your host and passes it into the psql standard input.
  exitCode = await testcontainer.ExecAsync(new[] { "/bin/sh", "-c",
    $"psql --host localhost --username postgres --password postgres --dbname db << EOF\n{await File.ReadAllLinesAsync("C:/Users/myusername/Desktop/foo.sql")}\nEOF"});
}
```

Please notice, your attempt `(3)` can't work. I would go with `(2)` or `(4)`.

It's probably necessary to pass the credentials to `psql`. Otherwise I get following exit code `2`:
> If the connection to the server went bad and the session was not interactive.

**Comment by mubeda** [comment]
Hey Andre! Thank you so much for given me other alternatives, i will try them, and let you know the result.
I really apreciate it.

**Comment by mubeda** [comment]
Just tested 2 and 4. Option 4) didn't worked for me, becasue the script is huge and fails, but is only because the script, no about the implementation.  Option 2) worked for me, the only drawback is that you need to manually add Fileshared permission to such mount on Docker for Windows. But... i can leave with that.  Thank you so much for you help!
Kinds Regars,
Mauro
