### ISSUE TITLE
Add Couchbase Testcontainer

### ISSUE THREAD

**Issue by mustafaonuraydin** [testcontainers/testcontainers-dotnet#258]
Couchbase Server is an open source, distributed, JSON document database. In dotnet-testcontainers project there is some pre-configured containers for easy to use. 

The issue is add couchbase testcontainer as pre-configured container.

This container should provide following features;
1. Create initial cluster and create customizable admin user with environment parameter
2. Create initial bucket or buckets
3. Add startup strategy for Couchbase
4. Create bucket function
5. Flush bucket function

**Comment by HofmeisterAn** [comment]
We should merge #261. Based on the existing example configurations you can create the configuration for Couchbase. This should be pretty straight forward. It would be nice if you keep the other configurations in mind and share patterns, use interfaces, add tests, etc.

**Comment by HofmeisterAn** [comment]
Closed in #296, #298 and published in `1.4.0-beta.20200721.12`.
