### ISSUE TITLE
RabbitMq Client Extension 

### ISSUE THREAD

**Issue by mustafaonuraydin** [testcontainers/testcontainers-dotnet#259]
RabbitMQ is an open-source message-broker that originally implemented the Advanced Message Queuing Protocol (AMQP) and has since been extended with a plug-in architecture to support Streaming Text Oriented Messaging Protocol (STOMP), MQ Telemetry Transport (MQTT), and other protocols.

The dotnet-testconatiners providing pre-configured RabbitMQ testcontainer. 

The issue is add RabbitMq Client extension for pre-configured RabbitMQ testcontainer for using container efficiently.

This feature should provide following features;

1. Create Exchange
2. Create Queue
3. Bind Queue
4. Publish message
5. Get message from queue
6. Purge Queue

**Comment by HofmeisterAn** [comment]
Closed for inactivity.
