### ISSUE TITLE
Mssql Database Configuration Update

### ISSUE THREAD

**Issue by mustafaonuraydin** [testcontainers/testcontainers-dotnet#260]
Microsoft SQL Server is a relational database management system developed by Microsoft. 

The dotnet-testconatiners providing pre-configured Mssql.

The issue is update MsSqlContainerConfiguration for following features;

1. Configurable base image for different versions of Mssql
2. Customizable environment functionality 
(For example optimize resources for ci pipeline "MSSQL_MEMORY_LIMIT_MB"]= "2048")
3. Implement set for Database, Username
4. Validate password strength for mssql password and throw meaningful runtime exception.

**Comment by HofmeisterAn** [comment]
> 1. Configurable base image for different versions of MsSql:

I prepared a PR (#261) that removes the sealed modifier and allows us to pass different images to the configuration. I think this should be the start.

> 2. Customizable environment functionality:

Any suggestion how we should provide this functionality (e. g. with a Property `MaximumMemory` or a method like `WithMaximumMemory()`, etc.)? I only care that all classes use the same approach. We may need some architectural changes to provide a convenient configuration too.

> 3. Implement set for Database, Username

We have to take a look at the Docker image from Microsoft. I don't know if we can change the username or password at all.

> 4. Validate password strength for MsSql password and throw meaningful runtime exception.

Good point. See 2. & 3.

**Comment by HofmeisterAn** [comment]
Closed for inactivity.
