### ISSUE TITLE
withImage does not pull image from registry

### ISSUE THREAD

**Issue by v-valk** [testcontainers/testcontainers-dotnet#304]
**Describe the bug**
Chain of issues:
1.  `.WithImage()` does not pull specified image
2.  `.WithWaitStrategy(Wait.ForUnixContainer()` does not fail even though the container is not up and ports should be unavailable
                    `.UntilPortIsAvailable(2525)`
                    `.UntilPortIsAvailable(9001));`

**To Reproduce**
1. Make sure you don't have the image you want to run locally
2. Start a draft unit test project, create a class then add the code below:
3. Change `.WithImage()` to your repository

 ```
private async Task SetupContainer()
        {
            var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
                .WithImage("myRegistry/myContainer:latest")
                .WithName("myNameHerroFren")
                .WithPortBinding(2525, 2525)
                .WithPortBinding(9001, 9001)
                .WithExposedPort(2525)
                .WithExposedPort(9001)
                .WithCleanUp(false)
                .WithWaitStrategy(Wait.ForUnixContainer()
                    .UntilPortIsAvailable(2525)
                    .UntilPortIsAvailable(9001));
            testcontainersBuilder.Build();
            IDockerContainer testcontainer = testcontainersBuilder.Build();
            _testOutputHelper.WriteLine("starting container?");
            await testcontainer.StartAsync();
        }

        [Fact]
        async Task TestContainerSetup()
        {
            SetupContainer();
            _testOutputHelper.WriteLine("test");
        }

```
**Expected behavior**
Either:
- A new container is created and started
- An error is given if an image cannot be found/resource cannot be accessed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10 enterprise
- Docker version: 2.3.0.4(46911)
- xUnit latest

**Additional context**
- If I have image locally - container will be created
- If I have image locally - after creating a container `.WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(2525).UntilPortIsAvailable(9001));` will be ignored
- If I remove the image and try the code above - it shows test as passed, however it does not pull an image, does not launch a container

**Comment by HofmeisterAn** [comment]
@v-valk each .NET Testcontainers test pulls its image. It does not use any local images. Your example is not properly set-up:

1. You do not `await` the result of `SetupContainer();`. Try `await SetupContainer();` instead. Have a look at the .NET Testcontainers tests. They have some good examples, like the [CouchbaseFixture](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/src/DotNet.Testcontainers.Tests/Fixtures/Containers/Modules/Databases/CouchbaseFixture.cs) and [CouchbaseTestcontainerTest](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/46797ed08f9929911b331e1c26c919ec0f1b1547/src/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Database/CouchbaseTestcontainerTest.cs#L11) for xUnit.
2. If you are using a private registry, you need to authenticate against it with `WithRegistryAuthentication`.

**Comment by v-valk** [comment]
@HofmeisterAn thank you very much for the fast response! Can you please confirm that if I use
`.WithRegistryAuthentication()
.WithImage()`
It will attempt to log in and pull the image?

**Comment by HofmeisterAn** [comment]
> @HofmeisterAn thank you very much for the fast response! Can you please confirm that if I use `.WithRegistryAuthentication().WithImage()` it will attempt to log in and pull the image?

Yes, if you do it right 😄. I use it too. Your test should look something like:

```csharp
var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
  .WithName("myNameHerroFren")
  .WithImage("myRegistry/myContainer:latest")
  .WithRegistryAuthentication("YOUR_DOCKER_REGISTRY_ENDPOINT", "YOUR_USERNAME", "YOUR_PASSWORD")
  .WithPortBinding(2525, 2525)
  .WithPortBinding(9001, 9001)
  .WithExposedPort(2525)
  .WithExposedPort(9001)
  .WithCleanUp(false)
  .WithWaitStrategy(Wait.ForUnixContainer()
    .UntilPortIsAvailable(2525)
    .UntilPortIsAvailable(9001));

await using (IDockerContainer testcontainer = testcontainersBuilder.Build())
{
  await testcontainer.StartAsync();
  // Your code.
}
```

or as I wrote in the previous message use the xUnit [shared context](https://xunit.net/docs/shared-context). Please have a look at the tests in this repository. This should help you a lot.

**Comment by HofmeisterAn** [comment]
If you need further help, let me know. In the meantime, I will close this issue.
