### ISSUE TITLE
TestcontainersContainer.StartAsync breaks coverlet code coverage

### ISSUE THREAD

**Issue by MrDazLive** [testcontainers/testcontainers-dotnet#309]
**Describe the bug**
When using test containers as part of a test scenario, calling container.StartAsync will result in code coverage producing inaccurate results.

Code coverage may return 0% coverage, whereas removing the .StartAsync method will return the expected code coverage.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a new test project.
2. Include DotNet.TestContainers & coverlet.msbuild
3. Write a unit test, that calls the .StartAsync method.
4. Run tests `dotnet test <test-project>.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura`

**Expected behavior**
Code coverage is produced, as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/7346602/90245827-4de47800-de2b-11ea-8a85-61cf84cc46ef.png)

**Version**
 - 1.3.0
 - 1.4.0-beta.20200807.5

**Comment by HofmeisterAn** [comment]
@MrDazLive I'm sorry, I can not reproduce your issue. It would also surprise me very much, because this project [enables](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/46797ed08f9929911b331e1c26c919ec0f1b1547/build.cake#L92-L94) code coverage and depends on [coverlet.msbuild](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/46797ed08f9929911b331e1c26c919ec0f1b1547/src/DotNet.Testcontainers.Tests/DotNet.Testcontainers.Tests.csproj#L9) too. But maybe we can figure out what's wrong with your set-up.

I use following class to try to reproduce your issue:

```csharp
public class Test
{
  [Fact]
  public async Task SampleTest()
  {
    await using (var testcontainers  = new TestcontainersBuilder<TestcontainersContainer>()
      .WithName("GitHub-Issue-309")
      .WithImage("redis:latest")
      .WithPortBinding(6379, true)
      .Build())
    {
      await testcontainers.StartAsync();
    }

    Console.WriteLine($"{nameof(this.SampleTest)} is finished.");
  }
}
```

I run `dotnet test src/DotNet.Testcontainers.Tests/DotNet.Testcontainers.Tests.csproj --filter=FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Test.SampleTest /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura` and get following output:

```
2020-08-14 15:23:44.489 +02:00 [INF] DotNet.Testcontainers.Clients.DockerContainerOperations Container "4d801f7b1f4025407e0cffe611ceb7a329743fb0c12e1a1ffaadfd289c8c08fc" created
2020-08-14 15:23:44.528 +02:00 [INF] DotNet.Testcontainers.Clients.DockerContainerOperations Attaching "DotNet.Testcontainers.Containers.OutputConsumers.Common.DoNotConsumeStdoutOrStderr" at container "4d801f7b1f4025407e0cffe611ceb7a329743fb0c12e1a1ffaadfd289c8c08fc"
2020-08-14 15:23:44.557 +02:00 [INF] DotNet.Testcontainers.Clients.DockerContainerOperations Starting container "4d801f7b1f4025407e0cffe611ceb7a329743fb0c12e1a1ffaadfd289c8c08fc"
2020-08-14 15:23:45.191 +02:00 [INF] DotNet.Testcontainers.Clients.DockerContainerOperations Removing container "4d801f7b1f4025407e0cffe611ceb7a329743fb0c12e1a1ffaadfd289c8c08fc"
SampleTest is finished.

Der Testlauf war erfolgreich.
Gesamtzahl Tests: 1
     Bestanden: 1
 Gesamtzeit: 3,7895 Sekunden

Calculating coverage result...
  Generating report '/Users/andre.hofmeister/Desktop/git/dotnet/dotnet-testcontainers/src/DotNet.Testcontainers.Tests/coverage.netcoreapp3.1.cobertura.xml'
```

I guess something in your code is blocking and does not complete `StartAsync`. Did you try the provided `RedisTestcontainer` container or anything else? There is also an example for Redis in the unit tests. You will find it [here](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/src/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Database/RedisTestcontainerTest.cs).

**Comment by MrDazLive** [comment]
Sorry, I wasn't clear in the post. A code coverage report is produced, with 0% coverage. When removing the StartAsync, the percentage is as expected. I will expand on the original post, for clarity.

I shall also attempt with the redis sample that you have provided, and see if I receive the same outcome.

**Comment by HofmeisterAn** [comment]
> Sorry, I wasn't clear in the post. A code coverage report is produced, with 0% coverage. When removing the StartAsync, the percentage is as expected. I will expand on the original post, for clarity.
> 
> I shall also attempt with the redis sample that you have provided, and see if I receive the same outcome.

Odd. That's working too. I changed the test and added:

```csharp
var foo = new SampleModel();
Assert.NotNull(foo);
```

and I get following report:

```xml
<class name="DotNet.Testcontainers.SampleModel" filename="SampleModel.cs" line-rate="1" branch-rate="1" complexity="1">
  <methods>
    <method name=".ctor" signature="()" line-rate="1" branch-rate="1" complexity="1">
      <lines>
        <line number="7" hits="1" branch="False" />
        <line number="8" hits="1" branch="False" />
        <line number="9" hits="1" branch="False" />
        <line number="10" hits="1" branch="False" />
      </lines>
    </method>
  </methods>
  <lines>
    <line number="7" hits="1" branch="False" />
    <line number="8" hits="1" branch="False" />
    <line number="9" hits="1" branch="False" />
    <line number="10" hits="1" branch="False" />
  </lines>
</class>
```

I'm pretty sure the issue is not related to .NET Testcontainers, but I agree, it is weird. What result does the console show? Do you run `debug` or `release`?  Have you seen https://github.com/coverlet-coverage/coverlet/issues/732?

**Comment by MrDazLive** [comment]
On further inspection, it appears to only impact properties with `{get; set;}`. Again, removing StartAsync appears to resolve it.

```csharp
public class SampleModel
{
    // Returns Coverage
    public string StringValue;
}
```

```csharp
public class SampleModel
{
    // Returns No Coverage
    public string StringValue { get; set; }
}
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<class name="ClassLibrary1.SampleModel" filename="Users\darien.livermore\tmp\TestContainer\ClassLibrary1\SampleModel.cs" line-rate="0" branch-rate="1" complexity="1">
    <methods>
        <method name="get_StringValue" signature="()" line-rate="0" branch-rate="1" complexity="1">
            <lines>
                <line number="8" hits="0" branch="False" />
            </lines>
        </method>
    </methods>
    <lines>
        <line number="8" hits="0" branch="False" />
    </lines>
</class>
```

**Comment by HofmeisterAn** [comment]
@MrDazLive event that works. I attached my [example.zip](https://github.com/HofmeisterAn/dotnet-testcontainers/files/5075635/Example.zip), maybe that helps you to figure out the issue.

<img width="1280" alt="Bildschirmfoto 2020-08-14 um 18 04 41" src="https://user-images.githubusercontent.com/9199345/90269553-15f42980-de59-11ea-8090-c5d94fb4e897.png">

**Comment by MrDazLive** [comment]
> @MrDazLive event that works. I attached my [example.zip](https://github.com/HofmeisterAn/dotnet-testcontainers/files/5075635/Example.zip), maybe that helps you to figure out the issue.
> 
> <img alt="Bildschirmfoto 2020-08-14 um 18 04 41" width="1280" src="https://user-images.githubusercontent.com/9199345/90269553-15f42980-de59-11ea-8090-c5d94fb4e897.png">

Would you consider this to be working as expected?

Commenting out the StartAsync (line 20) would result in get methods being hit.

**Comment by HofmeisterAn** [comment]
> Would you consider this to be working as expected?

Yes it is working as expected. Do you expect the setter in the coverage file too? Then you **shouldn't** use a single line property. This is how coverlet works.

```csharp
public class SampleModel
{
  private string _sampleValue;

  public string SampleValue
  {
    get
    {
      return this._sampleValue;
    }
    set
    {
      this._sampleValue = value;
    }
  }
}
```

The upper example will generate:

```xml
<class name="ClassLibrary1.SampleModel" filename="Users/andre.hofmeister/Downloads/Example/ClassLibrary1/SampleModel.cs" line-rate="0" branch-rate="1" complexity="2">
  <methods>
    <method name="get_SampleValue" signature="()" line-rate="0" branch-rate="1" complexity="1">
      <lines>
        <line number="9" hits="0" branch="False" />
        <line number="10" hits="0" branch="False" />
        <line number="11" hits="0" branch="False" />
      </lines>
    </method>
    <method name="set_SampleValue" signature="(System.String)" line-rate="0" branch-rate="1" complexity="1">
      <lines>
        <line number="13" hits="0" branch="False" />
        <line number="14" hits="0" branch="False" />
        <line number="15" hits="0" branch="False" />
      </lines>
    </method>
  </methods>
  <lines>
    <line number="9" hits="0" branch="False" />
    <line number="10" hits="0" branch="False" />
    <line number="11" hits="0" branch="False" />
    <line number="13" hits="0" branch="False" />
    <line number="14" hits="0" branch="False" />
    <line number="15" hits="0" branch="False" />
  </lines>
</class>
```

> Commenting out the StartAsync (line 20) would result in get methods being hit.

It is not necessary to comment that line out. It's working with that line too.

**Comment by MrDazLive** [comment]
It just doesn't seem right, that commenting out this method produces different code coverage results. 

![image](https://user-images.githubusercontent.com/7346602/90272691-a2045200-de55-11ea-8477-43403e31067c.png)
![image](https://user-images.githubusercontent.com/7346602/90272955-1808b900-de56-11ea-9dbc-d2971d05a2de.png)

**Comment by HofmeisterAn** [comment]
Now I see. You are talking about the `hits` attribute, right? I thought you are talking about an empty file - sorry. Did you try `opencover` instead of `cobertura`?

**Comment by MrDazLive** [comment]
Unfortunately, it's the same result. With StartAsync, it returns 0% line/method coverage. Without StartAsync, it returns 100% line/method coverage.

**Comment by HofmeisterAn** [comment]
@MrDazLive can you test the behavior with the new snapshot version `1.4.0-beta.20200815.5`?

**Comment by MrDazLive** [comment]
@HofmeisterAn I can confirm that this works in `1.4.0-beta.20200815.5`. I have also verified this in the project that it was originally noticed.

Thanks alot, for the quick turn around!
