### ISSUE TITLE
support for --link while building container

### ISSUE THREAD

**Issue by sadunaresh** [testcontainers/testcontainers-dotnet#324]
Looking to achieve something like below,

`docker run --rm --name web2 --link db:db training/webapp env`

is "--link" supported with any of existing supported command in the library?

**Comment by HofmeisterAn** [comment]
As far as I know the `--link` flag is a deprecated legacy feature of Docker. I think it’s recommend to use user-defined networks to facilitate communication between containers.

Until now networks are not implemented and part of this library. If you need the network feature, a pull request and your contribution is more than welcome.
