### ISSUE TITLE
Pulling an image (with namespace) from a private container registry does not work

### ISSUE THREAD

**Issue by fgheysels** [testcontainers/testcontainers-dotnet#329]
**Describe the bug**
Not sure if it is a bug, I might be doing something wrong.
I want to pull an image from a private container registry, and to do that, I use the following code:

```
var myContainer = new TestcontainersBuilder<TestcontainersContainer>()
                                    
              .WithImage("myregistry.azurecr.io/namespacepart1/namespacepart2/imagename:latest")
              .WithRegistryAuthentication("https://myregistry.azurecr.io", "username", "p4ssw0rd")
              .WithName("processor-end2endtests")
              .Build();

await myContainer.StartAsync();
```

When starting the container, I get an error which says:

> 'Docker API responded with status code=InternalServerError, response={"message":"Get https://registry-1.docker.io/v2/namespacepart2/imagename/manifests/latest: unauthorized: incorrect username or password"}

I've double checked the username & password, but everything should be ok.
I do wonder if the protocol that I specify for the registryEndpoint parameter in `WithRegistryAuthentication` is correct.  (If I do notspecify a protocol, an exception is thrown saying that the endpoint does not represent a valid Uri).

Since the WithRegistryAuthentication method is marked as obsolete, I've also tried to first make sure that I'm authenticated with the Azure Container Registry in question by executing an `az acr login` command, but this doesn't help.

**Comment by fgheysels** [comment]
What I do notice, is that I want to pull the image `namespacepart1/namespacepart2/imagename` but the exception message mentions an url which says `https://registry-1.docker.io/v2/namespacepart2/imagename/manifests/latest` so in fact, the first part of the namespace is missing.

**Comment by fgheysels** [comment]
Another update:

I've pushed my image to the Azure Container Registry without namespaces, so the image name is now just `imagename`.

I've updated the code to build the container to this:

```csharp
var myContainer = new TestcontainersBuilder<TestcontainersContainer>()                                 
              .WithImage("myregistry.azurecr.io/imagename:latest")
              .WithRegistryAuthentication("https://myregistry.azurecr.io", "username", "p4ssw0rd")
              .WithName("processor-end2endtests")
              .Build();

await myContainer.StartAsync();
```
And this works:  the container can be started.
So, I guess there must be a problem in the procedure that chops that image-name to determine the docker endpoint that must be used to pull the image ?

**Comment by HofmeisterAn** [comment]
>What I do notice, is that I want to pull the image namespacepart1/namespacepart2/imagename but the exception message mentions an url which says https://registry-1.docker.io/v2/namespacepart2/imagename/manifests/latest so in fact, the first part of the namespace is missing.

Yes you're right. `DockerImage` does not parse `myregistry.azurecr.io/namespacepart1/namespacepart2/imagename:latest` correct. I didn't know that Docker supports nested «namespaces» / «names».

Basically we need to fix: https://github.com/HofmeisterAn/dotnet-testcontainers/blob/3fc46c73795eeb997afc6337e2180fdbb40fcf3a/src/DotNet.Testcontainers/Images/DockerImage.cs#L18

and add a proper parser that maps the properties correct and set `FullName`.

<hr />

In the meantime you could try to create your `IDockerImage` argument a little bit different, try:

```csharp
.WithImage(new DockerImage("myregistry.azurecr.io", "namespacepart1/namespacepart2/imagename", "latest"))
```

instead.

**Comment by fgheysels** [comment]
Thanks, using `.WithImage(new DockerImage("myregistry.azurecr.io", "namespace1/namespace2/imagename", "tag"))` solves the issue for now.

**Comment by HofmeisterAn** [comment]
@fgheysels If you like you can test the latest snapshot version `1.5.0-beta.20201009.5`. The issue should be fixed.

**Comment by fgheysels** [comment]
@HofmeisterAn , I have tested this with `1.5.0-beta20201010.3` and the issue is indeed fixed.
Thanks.
