### ISSUE TITLE
CI Pipeline for Test Containers

### ISSUE THREAD

**Issue by bozd4g** [testcontainers/testcontainers-dotnet#333]
Hello,

How can i run test containers on ci pipeline? Can you add an example for that?

When i run all tests on pipeline, I'm getting an error as below;
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Cannot assign requested address (/var/run/docker.sock)

or

System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Cannot assign requested address (/tcp://localhost:2375)

Also [.WithDockerEndpoint] extension method does not work.

Thanks.

**Comment by mustafaonuraydin** [comment]
Hello Furkan @bozd4g ,

Which CI pipeline are you using? In you pipeline you should be sure that you can access your docker environment like DIND (Docker in docker) or DND (Docker near docker)

In your first error, you are using docker socket -> /var/run/docker.sock , for this sample, you need to mount socket file.

In your second error, you are trying to connect over docker api. Try to make debug and check is docker available and accessible for that.

Please do not hesitate to contact with me for further questions.

**Comment by bozd4g** [comment]
Thank you so much @mustafaonuraydin 🙏
