### ISSUE TITLE
Cannot Initialize Couchbase Container

### ISSUE THREAD

**Issue by dogac00** [testcontainers/testcontainers-dotnet#354]
I cannot initialize the couchbase container. My code is this:
``` cs
public static async Task Main(string[] args)
        {
            var container = new TestcontainersBuilder<CouchbaseTestcontainer>()
                .WithDatabase(new CouchbaseTestcontainerConfiguration()
                {
                    Username = "administrator",
                    Password = "password",
                    BucketName = "mybucket"
                })
                .WithExposedPort(8091)
                .WithExposedPort(8093)
                .WithExposedPort(11210)
                .WithPortBinding(8091, 8091)
                .WithPortBinding(8093, 8093)
                .WithPortBinding(11210, 11210)
                .Build();

            await container.StartAsync();

            var cluster = await Cluster.ConnectAsync(
                container.ConnectionString,
                container.Username,
                container.Password);

            var bucket = await cluster.BucketAsync("mybucket");

            var collection = bucket.DefaultCollection();

            await collection.UpsertAsync("id", "document content");
            var result = await collection.GetAsync("id");
            var stringContent = result.ContentAs<string>();

            Console.WriteLine(stringContent);
        }
```

When I run this code, the container is builded and there is no errors. But when `StartAsync` gets called, the application hangs forever and cannot start couchbase container.

When I check Docker, the test container is created and showing "Running". When I look at the logs of the container, I see that it waits for cluster initialization.

How can I initialize my cluster after creating the test container?

Here is my Docker logs:
```
Waiting for Couchbase Server to be available
Don't override port rest_port because already available in /opt/couchbase/etc/couchbase/static_config
Don't override port memcached_port because already available in /opt/couchbase/etc/couchbase/static_config
Don't override port query_port because already available in /opt/couchbase/etc/couchbase/static_config
Don't override port ssl_rest_port because already available in /opt/couchbase/etc/couchbase/static_config
Starting Couchbase Server -- Web UI available at http://<ip>:8091
and logs available in /opt/couchbase/var/lib/couchbase/logs
Waiting for Couchbase Server to be available
Waiting for Couchbase Server to be available
Waiting for Couchbase Server to be available
Waiting for Couchbase Server to be available
Waiting for Couchbase Server to be available
Waiting for Couchbase Server to be available
Couchbase server is online
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
Waiting for cluster init
```

As you can see it is waiting for cluster init forever.

**To Reproduce**
1. Create a CouchbaseContainer with TestcontainersBuilder.
2. Call StartAsync on it.

**Expected behavior**
I expect the container to be started successfully.

**Desktop (please complete the following information):**
- macOS Catalina

**Comment by mustafaonuraydin** [comment]
Hello @dogac00 ,

This problem may be caused by insufficient memory. 
Could you please share with me your local docker resources? 

My advice is change memory as 4GB minimum.

Here is my settings;
<img width="1033" alt="docker-resources" src="https://user-images.githubusercontent.com/23043950/104641739-3865c980-56bb-11eb-950c-6253a61dabe6.png">

**Comment by HofmeisterAn** [comment]
Thanks @mustafaonuraydin for the quick reply.

> This problem may be caused by insufficient memory.

I can confirm this. We had similar issues with the Microsoft-hosted agents for Azure.

I also tested it on my locale machine. If you do not have enough memory, Couchbase won't start.
Checkout the [minimum required memory quotas](https://docs.couchbase.com/server/current/learn/buckets-memory-and-storage/memory.html) in the Couchbase documentation. I think you need at least 2GB+ in total.

**Comment by dogac00** [comment]
Thanks @mustafaonuraydin, I resolved the issue by increasing docker memory limits.
