### ISSUE TITLE
WithBindingPort on Oracle Container

### ISSUE THREAD

**Issue by dayanfcosta** [testcontainers/testcontainers-dotnet#367]
**Describe the bug**
I tried to bind the port 1521 to the Oracle container using `.WithPortBinding(1521)` but if I use this, I get an exception saying that the container wasn't built.

**To Reproduce**
Try to create an `OracleTestcontainer` with the following instructions
```
 new TestcontainersBuilder<OracleTestcontainer>()
                 .WithPortBinding(ORACLE_PORT)
                 .WithDatabase(new OracleTestcontainerConfiguration())
                 .Build();
```
And you'll get the following error:
`[Test Class Cleanup Failure (TestClass)]: System.InvalidOperationException : Testcontainer has not been created.`

**Expected behavior**
It should create the test container binding port 1521 on the host to the container's 1521 port.

**Desktop (please complete the following information):**
- Version 1.4.0

**Comment by HofmeisterAn** [comment]
Based on your sample code I guess you haven't start and await the container? You can not access certain properties without starting the container. See:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/a991d569e98286b0a506fa57b3a02d7733c263b7/src/DotNet.Testcontainers/Containers/Modules/TestcontainersContainer.cs#L16

What does the class cleanup? In addition too that, take a look into the Oracle tests:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/bcb04fbdf27fd58c7fb16e22b4f03247c079b966/src/DotNet.Testcontainers.Tests/Fixtures/Containers/Modules/Databases/OracleFixture.cs#L11

\* you don't need the port binding.

**Comment by dayanfcosta** [comment]
@HofmeisterAn port binding is important to me for use in integration tests from API calls, in the API tests the database configuration comes from the `appsettings.json` I and keeping random port were making the tests more difficult. As a workaround I did this:

```
var configuration = new OracleTestcontainerConfiguration() { Port = ORACLE_PORT };
            Container = new TestcontainersBuilder<OracleTestcontainer>()
                 .WithDatabase(configuration)
                 .Build();
```

**Comment by HofmeisterAn** [comment]
You can get the assigned port with `GetMappedPublicPort(1521)`. Assigning random ports is best practice. Anyway, does your issue still exist?

**Comment by dayanfcosta** [comment]
As I'd told you the problem was solved with the previous workaround. I think this method wouldn't help me once I needed to have it on my `appsettings.json, but I'm gonna close this question. Thanks!
