### ISSUE TITLE
Is it possible to start a container and specify a hostname ?

### ISSUE THREAD

**Issue by fgheysels** [testcontainers/testcontainers-dotnet#374]
I want to setup a test where I need to launch a container, but I also need to specify a hostname for the running container.
Like you would do:

```
docker run --hostname <myhostname>  <containerimage>
```
Is that something that is already possible ?  If so, how can it be achieved ?

**Comment by fgheysels** [comment]
I'm using Dotnet.Testcontainers 1.4.0 and I see in the readme that there exists a `WithHostname` method, but it doesn't seem to be available in my project.

![image](https://user-images.githubusercontent.com/3605786/112605303-726bee00-8e17-11eb-9f97-c932251b9839.png)

I do find the method however in the codebase here (in the develop branch), so maybe a new release is required, since it is not in the master branch yet ?

**Comment by HofmeisterAn** [comment]
Use the latest snapshot release `1.5.0-beta.20210318.4`.

- `master` → `1.4.0`.
- `develop` → `1.5.0-beta.20210318.4`.

**Comment by fgheysels** [comment]
Great, thanks!

**Comment by fgheysels** [comment]
Any idea when 1.5 will be out of beta stage @HofmeisterAn  ?

**Comment by HofmeisterAn** [comment]
I haven’t a specific date yet. I would like to add the resource reaper (Ryuk) first. I think it’s a very important feature that I would like to ship within the next version.

**Comment by HofmeisterAn** [comment]
@fgheysels FYI `1.5.0` is released.
