### ISSUE TITLE
Also target .NET Standard 2.0 to support .NET Framework

### ISSUE THREAD

**Issue by chrisbbe** [testcontainers/testcontainers-dotnet#381]
**Is your feature request related to a problem? Please describe.**
Not targeting .NET Standard 2.0 to make the package usable by .NET Framework.

**Describe the solution you'd like**
In addition to targeting .NET Standard 2.1, also target .NET Standard 2.0

**Comment by HofmeisterAn** [comment]
👍 Shouldn't be much work. We just need to remove some syntactic sugar. I can take a look at it this week.

**Comment by chrisbbe** [comment]
I have already looked into it, I can provide a PR if you want?

**Comment by HofmeisterAn** [comment]
#382.
