### ISSUE TITLE
Can't run the image with "-p 8080:80"

### ISSUE THREAD

**Issue by dmitriivasiluk** [testcontainers/testcontainers-dotnet#385]
**Describe the bug**
I'm simply trying to run the image with this arguments "-p 8080:80"

**To Reproduce**
I expect this to work with the following line of code: `.WithPortBinding(8080, 80);`

**Expected behavior**
Ports to be assigned to "0.0.0.0:8080->80/tcp", which doesn't seem to happen at the moment

**Comment by HofmeisterAn** [comment]
I'm pretty sure it works. We use it a lot in our unit tests, it's even covered here with tests:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/e4ba13f9b8e014482192838ccc0b121de8e8aa3c/src/DotNet.Testcontainers.Tests/Unit/Containers/Unix/TestcontainersContainerTest.cs#L178

What error do you get? Can you add some more code?

**Comment by dmitriivasiluk** [comment]
var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
                .WithImage(<target_image>)
                .WithPortBinding(8080, 80)
                .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(80));
                
Actually, there're no error, but no assigned ports.

**Comment by dmitriivasiluk** [comment]
![image](https://user-images.githubusercontent.com/18139024/119000225-98cf8500-b993-11eb-94ed-573f0c6ed27b.png)

**Comment by dmitriivasiluk** [comment]
@HofmeisterAn Could this be the issue around placing the argument?
docker run -p 8080:80 <target_image> - works
docker run <target_image> -p 8080:80 - does not work

**Comment by dmitriivasiluk** [comment]
Well, this is what does the trick.
```
.WithPortBinding(8080, 80)
.WithExposedPort(80)
```

Anyway, thanks for spending the time. Closing the issue.
