### ISSUE TITLE
Database random port mapping does not work

### ISSUE THREAD

**Issue by prochnowc** [testcontainers/testcontainers-dotnet#386]
**Describe the bug**

When creating a eg. Postgres database container the random port mapping does not work.

**To Reproduce**

```
  await new TestcontainersBuilder<PostgreSqlTestcontainer>()
    .WithDatabase(
    new PostgreSqlTestcontainerConfiguration
    {
      Database = "test",
      Username = "user",
      Password = "password"
     })
     .Build()
     .StartAsync();
```

exposes some random port eg. 49132, but the actual port I can see in docker is different.
If I explicitly map the port it works.

**Desktop (please complete the following information):**
- Version 3.3.3 with WSL2

**Additional context**

Dotnet.Testcontainers v1.5.0-beta.1928

**Comment by HofmeisterAn** [comment]
I'm pretty sure it's working. We use `GetMappedPublicPort` in our tests too:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/d23c60664e23844272616b41be88fdd8433ebeb4/src/DotNet.Testcontainers.Tests/Unit/Containers/Unix/Database/PostgreSqlTestcontainerTest.cs#L30

By default the configuration above assings a random port to the default PostgreSQL port (5432) e. g. `0.0.0.0:56515->5432/tcp`. To get the assigned port `56515` call `GetMappedPublicPort(5432)` or access the `Port` property.

I hope this helps. Otherwise, please add more information. I'm not sure I understood your question entirely.

**Comment by prochnowc** [comment]
When I start the container it gives me for example "Port=49200" in the ConnectionString. But the docker container was actually started with port mapping "5432->52071". And of course my test code which tries to connect receives a "Npgsql.NpgsqlException" Please see the screenshots.

![postgres_init](https://user-images.githubusercontent.com/10866701/121336064-7342f500-c91b-11eb-83e1-416b2404a48f.png)

![postgres_container](https://user-images.githubusercontent.com/10866701/121336100-7b029980-c91b-11eb-8cb1-ae04045f4a0f.png)

Note: If I manually call `.WithPortBinding(15432, 5432)` it works fine.

**Comment by HofmeisterAn** [comment]
Odd, I haven't any issues. Even if it doesn't look like it, could you double check, if

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/d23c60664e23844272616b41be88fdd8433ebeb4/src/DotNet.Testcontainers/Containers/Modules/TestcontainersContainer.cs#L125

contains more than one port associated to your private port? Somehow `GetMappedPublicPort` resolves the wrong port in your case.

**Comment by prochnowc** [comment]
No, it just contains one port mapping. I've run the tests here and they fail too.

**Comment by prochnowc** [comment]
FYI: It seems some timing issue. I've added an additional `this.container = GetContainer()` after executing the wait strategies. Now everything works fine.

**Comment by prochnowc** [comment]
Just found this one: https://github.com/dotnet/Docker.DotNet/issues/511

**Comment by HofmeisterAn** [comment]
Interessting. Thanks for the information. We can at least replace

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/d23c60664e23844272616b41be88fdd8433ebeb4/src/DotNet.Testcontainers/Containers/Modules/TestcontainersContainer.cs#L244

with

```cs
return await this.client.GetContainer(id, ct)
  .ConfigureAwait(false);
```

This would be more like the original implementation. It won't help Kafka (`StartupCallback`) a lot, but I think there are better ways to create Kafka containers than the current approach anyway.

**Comment by prochnowc** [comment]
I did some further investigation. It seems that WSL2 does remapping of dynamic ports AFTER the container was started, and this might take a while.

I've ran "docker container ls" in a loop on windows and inside WSL2 when running the tests.

Output on linux:
```
"goofy_wiles" -> "0.0.0.0:50787->5432/tcp"
```

While the output on windows initially has the same port, after some delay it has another port (and IP):

```
"goofy_wiles" -> "0.0.0.0:50787->5432/tcp"
"goofy_wiles" -> "127.0.0.1:49156->5432/tcp"
```

The strange thing is, the Docker.DotNet client returns the following ports:

After start: 49156
After executing wait strategies: 50787

**Comment by prochnowc** [comment]
After disabling minikube the strange behavior goes away.
Could you still add 

```
return await this.client.GetContainer(id, ct)
  .ConfigureAwait(false);
```
?

**Comment by HofmeisterAn** [comment]
Sounds like it's related to WSL2? I don't use it frequently. Probably that's why I never noticed it. Could you add your information to dotnet/Docker.DotNet#511 too? I think there's not much we can do.

> Could you still add

Ofc, I can add that later. However, this may not help you if the "remapping" takes too long. Maybe you need to add a custom wait strategy what waits until the "remapping" is done.

**Comment by HofmeisterAn** [comment]
@prochnowc You'll find the change in `1.5.0-beta.1929`.

**Comment by HofmeisterAn** [comment]
I'll close this issue. If you have any further issues don't hesitate to open it again. Still, it would be nice if you forward your information to the Docker.DotNet project.

**Comment by prochnowc** [comment]
Thanks @HofmeisterAn, I've added my information to the linked issue.
