### ISSUE TITLE
CopyFileAsync permission issue

### ISSUE THREAD

**Issue by sadedil** [testcontainers/testcontainers-dotnet#389]
**Describe the bug**
When I use `CopyFileAsync`, the created file has `-rw-------` permissions. But when I use `docker cp` manually, it's setting permissions to `-rwxr-xr-x`

**To Reproduce**
```csharp
var content = File.ReadAllBytes("BackupForDockerImage.bak");
await testcontainer.CopyFileAsync("/var/opt/mssql/backup/BackupForDockerImage.bak", content);
```
Then open your favorite terminal, attach the docker container, and run `ls -l` in the copied folder.
You will see `-rw------- 1 root root 403886080 Jan  1  1970 BackupForDockerImage.bak`

**Expected behavior**
`-rwxr-xr-x 1 root root 403886080 Jul 29 10:09 BackupForDockerImage.bak`

**Desktop (please complete the following information):**
- DotNet.Testcontainers version: 1.6.0-beta.1955
- .NET Version: v4.7.2

**Additional context**
Also the file date resetting to 1970 if I use `CopyFileAsync`

By the way thanks for the library, It's very useful.

**Comment by HofmeisterAn** [comment]
`CopyFileAsync` is an overloaded method. Use the `accessMode` parameter.

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Containers/IDockerContainer.cs#L125

`rwxr-xr-x` should be `493`. You need to calculate the integer value from the binary form. ~~[Here](https://www.marksanborn.net/linux/changing-permissions-with-chmod-binary-values/) is an example~~. See the example below.

**Comment by sadedil** [comment]
Hi @HofmeisterAn,

Thank you for your quick response, `493` was worked!

Before creating this issue, I've tried with `777` but interestingly `777` is still not working. By the way, I've used this site: https://chmod-calculator.com

**Comment by HofmeisterAn** [comment]
> but interestingly 777 is still not working

As I said, you need to convert the value (Chmod). The attached link I missleading - sorry.

- `777` in bit representation is `111_111_111`, thats `511` in decimal.
- `755` in bit representation is `111_101_101`, thats `493` in decimal.
- `644` in bit representation is `110_100_100`, thats `420` in decimal.
- etc.
