### ISSUE TITLE
Accessing the output of ExecAsync

### ISSUE THREAD

**Issue by fabiogouw** [testcontainers/testcontainers-dotnet#390]
**Is your feature request related to a problem? Please describe.**
I'm writing code to test an application against a database and I need to run some scripts before the test runs (create some tables, etc.). I was able to copy the script into the container (using CopyFileAsync method) and I'm trying to run it (using ExecAsync method), but I can't see the output (stdout and stderr) when running the command (to debug and see errors if they happen), only the result code.

**Describe the solution you'd like**
I'd like to have some way to see what happened during the command execution. The ExecAsync could return an object that has this information, not only the return code.
The Java version of TestContainers has the [Container.ExecResult](https://www.testcontainers.org/features/commands/) object, I guess we might have it here too.

**Describe alternatives you've considered**
I considered to run the scripts outside TestContainers, using plain ADO.NET commands, but I think it would be nice if we can do it using the framework (maybe adding some extension methods to do it in the databases modules).

**Comment by HofmeisterAn** [comment]
👍 I think we just need to pass a stream to:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Clients/DockerContainerOperations.cs#L117

Either we use the output consumer or create a scoped stream and return a dedicated object with the output result and exit code.

**Comment by fabiogouw** [comment]
Andre, I took your second suggestion and it worked, I can make a PR with this change. But before, I'd like to discuss two options with you:

1. Create a new method (for instance, _ExecWithOutputAsync_) that returns the new object (exit code + stdout + stderr), similar to the solution in the Java version of this lib
2. Alter the existing method _ExecAsync_ to return this object. This will break existing clients.

**Comment by HofmeisterAn** [comment]
Thanks. I'll take a look at it later that day.

**Comment by HofmeisterAn** [comment]
`1.6.0-beta.1966`
