### ISSUE TITLE
Kafka security protocol

### ISSUE THREAD

**Issue by KovtunV** [testcontainers/testcontainers-dotnet#391]
Hello, is it possible to configure container with one of protocols: Plaintext, Ssl, SaslPlaintext, SaslSsl? Unfortunattely, I can't find the solution to use SASL_SSL here, even creating SSL certificate (server.keystore.jks)

**Comment by HofmeisterAn** [comment]
I'm not familiar with the Kafka configuration, but you can override the default configuration and pass it to `WithKafka`:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Configurations/Modules/MessageBrokers/KafkaTestcontainerConfiguration.cs#L29

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/tests/DotNet.Testcontainers.Tests/Fixtures/Containers/Unix/Modules/MessageBrokers/KafkaFixture.cs#L12

**Comment by KovtunV** [comment]
@HofmeisterAn Yes, I configured it, but I'm wondering how to generate SSL certificate via _keytool -keystore server.keystore.jks ..._
I added this to _startupScript stringBuilder_ but it doesn't work, even mkdir can't create a directory

**Comment by HofmeisterAn** [comment]
Probably you can mount a volume that contains the keystore or copy the keystore into the container.

**Comment by KovtunV** [comment]
@HofmeisterAn Is it possible to do this before starting "zookeeper-server-start.sh"?

![image](https://user-images.githubusercontent.com/11136226/129839189-7cc972e7-b2ef-41cc-9e3a-910660d03e31.png)

Image is taken from "https://docs.vmware.com/en/VMware-Smart-Assurance/10.1.0/sa-ui-installation-config-guide-10.1.0/GUID-DF659094-60D3-4E1B-8D63-3DE3ED8B0EDF.html"

**Comment by HofmeisterAn** [comment]
> Is it possible to do this before starting "zookeeper-server-start.sh"?

Yes, override `StartupCallback`. It configures ZooKeeper too and starts it at:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/8b3860c0bb27d8f82f747fdba07870ef33a18bad/src/DotNet.Testcontainers/Configurations/Modules/MessageBrokers/KafkaTestcontainerConfiguration.cs#L71

**Comment by HofmeisterAn** [comment]
I'll close this issue because it's related to the Kafka configuration itself. Don't hesitate to reopen the issue if you have further questions related to the library.
