### ISSUE TITLE
Add pre-configured test container for MongoDB

### ISSUE THREAD

**Issue by RMariowski** [testcontainers/testcontainers-dotnet#398]
**Is your feature request related to a problem? Please describe.**  
I started working on my personal project that is using multiple different databases and I'm using `dotnet-testcontainers` for more convenient way of testing. However as there's no pre-configured test container of `MongoDB`, I decided to write it for my own purposes, but as well I can also share it.

**Describe the solution you'd like**  
I would like to see a pre-configured test container of `MongoDB` as is for other databases like Oracle, MySQL etc.

**Additional context**  
Here's link to the branch from my fork as a potential PR: [link](https://github.com/RMariowski/dotnet-testcontainers/commits/feature/mongodb)

**Comment by HofmeisterAn** [comment]
👍 I'll take a look at it next week or the week after.

**Comment by HofmeisterAn** [comment]
Your changes look good, thanks. I would prefer to provide modules in separate dependencies to support more module specific functions, but we do not have the infrastructure yet.

A PR is more than welcome! Thanks, again.

**Comment by HofmeisterAn** [comment]
#400
