### ISSUE TITLE
Helper methods for database script execution

### ISSUE THREAD

**Issue by fabiogouw** [testcontainers/testcontainers-dotnet#399]
**Is your feature request related to a problem? Please describe.**
If I need to run scripts to prepare the database before running tests against it, then I must code all the steps:
- by using the database API to execute the script
- or by copying the file inside the container and executing the command line tool (sqlcmd, mysql, ...)

**Describe the solution you'd like**
A good way to make my test code smaller is creating a helper method in the database modules:

```csharp
var results = await dbTestContainer.ExecScript("CREATE DATABASE xzy; ...");
```

This `ExecScript` method can encapsulate the task of creating the script file, copying it inside the container and running the command line tool to execute it.

**Comment by HofmeisterAn** [comment]
> to prepare the database before running tests

Shouldn't that be part of the Docker image?

> This ExecScript method can encapsulate the task of creating the script file, copying it inside the container and running the command line tool to execute it.

Sounds good as long as it covers Windows containers (PowerShell scripts, etc.) too.

**Comment by fabiogouw** [comment]
> Shouldn't that be part of the Docker image?]

This is an approach, but I'm looking for scenarios where it's easier to prepare the content of the container instead building a new image for each test case. Let's say we're building a data access component and we want to validate the behavior when the component uses an invalid user, user with wrong permissions, access a table that doesn't exists in the MySQL database. Instead of having an image for each case, it's easier to run a script to give wrong permissions to the user before the test.

> Sounds good as long as it covers Windows containers (PowerShell scripts, etc.) too.

Hm, I was thinking in having this feature only for specific databases modules (at least for now), not for generic images: running SQL scripts against MS SQL, MySQL, Oracle, Postgre; Lua scripts for Redis; N1QL for Couchbase. I've created a pull request #401 so we can easily discuss about this feature

**Comment by HofmeisterAn** [comment]
> Hm, I was thinking in having this feature only for specific databases modules (at least for now), not for generic images: running SQL scripts against MS SQL, MySQL, Oracle, Postgre; Lua scripts for Redis; N1QL for Couchbase. I've created a pull request #401 so we can easily discuss about this feature

Ah I see. I was thinking about a "more" generic implementation like `IDockerContainer.ExecAsync`. Where you pass the content of the script and the executable to the function.

**Comment by HofmeisterAn** [comment]
#401
