### ISSUE TITLE
MsSqlTestcontainer with azure-sql-edge image does not start on ARM64 (Mac M1)

### ISSUE THREAD

**Issue by cagrin** [testcontainers/testcontainers-dotnet#404]
I've tried ```MsSqlTestcontainer``` with ```mcr.microsoft.com/azure-sql-edge``` but it won't start.

```cs
var testcontainersBuilder = new TestcontainersBuilder<MsSqlTestcontainer>()
    .WithDatabase(new MsSqlTestcontainerConfiguration()
    {
        Password = "StrongP@ssw0rd!"
    })
    .WithImage("mcr.microsoft.com/azure-sql-edge");

var testcontainer = testcontainersBuilder.Build();
testcontainer.StartAsync().Wait();
```
I've figured it out that the reason of that behavior is because ```sqlcmd tool is not available inside the ARM64 version of SQL Edge containers``` according to docker image description (https://hub.docker.com/_/microsoft-azure-sql-edge). But ```sqlcmd``` is necessary to verify that the container has started (see file: ```MsSqlTestcontainerConfiguration.cs```):
```cs
public override IWaitForContainerOS WaitStrategy => Wait.ForUnixContainer()
    .UntilCommandIsCompleted($"/opt/mssql-tools/bin/sqlcmd -S 'localhost,{this.DefaultPort}' -U '{this.Username}' -P '{this.Password}'");
```

#### Questions:
1a) Should it be treated as an error of handling ARM64 image?
or maybe
1b) Should it be treated as a different Testcontainer, something like ```AzureSqlEdgeTestcontainer```?
2) What other alternative of ```WayStrategy``` can be used in this particular case? 

Currently it is the only docker image that runs on M1 macs from the hole MS SQL Server family. Please help.

**Comment by HofmeisterAn** [comment]
>1a) Should it be treated as an error of handling ARM64 image?

Well, it sounds like a different image.  Sorry - I don't know anything about `mcr.microsoft.com/azure-sql-edge`.

> 1b) Should it be treated as a different Testcontainer, something like AzureSqlEdgeTestcontainer?

I guess, yes. You can create your own configuration for `mcr.microsoft.com/azure-sql-edge` and provide a wait strategy for that image.

> 2) What other alternative of WayStrategy can be used in this particular case?

That depends on your use case. You can use whatever identifies that the Docker container is ready.

**Comment by HofmeisterAn** [comment]
>1a) Should it be treated as an error of handling ARM64 image?

Well, it sounds like a different image.  Sorry - I don't know anything about `mcr.microsoft.com/azure-sql-edge`.

> 1b) Should it be treated as a different Testcontainer, something like AzureSqlEdgeTestcontainer?

I guess, yes. You can create your own configuration for `mcr.microsoft.com/azure-sql-edge` and provide a wait strategy for that image.

> 2) What other alternative of WayStrategy can be used in this particular case?

That depends on your use case. You can use whatever identifies that the Docker container is ready.

**Comment by cagrin** [comment]
OK, I've been able to successfully start Azure SQL Edge testcontainer on M1 Mac with some ```UntilMessageIsLogged``` as a ```WaitStrategy```. Unfortunately it feels too tricky to consider this as "the solution", but it is "ok" for now.

```cs
const string started = "Recovery is complete. This is an informational message only. No user action is required.";
using var stdout = new MemoryStream();
using var stderr = new MemoryStream();
using var consumer = Consume.RedirectStdoutAndStderrToStream(stdout, stderr);

var testcontainersBuilder = new TestcontainersBuilder<MsSqlTestcontainer>()
    .WithDatabase(new MsSqlTestcontainerConfiguration()
    {
        Password = "StrongP@ssw0rd!"
    })
    .WithImage("mcr.microsoft.com/azure-sql-edge")
    .WithOutputConsumer(consumer)
    .WithWaitStrategy(Wait.ForUnixContainer().UntilMessageIsLogged(consumer.Stdout, started));

testcontainer = testcontainersBuilder.Build();
testcontainer.StartAsync().Wait();
```

If I'll come up with better solution, definitely I'll share it here.

**Comment by HofmeisterAn** [comment]
It depends on the Docker image, but parsing the output isn't uncommon.

**Comment by HofmeisterAn** [comment]
I'll close the issue. Don't hesitate to reopen the issue if you need further information or help.

**Comment by Trinition** [comment]
@cagrin I'm new to TestContainers, and I'm now running into this as well.  I appreciate you sharing a custom solution.  I'm using Groovy/Grails, so I'm going to try to figure out how to do the same thing on that platform.

**Comment by HofmeisterAn** [comment]
@Trinition Even your question does not relate to the original one. I guess you're at the wrong repository. If you're using Java, [testcontainers-java](https://github.com/testcontainers/testcontainers-java) should be the right one. This is for .NET languages.

**Comment by cagrin** [comment]
BTW, I was able to make custom Azure SQL Edge image, that contains simple `sqlcmd` tool on ARM64. See my repo for more details: https://github.com/cagrin/azure-sql-edge-arm64

With `cagrin/azure-sql-edge-arm64` image it is now possible to simple use `MsSqlTestcontainer` on ARM64 (M1 Mac).

``` c#
var testcontainersBuilder = new TestcontainersBuilder<MsSqlTestcontainer>()
    .WithDatabase(new MsSqlTestcontainerConfiguration()
    {
        Password = "StrongP@ssw0rd!"
    })
    .WithImage("cagrin/azure-sql-edge-arm64");
```

**Comment by Trinition** [comment]
@HofmeisterAn you are right.  That's how new I was!  I did manage to add a little custom code to get Azure SQL Edge working with `testcontainers-java`, but the whole container-wait mechanism is different there, so it's a different solution that what's presented here.

**Comment by gmelekh** [comment]
@Trinition 
@cagrin 
Hello..
could you please elaborate how did you configure your connection to testcontainer ?
I mean:

spring.datasource.url=jdbc:tc:**sqlserver**:///TestDBSchema 
OR
spring.datasource.url=jdbc:tc:**azuresqledgeOrWhatEverSomethingCustom**:///TestDBSchema 

Because as I know native support for azure-sql-edge is currently not available ?
