### ISSUE TITLE
[Feature Request] Report whether docker image exists locally

### ISSUE THREAD

**Issue by lonix1** [testcontainers/testcontainers-dotnet#408]
**Is your feature request related to a problem? Please describe.**
When running `container.StartAsync()` for the first time, it needs to pull the image. This could take time, especially for large images, and on slow networks.

This happens during a test run, and because it's not obvious that it's happening, the assumption is often that something is "stuck" / buggy / whatever. So a <kbd>ctrl+c</kbd> is used, then a reattempt, then again, and so on, until one remembers that maybe a docker image is being pulled in the background! :-)

**Describe the solution you'd like**
It would be nice to be able to log to the test console that the image is being pulled.

To do that though, the `PostgreSqlTestcontainer` (or whatever) needs to have a property/method that tells me if the "image exists". For example: `container.ImageExists`. Then I could do this:

````cs
var exists = container.ImageExists;
if (!exists) _logger.Log("About to pull image.");
await container.StartAsync();
if (!exists) _logger.Log("Image pulled (and container started).");
````

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by HofmeisterAn** [comment]
If you provide and setup the logging implementation for `Microsoft.Extensions.Logging.ILogger` you will already get the information. It looks like this:

```
2021-11-24 13:55:51.875 +01:00 [VRB] DotNet.Testcontainers.Tests.Initialized Docker.DotNet.Models.JSONMessage
2021-11-24 13:55:51.875 +01:00 [VRB] DotNet.Testcontainers.Tests.Initialized Docker.DotNet.Models.JSONMessage
2021-11-24 13:55:51.911 +01:00 [VRB] DotNet.Testcontainers.Tests.Initialized Docker.DotNet.Models.JSONMessage
2021-11-24 13:55:51.919 +01:00 [VRB] DotNet.Testcontainers.Tests.Initialized Docker.DotNet.Models.JSONMessage
2021-11-24 13:55:51.922 +01:00 [VRB] DotNet.Testcontainers.Tests.Initialized Docker.DotNet.Models.JSONMessage
2021-11-24 13:55:51.924 +01:00 [INF] DotNet.Testcontainers.Tests.Initialized Image "postgres:11.5" created
```

The last line shows that the image has been pulled successfully (log level information). The lines above are printed while the image is pulled (log level verbose). See [Initialization:L13](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/0b37e212871e81f3af808ee0d48fe4cdbf3f5340/tests/DotNet.Testcontainers.Tests/Initialization.cs#L13) and the corresponding log [output:L113](https://dev.azure.com/HofmeisterAn/GitHub-Testcontainers/_build/results?buildId=2028&view=logs&j=2e4c57fa-087c-5e0a-b0d9-a942b3c0c993&t=06a1d7ff-cd0c-513e-a823-a42a9f55e68d&l=113).

**Comment by lonix1** [comment]
I don't have my integration tests setup that way, so it did not meet my needs, and I used a workaround instead. If anyone needs it what I did was this:
- use `Docker.DotNet` library to determine if image exists
- if not, log "pull begin"
- pull/start image: `await container.StartAsync()`
- log "pull end"

Enjoying this library, thanks for making it!
