### ISSUE TITLE
Endpoint configuration

### ISSUE THREAD

**Issue by DanWillman** [testcontainers/testcontainers-dotnet#414]
**Is your feature request related to a problem? Please describe.**
Currently the library only supports docker running at hard-coded locations, `/var/run/docker.sock` for example, but will not support docker replacements such as podman. Many organizations are currently evaluating the value of docker desktop with the change to a paid model, and we are currently looking to switch to podman for our windows/MacOS environments, but this breaks testcontainers for us. 

**Describe the solution you'd like**
Expose the API endpoint configuration to consumers

**Describe alternatives you've considered**
One of the alternatives we've explored would require each developer to expose the port through WSL on the docker desktop windows named pipe, which is less than ideal.

**Comment by HofmeisterAn** [comment]
I'm not quite sure if I got it right, but we expose two ways to configure the Docker API endpoint either with `WithDockerEndpoint`: https://github.com/HofmeisterAn/dotnet-testcontainers/blob/feebebcf7d9effe5ba5ee4050dc5161a7d5551dc/src/DotNet.Testcontainers/Builders/ITestcontainersBuilder.cs#L265

or global with `TestcontainersSettings.OS.DockerApiEndpoint`

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/feebebcf7d9effe5ba5ee4050dc5161a7d5551dc/src/DotNet.Testcontainers/Configurations/TestcontainersSettings.cs#L24

Does that help?

**Comment by DanWillman** [comment]
Oh whoops, I missed WithDockerEndpoint overriding the API endpoint, thanks for that. I'm still hitting socket exceptions with this, but it's definitely on the right track. I'll close this for now, thanks for the help!
