### ISSUE TITLE
Expose TestcontainersContainer client

### ISSUE THREAD

**Issue by eaba** [testcontainers/testcontainers-dotnet#416]
Please can you expose the `client` in `TestcontainersContainer`?

I need to extend the `TestcontainersContainer` to add copying files from the container and I want to re-use the `client` instead of creating a different `client`.

[Edit]: How can we re-use the dockerclient in out extension method?

Please!!!

**Comment by HofmeisterAn** [comment]
> to add copying files from the container

Can you explain a bit more? Do you want to copy files from a running container to your host (aka [GetArchiveFromContainerAsync](https://github.com/dotnet/Docker.DotNet/blob/f58748616cc5b679b25496926c5688294c94d850/src/Docker.DotNet/Endpoints/IContainerOperations.cs#L366))?

**Comment by eaba** [comment]
> > to add copying files from the container
> 
> Can you explain a bit more? Do you want to copy files from a running container to your host (aka [GetArchiveFromContainerAsync](https://github.com/dotnet/Docker.DotNet/blob/f58748616cc5b679b25496926c5688294c94d850/src/Docker.DotNet/Endpoints/IContainerOperations.cs#L366))?

Yes `GetArchiveFromContainerAsync`. So since that is not yet possible, I decided to creation an extension for it!

**Comment by HofmeisterAn** [comment]
Can you contribute and create a pull request?

**Comment by eaba** [comment]
Ok

**Comment by HofmeisterAn** [comment]
I don't know the parameters, but maybe something like `ReadFileAsync` would be nice. If you have any other ideas, I'm happy to discuses them. Thanks in advance.

**Comment by eaba** [comment]
@HofmeisterAn I have sent in a quick PR, please can you take it up from there? #418

Can it be available by this week's end?

**Comment by eaba** [comment]
@HofmeisterAn How can we also set the container resource? I can find the Resource model here https://github.com/dotnet/Docker.DotNet/blob/c71df18a0f76f30160f61f908353ad1e53677377/src/Docker.DotNet/Models/Resources.Generated.cs#L1-L102 but I did not see how to use it. 

I know this is outside the scope of this issue.

**Comment by HofmeisterAn** [comment]
> How can we also set the container resource? I can find the Resource model here

This is not supported right now. I think `Resources` gets passed to `HostConfig`. Java offers to customize the configuration like [this](https://www.testcontainers.org/features/advanced_options/#customizing-the-container). I haven't thought about it yet, we probably need a proper concept first.

**Comment by HofmeisterAn** [comment]
I'll close this in favor of #430.
