### ISSUE TITLE
Pre-configured Postgres example in README does not work

### ISSUE THREAD

**Issue by Sibusten** [testcontainers/testcontainers-dotnet#425]
**Describe the bug**
The pre-configured Postgres example in the README throws a `MemberAccessException` when building the container.

**To Reproduce**
Copy the following container creation code from the README and run it:
```cs
TestcontainerDatabase testcontainers = new TestcontainersBuilder<TestcontainerDatabase>()
    .WithDatabase(new PostgreSqlTestcontainerConfiguration())
    .Build();
```

**Expected behavior**
The pre-configured example in the README should function correctly.

**Desktop (please complete the following information):**
- Version 1.5.0

**Additional context**
I got it working by following the setup in [PostgreSqlFixture](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/develop/tests/DotNet.Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/PostgreSqlFixture.cs). This required:
1. Changing the generic type to `PostgreSqlTestcontainer`
2. Passing `Database`, `Username`, and `Password` to `PostgreSqlTestcontainerConfiguration`

The following works correctly:
```cs
TestcontainerDatabase testcontainers = new TestcontainersBuilder<PostgreSqlTestcontainer>()
    .WithDatabase(new PostgreSqlTestcontainerConfiguration { Database = "db", Username = "postgres", Password = "postgres" })
    .Build();
```

**Comment by HofmeisterAn** [comment]
Thanks - you're absolutely right. A pull request is welcome, otherwise I can do it tomorrow. Even the field name is wrong 😬

```cs
public sealed class PostgreSqlTest : IAsyncLifetime
{
  private readonly TestcontainerDatabase testcontainers = new TestcontainersBuilder<PostgreSqlTestcontainer>()
    .WithDatabase(new PostgreSqlTestcontainerConfiguration
    {
      Database = "db",
      Username = "postgres",
      Password = "postgres",
    })
    .Build();

  [Fact]
  public void ExecuteCommand()
  {
    using (var connection = new NpgsqlConnection(this.testcontainers.ConnectionString))
    {
      using (var command = new NpgsqlCommand())
      {
        connection.Open();
        command.Connection = connection;
        command.CommandText = "SELECT 1";
        command.ExecuteReader();
      }
    }
  }

  public Task InitializeAsync()
  {
    return this.testcontainers.StartAsync();
  }

  public Task DisposeAsync()
  {
    return this.testcontainers.DisposeAsync().AsTask();
  }
}
```

**Comment by HofmeisterAn** [comment]
Thanks for the information again. It's fixed.
