### ISSUE TITLE
InvalidOperationException `cannot hijack chunked ... stream` (Rancher Desktop, Docker Desktop 4.10.0)

### ISSUE THREAD

**Issue by wesley-pattison** [testcontainers/testcontainers-dotnet#431]
**Describe the bug**
Please see this bug reported by someone else in Docker DotNet:
https://github.com/dotnet/Docker.DotNet/issues/554

My own response to this:
https://github.com/dotnet/Docker.DotNet/issues/554#issuecomment-1064806276

**To Reproduce**
1. Use Rancher Desktop with WSL2 enabled and dockerd (moby)
2. Run unit tests in dotnet-testcontainers solution (I am only focused on RabbitMq myself)
3. Exception thrown

**Expected behavior**
Unit test passes

**Desktop (please complete the following information):**
- Rancher Desktop (Windows install) v1.1.1
- Windows 10 with WSL2 Ubuntu

**Workaround**
- Use snapshot release `2.1.0-beta.2698157448`
- Downgrade to Docker Desktop `4.9.x`

**Comment by piotrke** [comment]
any update on this? I'd really like to use this library but it's not possible with Rancher Desktop

**Comment by HofmeisterAn** [comment]
With the latest changes (in the `develop`) you might be able to use Testcontainers. As long as you don't need access to the I/O streams. I did some minor improvements, but I still need to look into the underlying issue. There is no snapshot release yet, but you can, checkout the repository in the meantime.

**Comment by joebone** [comment]
So I tried the latest changes in Develop, to no avail, however I *have* made a local hack that at least allows this to work..
https://github.com/dotnet/Docker.DotNet/issues/554#issuecomment-1164473429
At the same time i had to manually replace the "localhost" in the generated connectionstring with "127.0.0.1" in order to connect properly, so in the end my factory method is something like this:

```cs
 static Func<Task<IDbConnection>> GetDockerizedDb = async () =>
 {
     var pw = "tmpTest(!)Password123";
     var dbConfig = new MsSqlTestcontainerConfiguration("mcr.microsoft.com/mssql/server:2019-latest");
     dbConfig.Password = pw;
     var testcontainersBuilder = new TestcontainersBuilder<MsSqlTestcontainer>().WithDatabase(dbConfig);
     var containers = testcontainersBuilder.Build();
     await containers.StartAsync();
     var conn = new SqlConnection(containers.ConnectionString.Replace("localhost,", "127.0.0.1,"));
     await conn.OpenAsync();
     await conn.ExecuteAsync(File.ReadAllText("SharedTests/sundb.setup.sql"));
     return conn;
 };
```

**Comment by joebone** [comment]
Update: I have an open PR to that repo that adds an option to the configuration that will allow this project to specify the http version 
https://github.com/dotnet/Docker.DotNet/pull/566
Being a first time contributor, I have no idea how long that process will take or even if they will accept the change, but I have applied the changes to a local version and "everything works on my machine", as we say. I don't know what your feelings are on taking dependencies on prerelease versions, but at least if this is a stopper that is a workaround...

**Comment by joebone** [comment]
@HofmeisterAn Could we have a discussion about how you would best like to integrate the changes required in this library? I had hoped to make as non-intrusive a change as possible for backwards compatibility but I've gone down a rabbit hole of changes in order to include it in the configuration, and the issue is that the instance of the dockerclient that is used is currently pulled in by calling a new DotNet.Testcontainers.Configurations.Windows
which eventually winds up in NpipeEndpointAuthenticationProvider.GetAuthConfig()

Basically the client is instantiated in DockerEndpointAuthenticationConfiguration in the method, and the HttpVersion (configured by the user, or the context detecting that rancher desktop is being run ) would be have to be configured there, but because its internal, the end user has no access / control over that..
```c#
public DockerClientConfiguration GetDockerClientConfiguration()
{
  return new DockerClientConfiguration(this.Endpoint) { HttpVersion = this.HttpVersion };
}
```

Initially I just wanted to add a public Version HttpVersion { get; } to that DockerEndpointAuthenticationConfiguration , but as it is all called internally by the TestcontainersContainer constructor via the TestcontainersClient, the changes I was making were starting to sprawl. 

How would be your preferred way of solving this issue? Autodetect the runtime / api that is running? Some kind of extension method like the following?
```c#
       dbConfig.Password = pw;
       var testcontainersBuilder = new TestcontainersBuilder<MsSqlTestcontainer>()
           .WithHttpVersion(new(1, 0))
           .WithDatabase(dbConfig);
```
Just need some guidance here so I don't waste a whole bunch of everybody's time..

**Comment by HofmeisterAn** [comment]
I know this is an important issue for anyone that can't use Docker. I haven't had enough time to take a close look into the issue yet, but I prepared a test environment and read the `Docker.DotNet` sources. Just give me some more time, to get a better understanding of the underlying issue.

I don't think, changing the HTTP version to `1.0` is the right approach. If you look into the Docker Engine API documentation, you'll see that [ContainerAttach](https://docs.docker.com/engine/api/v1.41/#operation/ContainerAttach) returns `1.1` for instance. I would assume it (should) supports chunked transfer encoding:
> it allows streaming of content as chunks and explicitly signaling the end of the content

**Comment by joebone** [comment]
I'm glad I asked! =) Thanks for the update, I guess meanwhile we'll internally use this workaround, but I look forward to hearing your thoughts on how you'd like to solve this issue when you find the time. Obviously, whatever help I can give is yours. Great project btw!

**Comment by jplumhoff** [comment]
Since this issue specifically mentions Rancher, I'm not sure if this is the place to mention this or not.  But immediately after upgrading to Docker Desktop 4.10, I started seeing the same "cannot hijack chunked or content length stream" exception.  I uninstalled 4.10, reinstalled 4.9, and everything works again.

**Comment by HofmeisterAn** [comment]
I can confirm. It's broken for Docker Desktop for Windows (4.10.0) too. We need a fix in https://github.com/dotnet/Docker.DotNet/issues/554.

**Comment by databrecht** [comment]
Same on Docker Desktop for Mac (4.10.0) it seems, downgrading to 4.9.1 makes the error go away. 

```
System.AggregateException : One or more errors occurred. (cannot hijack chunked or content length stream) (cannot hijack chunked or content length stream)
---- System.InvalidOperationException : cannot hijack chunked or content length stream
---- System.InvalidOperationException : cannot hijack chunked or content length stream
 Stack Trace:
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
  at [Microsoft.Net](http://microsoft.net/).Http.Client.HttpConnectionResponseContent.HijackStream()
  at Docker.DotNet.DockerClient.MakeRequestForHijackedStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken cancellationToken)
  at Docker.DotNet.ContainerOperations.AttachContainerAsync(String id, Boolean tty, ContainerAttachParameters parameters, CancellationToken cancellationToken)
  at DotNet.Testcontainers.Clients.DockerContainerOperations.AttachAsync(String id, IOutputConsumer outputConsumer, CancellationToken ct)
  at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.Start(String id, CancellationToken ct)
  at DotNet.Testcontainers.Containers.Modules.TestcontainersContainer.StartAsync(CancellationToken ct)```

**Comment by xFrankTheDevx** [comment]
Hello everyone. I'd like to add that the same error is occurring for Docker Desktop 4.10.0 for Windows. I did the same as databrecht in the comment above and it made the error go away.

**Comment by PatrickGhosn** [comment]
Getting this bug as well after updating to 4.10.

**Comment by HofmeisterAn** [comment]
Quick update because I know a couple of devs waiting for a fix. We’re trying to contact the maintainers. If that somehow won’t work we'll fork and fix it.

**Comment by Jejuni** [comment]
Getting this bug as well.

We're using TestContainers quite heavily for integration testing.
Luckily we didn't update docker on our Build Server, but none of our developers can run integration tests on their machines anymore.

Hoping for a quick fix.

**Comment by HofmeisterAn** [comment]
@Jejuni Your devs can downgrade to 4.9.1. The patch I'm suggesting works fine on my environment. I just need to get it to the upstream. I'll think about how we could mange this with a fork in the meantime.

**Comment by HofmeisterAn** [comment]
I've emailed the @dotnet-foundation and asked if they can help us, or if I can get access to the repository. I prefer a fix in the upstream. A fork should be the last option.

**Comment by SeanKilleen** [comment]
@HofmeisterAn just coming across this. I also reached out to the .NET Foundation Maintainers committee on the Discord & Slack to see if pinging there might help move it along.

In a way, I'm relieved -- was testing Testcontainers for the first time (LOVE the idea!) and thought I'd done something wrong 😅

**Comment by HofmeisterAn** [comment]
@SeanKilleen Thanks, for reaching out too. I hope we find a way to fix the upstream soon. Especially, because I have a patch and it's a bad first impression using the latest Docker Desktop version.

**Comment by SeanKilleen** [comment]
@HofmeisterAn another thought -- many of us, including me, now pay for Docker Pro. Since this changed as of 4.10, perhaps we can open a support request / issue and see if docker has any flexibility on their end? I know it doesn't seem to be a "breaking change" in the classical sense, but given the impact, maybe they'd consider options.

**Comment by SeanKilleen** [comment]
Just to update the group here -- the maintainer responded and `Docker.Dotnet` has a new release that includes @HofmeisterAn's fix.

So I think as soon as we get a new release of testcontainers-dotnet with the updated `Docker.Dotnet` dependency, we should be good.

**Comment by HofmeisterAn** [comment]
I've deployed a snapshot version `2.1.0-beta.2698157448`. Can anyone test it? Feedback would be appreciated.

**Comment by kron0s19** [comment]
I just updated to `2.1.0-beta.2698157448`, and I can confirm that it is working now.

Great job (Y)

I'm running Windows `Docker Desktop 4.10.1 (82475)`

**Comment by piotrke** [comment]
works like a charm. 
I'm running Rancher 1.4.1 on Windows

**Comment by SeanKilleen** [comment]
Worked for me too! 🎉

**Comment by Xitric** [comment]
We can also confirm that `2.1.0-beta.2698157448` has fixed our integration tests that use testcontainers.

Thank you for the great work, and great to see the amount of support and activity around this project!

**Comment by wesley-pattison** [comment]
I can also confirm that using `2.1.0-beta.2698157448` has resolved the issue, and integration tests are succeeding.

Thanks all!

**Comment by HofmeisterAn** [comment]
Awesome 🥳 I'll publish a release version later that day. Thanks for your response.

**Comment by macalbert** [comment]
The version `2.1.0-beta.2698157448` fix the problem! 😄 

Tried out using docker desktop version `4.9.1` and `4.10.1`.

Thank you!!

**Comment by rossmasday** [comment]
I can confirm that using 2.1.0-beta.2698157448 works on Mac OSX Arm64 and on windows with Rancher desktop 1.4.1

**Comment by accesable** [comment]
Hi I just follow the tutorial from this [URL](https://testcontainers.com/guides/getting-started-with-testcontainers-for-dotnet/) and try out and I meet this problem again, I also tried to downgrade to docker desktop version `4.10.1` but didn't work out.
- I'm using .NET 9
- On MacOS with Apple Silicon
```
Restore complete (0.2s)
  CustomerService succeeded (0.1s) → CustomerService/bin/Debug/net9.0/CustomerService.dll
  CustomerService.Tests succeeded (0.9s) → CustomerService.Tests/bin/Debug/net9.0/CustomerService.Tests.dll
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.8.2+699d445a1a (64-bit .NET 9.0.8)
[xUnit.net 00:00:00.02]   Discovering: CustomerService.Tests
[xUnit.net 00:00:00.03]   Discovered:  CustomerService.Tests
[xUnit.net 00:00:00.04]   Starting:    CustomerService.Tests
[testcontainers.org 00:00:00.07] Connected to Docker:
  Host: tcp://127.0.0.1:49358/
  Server Version: 28.4.0 (via Testcontainers Desktop 1.22.0)
  Kernel Version: 6.10.14-linuxkit
  API Version: 1.51
  Operating System: Docker Desktop
  Total Memory: 7.65 GB
  Labels: 
    com.docker.desktop.address=unix:///Users/***/Library/Containers/com.docker.docker/Data/docker-cli.sock
[testcontainers.org 00:00:00.18] Docker container 55a78f5a9b5c created
[testcontainers.org 00:00:00.21] Start Docker container 55a78f5a9b5c
[testcontainers.org 00:00:00.34] Wait for Docker container 55a78f5a9b5c to complete readiness checks
[testcontainers.org 00:00:00.35] Docker container 55a78f5a9b5c ready
[testcontainers.org 00:00:00.37] Searching Docker registry credential in CredsStore
[testcontainers.org 00:00:00.37] Searching Docker registry credential in CredHelpers
[testcontainers.org 00:00:00.37] Searching Docker registry credential in Auths
[testcontainers.org 00:00:00.37] Searching Docker registry credential in Auths
[testcontainers.org 00:00:00.51] Docker registry credential https://index.docker.io/v1/ found
[testcontainers.org 00:00:10.60] Docker image postgres:15.1 created
[testcontainers.org 00:00:10.87] Docker container 5ea9350b0281 created
[testcontainers.org 00:00:10.88] Start Docker container 5ea9350b0281
[testcontainers.org 00:00:10.99] Wait for Docker container 5ea9350b0281 to complete readiness checks
[testcontainers.org 00:00:11.00] Execute "pg_isready --host localhost --dbname postgres --username postgres" at Docker container 5ea9350b0281
[xUnit.net 00:00:11.13]     CustomerService.Tests.CustomerServiceTest.ShouldReturnTwoCustomers [FAIL]
[xUnit.net 00:00:11.13]       System.InvalidOperationException : cannot hijack chunked or content length stream
[xUnit.net 00:00:11.13]       Stack Trace:
[xUnit.net 00:00:11.13]         /_/src/Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectionResponseContent.cs(37,0): at Microsoft.Net.Http.Client.HttpConnectionResponseContent.HijackStream()
[xUnit.net 00:00:11.13]         /_/src/Docker.DotNet/DockerClient.cs(400,0): at Docker.DotNet.DockerClient.MakeRequestForHijackedStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken cancellationToken)
[xUnit.net 00:00:11.13]         /_/src/Docker.DotNet/Endpoints/ExecOperations.cs(58,0): at Docker.DotNet.ExecOperations.StartContainerExecAsync(String id, ContainerExecStartParameters parameters, CancellationToken cancellationToken)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Clients/DockerContainerOperations.cs(165,0): at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs(152,0): at Testcontainers.PostgreSql.PostgreSqlBuilder.WaitUntil.UntilAsync(IContainer container)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Containers/DockerContainer.cs(677,0): at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(WaitStrategy waitStrategy, CancellationToken ct)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs(184,0): at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass24_0.<<WaitUntilAsync>g__UntilAsync|0>d.MoveNext()
[xUnit.net 00:00:11.13]         --- End of stack trace from previous location ---
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs(213,0): at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntilAsync(Func`1 wait, TimeSpan interval, TimeSpan timeout, Int32 retries, CancellationToken ct)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Containers/DockerContainer.cs(695,0): at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(IEnumerable`1 waitStrategies, CancellationToken ct)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Containers/DockerContainer.cs(557,0): at DotNet.Testcontainers.Containers.DockerContainer.UnsafeStartAsync(CancellationToken ct)
[xUnit.net 00:00:11.13]         /_/src/Testcontainers/Containers/DockerContainer.cs(340,0): at DotNet.Testcontainers.Containers.DockerContainer.StartAsync(CancellationToken ct)
[xUnit.net 00:00:11.13]   Finished:    CustomerService.Tests
  CustomerService.Tests test failed with 1 error(s) (11.5s)
    /_/src/Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectionResponseContent.cs(37): error TESTERROR: 
      CustomerService.Tests.CustomerServiceTest.ShouldReturnTwoCustomers (1ms): Error Message: System.InvalidOperationException : cannot hijack ch
      unked or content length stream
      Stack Trace:
         at Microsoft.Net.Http.Client.HttpConnectionResponseContent.HijackStream() in /_/src/Docker.DotNet/Microsoft.Net.Http.Client/HttpConnectio
      nResponseContent.cs:line 37
         at Docker.DotNet.DockerClient.MakeRequestForHijackedStreamAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString
       queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken cancellationToken) in /_/src/Docker.DotNet/Do
      ckerClient.cs:line 400
         at Docker.DotNet.ExecOperations.StartContainerExecAsync(String id, ContainerExecStartParameters parameters, CancellationToken cancellatio
      nToken) in /_/src/Docker.DotNet/Endpoints/ExecOperations.cs:line 58
         at DotNet.Testcontainers.Clients.DockerContainerOperations.ExecAsync(String id, IList`1 command, CancellationToken ct) in /_/src/Testcont
      ainers/Clients/DockerContainerOperations.cs:line 165
         at Testcontainers.PostgreSql.PostgreSqlBuilder.WaitUntil.UntilAsync(IContainer container) in /_/src/Testcontainers.PostgreSql/PostgreSqlB
      uilder.cs:line 152
         at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(WaitStrategy waitStrategy, CancellationToken ct) in /_/src/Testco
      ntainers/Containers/DockerContainer.cs:line 677
         at DotNet.Testcontainers.Configurations.WaitStrategy.<>c__DisplayClass24_0.<<WaitUntilAsync>g__UntilAsync|0>d.MoveNext() in /_/src/Testco
      ntainers/Configurations/WaitStrategies/WaitStrategy.cs:line 184
      --- End of stack trace from previous location ---
         at DotNet.Testcontainers.Configurations.WaitStrategy.WaitUntilAsync(Func`1 wait, TimeSpan interval, TimeSpan timeout, Int32 retries, Canc
      ellationToken ct) in /_/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs:line 213
         at DotNet.Testcontainers.Containers.DockerContainer.CheckReadinessAsync(IEnumerable`1 waitStrategies, CancellationToken ct) in /_/src/Tes
      tcontainers/Containers/DockerContainer.cs:line 695
         at DotNet.Testcontainers.Containers.DockerContainer.UnsafeStartAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerCont
      ainer.cs:line 557
         at DotNet.Testcontainers.Containers.DockerContainer.StartAsync(CancellationToken ct) in /_/src/Testcontainers/Containers/DockerContainer.
      cs:line 340

Test summary: total: 1, failed: 1, succeeded: 0, skipped: 0, duration: 11.5s
Build failed with 1 error(s) in 12.8s
```

**Comment by HofmeisterAn** [comment]
@accesable This is a known issue with Testcontainers Desktop: https://github.com/testcontainers/Docker.DotNet/issues/34.

Your log says:

> Server Version: 28.4.0 (via Testcontainers Desktop 1.22.0)

Can you please try the latest Docker Desktop and Testcontainers for .NET version?

**Comment by accesable** [comment]
I try the latest version of Docker Desktop and shutdown the Testcontainers Desktop app as well, and it worked thanks for the issue reference. I think the problem was the Testcontainers Desktop app itself
