### ISSUE TITLE
DotNet.Testcontainers.Containers.ResourceReaperException on linux machine

### ISSUE THREAD

**Issue by zaidov012** [testcontainers/testcontainers-dotnet#441]
**DotNet.Testcontainers.Containers.ResourceReaperException on linux machine**

Noticed that beta 1.6 versions on the Linux machine throw such errors and cannot start containers.

```
at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
   at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(CancellationToken ct)
   at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
   at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
```

**In version 1.5.0" where ryuk is not used, there are no problems and everything works fine**

**Screenshots**
This is how kafka container created
```
        public KafkaContainer()
        {
            _hostName = "localhost";
            _hostPort = this.getFreePort();


            var configuration = new KafkaTestcontainerConfiguration();
            configuration.Environments.Add("KAFKA_AUTO_CREATE_TOPICS_ENABLE", "true");

            //NOTE: topic_name:partition:replica
            configuration.Environments.Add("KAFKA_CREATE_TOPICS", "loan-events-topic:1:1");
            _container = new TestcontainersBuilder<KafkaTestcontainer>()
                .WithKafka(configuration)
                .WithHostname(_hostName)
                .WithPortBinding(_hostPort, 9092)
                .WithName($"kafka-testcontainer-{Guid.NewGuid().ToString()[..8]}")
                .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(9092))
                .Build();

            this.BootstrapServers = $"{_hostName}:{_hostPort}";
        }
```
```
        private int getFreePort()
        {
            var tcpListener = new TcpListener(IPAddress.Loopback, 0);

            tcpListener.Start();

            int port = ((IPEndPoint)tcpListener.LocalEndpoint).Port;

            tcpListener.Stop();

            return port;
        }
```

- Version: 1.6.0-beta.2130 and 1.6.0-beta.2121

**Additional note**
On the local windows machine, there are no errors and everything works fine

**Comment by HofmeisterAn** [comment]
The Kafka configuration works fine on Docker hosts running Linux ([175-185](https://dev.azure.com/HofmeisterAn/GitHub-Testcontainers/_build/results?buildId=2130&view=logs&j=2e4c57fa-087c-5e0a-b0d9-a942b3c0c993&t=06a1d7ff-cd0c-513e-a823-a42a9f55e68d&l=175)). Based on your information, I assume, that you have issues running the tests on your CI/CD infrastructure. The Resource Reaper uses [DinD](https://github.com/HofmeisterAn/dotnet-testcontainers/blob/859826e98e619000ffe5029f088ed9db86946d6f/src/DotNet.Testcontainers/Containers/ResourceReaper.cs#L46). What's your Docker endpoint (Docker daemon socket)? Do you use tcp? Can you add the full stack trace? Btw `getFreePort` shouldn't be necessary.

**Comment by HofmeisterAn** [comment]
I'll close this issue due to inactivity. Don't hesitate to reopen it again if you still have the issue with the latest version. In this case, please add the debug logs as well (this may relate to #443).
