### ISSUE TITLE
use local Docker credential to login private registry

### ISSUE THREAD

**Issue by linitachi** [testcontainers/testcontainers-dotnet#444]
**Is your feature request related to a problem? Please describe.**
Hi, I want to use local Docker credential to login private registry,

**Describe the solution you'd like**
I can choose to use local Docker credential or using `WithRegistryAuthentication` to login docker.

**Describe alternatives you've considered**
I use 1.5 version Currently  , login by WithRegistryAuthentication 

**Additional context**
None

Thank you very much.

**Comment by HofmeisterAn** [comment]
Do you get any error? My test case works fine with `docker.io`:

```csharp
.WithImage("<account_name>/<image>")
.WithRegistryAuthentication("https://index.docker.io/v1", "<account_name>", "<account_password>")
.Build();
```

The Docker credential store, is not supported yet. If you would like to contribute, your help is more than welcome.

**Comment by linitachi** [comment]
I want to use Docker credential store so I can use docker login on CI.

**Comment by HofmeisterAn** [comment]
> I want to use Docker credential store so I can use docker login on CI.

Sorry, I got that wrong. I thought, you're saying `WithRegistryAuthentication` does not work. As I said, the Docker credential store is not implemented yet. Would you like to contribute? Help is much appreciated.

**Comment by HofmeisterAn** [comment]
I don't know if all "credential stores" are covered, but `1.6.0-beta.2219` supports the Docker config `auths` and `credsStore` configuration.

**Comment by linitachi** [comment]
Thank you very much!
have some example can give me reference XD?

**Comment by HofmeisterAn** [comment]
Just run `docker login`. You can check the type of the credential store in your Docker config. Usually, at `~/. docker/config.json`.
