### ISSUE TITLE
[Question] Support for building Microsoft SQL Server DB via DACPAC (pre-configured container)

### ISSUE THREAD

**Issue by DBloodworth95** [testcontainers/testcontainers-dotnet#453]
I was considering using this library to setup a container containing a Microsoft SQL Server image for unit tests using the pre-configured container however, the database I'm currently working with is quite big and has already been defined.

 I was wondering if this supports the ability to build the db by providing a DACPAC file?

**Comment by HofmeisterAn** [comment]
I don't know much about `DACPAC`, but I'm certain you can create your own custom Docker image that contains your database schema. At least, you can publish your built `DACPAC` file with [SqlPackage](https://docs.microsoft.com/sql/tools/sqlpackage/sqlpackage?view=sql-server-ver15) to the Docker image or container. Depends on your workflow.

**Comment by DBloodworth95** [comment]
Cool, that's what I had in mind if there wasn't any built-in support for this, thanks :)
