### ISSUE TITLE
Add missing function ` WithNetworkAliases`

### ISSUE THREAD

**Issue by vlaskal** [testcontainers/testcontainers-dotnet#455]
**Is your feature request related to a problem? Please describe.**
I have application which behaves differently based on url eg. branding.
I would like to test this application deployed in docker, that branding switching works correctly.

**Describe the solution you'd like**
I'd like to define several aliases for my container as Docker CLI option `--network-alias` does.
Also this function is available in [Java version of testcontainers](https://github.com/testcontainers/testcontainers-java/blob/14eff07a7cae8d48b07b80e309bba601f164ae66/core/src/main/java/org/testcontainers/containers/Container.java#L271). 

**Describe alternatives you've considered**
I tried to look around for other libraries and found just one. The reason why I would like to see this function is similarity with Java version. 

**Additional context**
I think this is basic functionality which is missing.

Let me know what you think about this request.
I can help with it in case.

**Comment by HofmeisterAn** [comment]
Sounds good 👍 I just can't take care of it right now. Would you like to contribute and work on it?

**Comment by vlaskal** [comment]
Cool, I can try. This is not a problem for me. 

Unfortunatelly I have Rancher desktop which cause me problem and error which is described here #431 but is caused by dotnet/Docker.DotNet#554.
Can take a time to solve main problem or do you have any other idea how to overcome this error?

**Comment by HofmeisterAn** [comment]
I haven't had any time to take a look into this issue, sorry. Usually, I use Docker Desktop or Docker Enterprise Edition. Maybe I'll have some time, beginning of next month. It would be nice to support Rancher Desktop as well. Is only `CopyOutputToAsync` broken?

**Comment by vlaskal** [comment]
Yes, support Rancher Desktop will open new areas which was cut by Docker Desktop license. 
For me it fails in `StartAsync` method when client wants to attach to container `Task<MultiplexedStream> AttachContainerAsync(...)` . I think it is not Rancher Desktop problem but more less of Moby version. 
I will look at it and in case I will jump to Docker Desktop for a while and will add `WithNetworkAliases` function.

**Comment by vlaskal** [comment]
@HofmeisterAn  I tried to create first PR #480 for this feature and also first in this repo. I hope I did everything correctly.
