### ISSUE TITLE
Extend WithDockerEndpoint method with Docker.DotNet.Credentials parameter

### ISSUE THREAD

**Issue by MarcinSzyszka** [testcontainers/testcontainers-dotnet#456]
**Is your feature request related to a problem? Please describe.**
I want to connect to docker with TLS and I want to pass credentials object prepared by my own - exactly the same way as it is done in Docker.DotNet library used in dotnet-testcontainers library

**Describe the solution you'd like**
Allow to pass Docker.DotNet.Credentials object as parameter

**Describe alternatives you've considered**
There is no chance to connect to docker with TLS now

**Additional context**
It's simple change by it would allow user to connect to secured docker api (not only with TLS)
Leave credentials configuration to user exactly as it is done in Docker.DotNet library

I will create PR with changes after submiting this issue to follow contributing rules

**Comment by HofmeisterAn** [comment]
I'll close this in favor of #370. There is already an ongoing discussion. Please notice, that the library does not expose models from `Docker.DotNet`. [Here](https://github.com/HofmeisterAn/dotnet-testcontainers/issues/370#issuecomment-966167220) is a short summary about the tasks.
