### ISSUE TITLE
Add support for credential helpers for custom registries

### ISSUE THREAD

**Issue by harrhp** [testcontainers/testcontainers-dotnet#461]
**Is your feature request related to a problem? Please describe.**
I need a way to authenticate to private registry via credential helper when pulling images. I have 2 private registries in `~/docker/.config.json` that use bat files to provide credential. I don't know credentials in advance to just do `docker login` so  i need to use helpers. Right now i can't pull images with this setup

**Describe the solution you'd like**
I think there should be another implementation of `IAuthenticationProvider` that implements credential helpers protocol described in the link below

**Describe alternatives you've considered**
i didn't find any solution

**Additional context**
https://docs.docker.com/engine/reference/commandline/login/#credential-helpers
I use version `1.6.0-beta.2226`

**Comment by HofmeisterAn** [comment]
I added the class `CredsHelperProvider` in advance:

https://github.com/HofmeisterAn/dotnet-testcontainers/blob/ba7d87befb0ece496d94ec9f350d503a264a372c/src/DotNet.Testcontainers/Builders/CredsHelperProvider.cs#L6-L19

But I don't know exactly how the credential helpers work. I haven't looked into the docs, etc. Maybe, someone else can add the implementation. Or I need to do some researches first.

**Comment by HofmeisterAn** [comment]
We'll publish this change as soon as we update the NuGet feed configuration.

**Comment by HofmeisterAn** [comment]
Published in `1.7.0-beta.2530372824`.
