### ISSUE TITLE
Support for ImageFromDockerfile

### ISSUE THREAD

**Issue by hauntingEcho** [testcontainers/testcontainers-dotnet#478]
**Is your feature request related to a problem? Please describe.**

My team has a collection of around a thousand integration tests which include a Postgres database, whose schema is managed using a collection of a few hundred Flyway migrations.  Getting the database schema initialized takes too long for local development if done for every test (ballpark 5 seconds)

**Describe the solution you'd like**

With the Java version, I've resolved this for previous projects by [creating a base image at the beginning of the test suite](https://www.testcontainers.org/features/creating_images/) and re-using that image for each test.

**Describe alternatives you've considered**

* I've looked into building the image from outside of the dotnet solution, but that does not integrate well with IDE test runners.
* Compressing the schema migration history would speed up the initialization, but comes with added risk
* Bringing up a single long-lived database container and using it as a test fixture.  This is the workaround we're currently using, but since it does not provide isolation between tests it both opens us up to flakiness (if a prior test does not clean up properly) and prevents us from running tests in parallel

**Comment by HofmeisterAn** [comment]
What exactly is missing to support your use case? I know the image builder does not offer all kind of configuration methods, but you certainly can create an image from a directory before running your tests. Reusing an image works fine.

**Comment by hauntingEcho** [comment]
Oh wow! That's my bad - I had been looking for the DSL keywords and had somehow missed the note on `ImageFromDockerfileBuilder` at the end of the supported command list, and the rest of my team had missed at as well.
