### ISSUE TITLE
Support setting ulimits on Docker containers

### ISSUE THREAD

**Issue by Xitric** [testcontainers/testcontainers-dotnet#481]
**Is your feature request related to a problem? Please describe.**

We are currently trying to spin up an Elastic container as part of our testing infrastructure, to automate integration tests against multiple versions of Elastic. Unfortunately, this requires use of the Docker `ulimits` argument, as exemplified in [their documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-file):

```yaml
es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
   ...
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

**Describe the solution you'd like**

Setting the ulimits is [supported by Docker run](https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container---ulimit), for instance:

```bash
docker run --ulimit nofile=1024:1024 debian
```

We would like for this to become available via testcontainers-dotnet. Something like the following would be great:

```c#
new TestcontainersBuilder<MyContainerType>()
    .WithImage(configuration.Image)
    .WithPortBinding(configuration.Port, configuration.DefaultPort)
    .WithUlimit(Ulimit.Memlock, -1, -1)
```

Docker supports the syntax: `<type>=<soft limit>[:<hard limit>]`, so the `.WithUlimit()` command would need to support both the type and a soft limit, and optionally a hard limit as well. If the hard limit is not provided, the soft limit is used for both values.

As of writing this proposal, Docker supports [the following ulimit types](https://github.com/docker/go-units/blob/e682442797b36348f8e1f98defdbf32bac0b6c6f/ulimit.go#L46):

```go
"core"
"cpu"
"data"
"fsize"
"locks"
"memlock"
"msgqueue"
"nice"
"nofile"
"nproc"
"rss"
"rtprio"
"rttime"
"sigpending"
"stack"
```

**Describe alternatives you've considered**

We have tried to set the ulimits globally in our Docker config `/etc/docker/daemon.json`. This is only a possibility in local development environments, and as such does not work in our CI/CD pipelines. It also seems to make our workstations a little unstable when we set all these limits globally. We would like to be able to set it on a container-by-container basis.

**Additional context**

None.

**Comment by HofmeisterAn** [comment]
Wouldn't Docker Compose be another alternative? This would be a win-win situation.

**Comment by Xitric** [comment]
Yes, compose would certainly be an alternative for us, and it would be great with compose support in any event.

But I guess that is also a larger task, and this seems like rather low-hanging fruit. I could be persuaded to open a PR myself. As for compose support, it seems that nobody has picked it up yet, and we do not have the time to invest at this point either, unfortunately.

**Comment by Xitric** [comment]
@HofmeisterAn I just took a look at the Java implementation, since I guess that is what you try to follow in terms of API functionality, and they actually declined a PR for Ulimit functionality testcontainers/testcontainers-java#4127. The argument being that it is too low-level.

Is their proposed alternative a viable approach for the .NET port? So as to not deviate too much from the Java baseline:

```java
.withCreateContainerCmdModifier(cmd ->
    cmd.getHostConfig()
    .withUlimits(new Ulimit[]{new Ulimit("nofile", ulimitsNofileSoft, ulimitsNofileHard)});
);
```

**Comment by HofmeisterAn** [comment]
> I guess that is what you try to follow in terms of API functionality

Yes, we would like to provide the same functionalities across different implementations (languages). I think that makes just sense. It's much more convenient for the developers, and we have a lot more synergies too, like the documentations, etc.

> The argument being that it is too low-level.

I think Richard is right. Just passing the Docker CLI commands through the library doesn't make much sense.

> Is their proposed alternative a viable approach for the .NET port?

We don't have the feature to modify the host configuration yet. A delegate might work. I'd favor this or Docker Compose. This will get us closer to the overall milestone.
