### ISSUE TITLE
Customize docker registry for ryuk image when using default resource reaper

### ISSUE THREAD

**Issue by harrhp** [testcontainers/testcontainers-dotnet#483]
**Is your feature request related to a problem? Please describe.**
When default session of resource reaper is [started](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Containers/ResourceReaper.cs#L108) it uses image that points to public registry, it is a problem when running tests in CI without internet access. 

**Describe the solution you'd like**
Expose property in `TestcontainersSettings` that allows to specify registry (and tag ?) for ryuk image

**Describe alternatives you've considered**
It's probably possible to disable default resource reaper and manage session manually but it's more code

**Additional context**

**Comment by HofmeisterAn** [comment]
OC, let's add this. What about `IDockerImage TestcontainersSettings.ResourceReaperImage`? We could achieve the same thing with `HubImageNamePrefix`, but the Ryuk image we're using right now is not on Docker Hub.

**Comment by harrhp** [comment]
`IDockerImage TestcontainersSettings.ResourceReaperImage` is good, it would allow to change image name also (potentialy for another existing image or custom built image)

**Comment by HofmeisterAn** [comment]
Published in `2.1.0-beta.2561986470`.
