### ISSUE TITLE
docker image exception

### ISSUE THREAD

**Issue by sieval** [testcontainers/testcontainers-dotnet#487]
**Describe the bug**
Been using TestContainers for several months now, but today we are seeing the following error in our Azure Devops build pipelines
 Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: ghcr.io/psanetra/ryuk:2021.12.20"}
Indeed the url https://ghcr.io/psanetra gives a 404 error 
Tried to solve by using the new 2.0.0 version (were using 1.6), but that did not help

**To Reproduce**
go to https://ghcr.io/psanetra you will not find anything

**Expected behavior**
The image can be downloaded 

**Screenshots**
![image](https://user-images.githubusercontent.com/24894161/175029815-9ff627d1-9eac-44de-a9a3-2b1ab47815bb.png)

**Comment by HofmeisterAn** [comment]
`ghcr.io/psanetra/ryuk:2021.12.20` is [available](https://github.com/psanetra/moby-ryuk/pkgs/container/ryuk). Do you use a private Docker registry? Then see #483.

**Comment by sieval** [comment]
Hi @HofmeisterAn 
I tried to navigate to the url ghcr.io/psanetra/ryuk:2021.12.20 , but that also resulted in a 404 (at the moment I created the issue), now is up again.
must have been a temporary problem then.
