### ISSUE TITLE
Add CHANGELOG.md

### ISSUE THREAD

**Issue by pellared** [testcontainers/testcontainers-dotnet#495]
Can you consider adding a changelog? I find it easier to use than checking the GitHub release description. Also I find updating the changelog as part of PR a good practice.

Reference: https://keepachangelog.com/en/1.1.0/

**Comment by HofmeisterAn** [comment]
I don't see any advantages over https://github.com/testcontainers/testcontainers-dotnet/releases, but if we would like to track changes in a CHANGELOG, I'm fine with that.

**Comment by pellared** [comment]
There are some pros and cons. From top of my head

Pros
1. It is under version control. So e.g. they play well with forks.
2. Finding something in a file may be easier than on a webpage (which UI can change). For example paging makes finding things harder.
3. Can be useful to communicate unrealeased changes. For instance I try too look at changelog before making an issue (reading git history can be harder).

Cons:
1. It has to be maintained and preferably in sync with GH Releases.
