### ISSUE TITLE
Bind mount points get duplicated when ConfigureContainer is called

### ISSUE THREAD

**Issue by dschreib42** [testcontainers/testcontainers-dotnet#507]
**Description**
When configuring the builder for a container and finally ConfigureContainer is called, then all container bind mounts are duplicated, because of internal concatenation is done without proper merging.

**To Reproduce**
Take the /src/Testcontainers/Builders/TestcontainersBuilderDatabaseExtension.cs and add a simple line like '.WithBindMount("/foo", "/bar")' to the builder statement. The 'WithBindMount' option must be added before "ConfigureContainer(...) is called!

**Expected behavior**
A single bind mount was added and no exception is raised.

**Current behavior**
```
Docker.DotNet.DockerApiException : Docker API responded with status code=BadRequest, response={"message":"Duplicate mount point: /bar" }

Stack Trace: 
DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
```

**Desktop (please complete the following information):**
- Version 2.0.1

**Additional context**
The problem is located in the TestcontainersBuilder class. When ConfigureContainer is called, the mount-bindings of the current and the new bind-mount configurations are just concatenated. Same issue happens maybe for other options like evironment variables as well?

**Comment by HofmeisterAn** [comment]
This snippet reproduces the issue: 

```csharp
ITestcontainersContainer container = new TestcontainersBuilder<PostgreSqlTestcontainer>()
  .WithNetworkAliases("Foo")
  .WithBindMount("/foo", "/foo", AccessMode.ReadOnly)
  .ConfigureContainer(_ =>
  {
  })
  .WithDatabase(new PostgreSqlTestcontainerConfiguration
  {
    Database = "Database",
    Username = "Username",
    Password = "Password",
  })
  .WithImage("alpine")
  .Build();
```
The respective configuration (any `IEnumerable<T>`) contains the value `2n` times (`n` equals the number of `ConfigureContainer` or `WithDatabase` calls; order is important).

https://github.com/testcontainers/testcontainers-dotnet/blob/95b647e3e895b4d7f0dfc852fc4dba480430b904/src/Testcontainers/Builders/TestcontainersBuilder.cs#L356

**Comment by alesandrino** [comment]
I never really thought about it when implementing bind mounts, but I believe that merging the configuration is not really necessary when calling ConfigureContainer. All tests green - am I missing something here?

**Comment by HofmeisterAn** [comment]
Good catch, thanks! You're right. Can you create a PR?
