### ISSUE TITLE
Add an option to specify memory limit to TestcontainersBuilder

### ISSUE THREAD

**Issue by michal-korniak** [testcontainers/testcontainers-dotnet#508]
Hi.
I noticed that some of my tests fails with OutOfMemoryException. We use windows containers (HyperV) and it seems that by default memory is limited to 1GB. I didn't find any information about changing this default value, so it seems that only possibility to change this limit is to use --memory flag during starting the container (https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources). We don't have this option now, but I think that it will be very useful. For now it could be impossible to test some memory demanding windows containers.

https://stackoverflow.com/questions/43460770/docker-windows-container-memory-limit
https://stackoverflow.com/questions/58803693/physical-memory-limits-inside-windows-container-with-process-isolation

**Comment by HofmeisterAn** [comment]
You can override the configuration with `WithCreateContainerParametersModifier` added in #503:

```csharp
.WithCreateContainerParametersModifier(parameterModifier => parameterModifier.HostConfig.Memory = 2048)
```

**Comment by michal-korniak** [comment]
Great feature, thanks!
