### ISSUE TITLE
Ability to force pull the image from a self-hosted registry to a local Docker

### ISSUE THREAD

**Issue by vova-lantsov-dev** [testcontainers/testcontainers-dotnet#525]
**Describe the bug**
I have a custom docker registry and trying to pull the image from it. The problem is that I'm getting the `DockerImageNotFoundException`. All previous issues on this topic didn't help me.

> `docker.infra.kube` below is an internal domain name and is not available publicly

The workaround is to manually run `docker pull docker.infra.kube/database/postgres/local:latest` command. After manual pulling of the image, code works as expected. But I can't manually pull the image every time, especially in CI/CD.

**To Reproduce**
<img width="698" alt="image" src="https://user-images.githubusercontent.com/45858087/181647838-705eabdf-ac52-4505-b3ae-51501e89bedf.png">

**Expected behavior**
Image is not found locally and should be pulled from the remote registry.

**Actual behavior**
```
Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: docker.infra.kube/database/postgres/local:latest"}
```

**Info:**
- Version of lib: `2.1.0`
- Locally installed Docker: `Docker Desktop for Mac 4.9.1 (81317)`
- Device: `MacBook Air M1 2020 (arm64)`

**Comment by vova-lantsov-dev** [comment]
Unfortunately, this topic is bad documented :c It would be great to have an additional documentation on how to act with different kinds of images, registries and authentication, and those images that are not pulled yet

**Comment by HofmeisterAn** [comment]
> Unfortunately, this topic is bad documented :c It would be great to have an additional documentation on how to act with different kinds of images, registries and authentication, and those images that are not pulled yet

Well, you should not have to deal with it. Testcontainers picks up the credentials by the hostname. How do you log in, into the private registry? How do you store the credentials?

Can you take a look into the logs or debug into Testcontainers to see if it finds the credentials? In the logs, you will see something like [this](https://github.com/testcontainers/testcontainers-dotnet/runs/7565582829?check_suite_focus=true#step:7:151). In that case, Testcontainers will fall back to Docker Hub. Credentials are read by these three [providers](https://github.com/testcontainers/testcontainers-dotnet/blob/f3d1f28359b240b337e0bca6a015d4c3b9a774ac/src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs#L86).

**Comment by vova-lantsov-dev** [comment]
@HofmeisterAn 
Okay, I debugged your code a bit and found more info:
What was exactly used is a `CredsStoreProvider` class. It was able to find the config and read it. But the config was in the following format:
```json
{"ServerURL":"docker.infra.kube","Username":"team-ro","Secret":"<MASKED>"}
```
And the model you're binding to is:
<img width="542" alt="image" src="https://user-images.githubusercontent.com/45858087/181724012-fcefbf32-dbc8-47cb-9e3c-a81c64a14d19.png">

As you can see, neither `ServerURL` nor the `Secret` fields are binded from JSON.

If you need to know how I authorized, it was like that
```
echo "<MASKED>" | docker login --username team-ro --password-stdin docker.infra.kube
```

Again, I use Docker Desktop for Mac, version `4.10.1 (82475)` (upgraded today to latest)

**Comment by HofmeisterAn** [comment]
Can you try it with `2.2.0-beta.2760496496`.

**Comment by vova-lantsov-dev** [comment]
@HofmeisterAn I confirm that it works with `2.2.0-beta.2760496496`

**Comment by HofmeisterAn** [comment]
Looks like I messed up the field names - sorry. I'll update the changelog in the next days. Can we close this issue?

**Comment by vova-lantsov-dev** [comment]
@HofmeisterAn I think we can close this issue. I still have a problem with CI/CD since there is another auth logic, but I didn't investigate it yet
