### ISSUE TITLE
Co-dependency on containers

### ISSUE THREAD

**Issue by digitaldias** [testcontainers/testcontainers-dotnet#526]
This is not yet a bug, more like a request for clarification. 

I am working with microservices, and it would be nice to be able to spin up the various containers for the final integration tests. 
One issue I'm having a hard time understanding is how to make one container wait for another container, but I see this is already a separate issue so that I won't go too deep into that. 

The other issue I have is I fail to understand how to avoid hard-coding my computer's IP for one container to see another i..e I am running one container that needs to see a MongoDB. They both start nicely, but the mongo container is invisible to the others unless I hard code my local computer's IP. 

I've tried a whole range of combinations of `.WithNetwork()` and `.WithNetworkAlias()`, but I cannot seem to get them to see each other. 

Some clarification in the readme should help me a lot :)

Other than that, this is a fantastic package!

**Comment by HofmeisterAn** [comment]
I collect best practices in #438, but that does not cover Docker networks yet 😅. I can add another example soon as we figured out a solution for you.

> The other issue I have is I fail to understand how to avoid hard-coding my computer's IP for one container to see another i..e I am running one container that needs to see a MongoDB.

I think this is covered by a test. You can do something like [this](https://github.com/testcontainers/testcontainers-dotnet/blob/f3d1f28359b240b337e0bca6a015d4c3b9a774ac/tests/Testcontainers.Tests/Unit/Networks/TestcontainersNetworkTest.cs#L51). The test assigns a network to both containers, then they will see each other through the hostname (`WithHostname`). _Which is not the `Hostname` property_. OC, that's misleading and needs to be improved. I just noticed it now...

> One issue I'm having a hard time understanding is how to make one container wait for another container

Something like this can be done with a custom wait strategy. Pass your own strategy to `WithWaitStrategy`.

**Comment by HofmeisterAn** [comment]
@digitaldias Do you need any further help or can we close this issue?

**Comment by HofmeisterAn** [comment]
I'll close this issue. Don't hesitate to reopen it again if you have any further questions or problems.
