### ISSUE TITLE
Re-use existing networks

### ISSUE THREAD

**Issue by fdw** [testcontainers/testcontainers-dotnet#527]
**Is your feature request related to a problem? Please describe.**
For complicated reasons, our tests already run in a Docker container. From there, we want to use testcontainers to start a sibling container.
While this works fine, we need to connect both to the same network so that the testcontainer is reachable. Unfortunately, as far as we can see, we can only connect it to an existing network if we know the network's ID (which we don't, as it is re-created regularly).

**Describe the solution you'd like**
It should be possible to connect a testcontainer to a network using only the network's name.

**Describe alternatives you've considered**
It might be possible to use some other Docker library to find the ID of the network so that we can pass it to testcontainers. But that is a lot of work.

**Comment by HofmeisterAn** [comment]
This is not yet supported and relates to [#506](https://github.com/testcontainers/testcontainers-dotnet/issues/506), [#407](https://github.com/testcontainers/testcontainers-dotnet/issues/407) too. I haven't thought much about alternatives, but I think we need something similar. Maybe we can use the `AbstractBuilder` to provide this feature for all Docker resources.

**Comment by HofmeisterAn** [comment]
Since we refactored and moved to the new container builder API, this is now possible. You can use `WithNetwork(string)` to connect to an already existing network. In addition, we extended the reuse support by implementing #1051.

**Comment by Ngx-chips** [comment]
> This is not yet supported and relates to [#506](https://github.com/testcontainers/testcontainers-dotnet/issues/506), [#407](https://github.com/testcontainers/testcontainers-dotnet/issues/407) too. I haven't thought much about alternatives, but I think we need something similar. Maybe we can use the `AbstractBuilder` to provide this feature for all Docker resources.





https://nodeer.space/questions/guide-connecting-a-testcontainer-to-an-existing-docker-network-with-testcontainers-node
