### ISSUE TITLE
DockerEndpointAuthConfig can't initialize when specifying remote host through code

### ISSUE THREAD

**Issue by BenasB** [testcontainers/testcontainers-dotnet#528]
**Describe the bug**
The static class [`TestcontainersSettings`](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Configurations/TestcontainersSettings.cs) fails to initialize when using only `WithDockerEndpoint` or `TestcontainersSettings.OS` with endpoint (this is what I call "through code" here as opposed to environment variables or poperties files). The culprit is the private property [`DockerEndpointAuthConfig`](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Configurations/TestcontainersSettings.cs#L27). If I understand correctly, none of the AuthenticationProviders are matched during `Where()`s and we end up calling a `First()` on an empty collection.

This is the error:
```
  Error Message:
   System.TypeInitializationException : The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.
---- System.InvalidOperationException : Sequence contains no elements
  Stack Trace:
     at DotNet.Testcontainers.Configurations.TestcontainersSettings.set_ResourceReaperEnabled(Boolean value)
   at Bets.Testcontainers.Test.UnitTest1.Test1() in D:\temp-test-containers\UnitTest1.cs:line 13
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Linq.ParallelEnumerable.GetOneWithPossibleDefault[TSource](QueryOperator`1 queryOp, Boolean throwIfTwo, Boolean defaultIfEmpty)
   at System.Linq.ParallelEnumerable.First[TSource](ParallelQuery`1 source)
   at DotNet.Testcontainers.Configurations.TestcontainersSettings..cctor()
```

The error is a bit misleading as at first I thought there was a problem with `ResourceReaperEnabled`, but it turns out just the static class constructor fails and `ResourceReaperEnabled` is only there because it was my first call to `TestcontainersSettings`.

I was running this in a **machine without docker installed**. When running it in a machine with docker installed, the problem was not there because I think it detected my local docker host (even though I specified a remote host with `WithDockerEndpoint`) and it failed elsewhere (no connection setup from that machine to the remote docker host, which of course fails)

**To Reproduce**
1. Perform steps on a machine without docker
2. Write a simple test class with a `WithDockerEndpoint` when configuring the test container:
```csharp
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;
using Xunit.Abstractions;

namespace Bets.Testcontainers.Test
{
    public class UnitTest1
    {
        [Fact]
        public async Task Test1()
        {
            TestcontainersSettings.ResourceReaperEnabled = false; // moby-ryuk is not accessible inside my corp network
            TestcontainersSettings.HubImageNamePrefix = "corp-docker-hub";
            var testcontainersBuilder = new TestcontainersBuilder<TestcontainersContainer>()
              .WithImage("nginx")
              .WithName("nginx-fhfh")
              .WithDockerEndpoint("my-remote-docker-host")
              .WithPortBinding(80)
              .WithAutoRemove(true)
              .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(80));

            using (var webClient = new HttpClient())
            await using (var testcontainers = testcontainersBuilder.Build())
            {
                await testcontainers.StartAsync();

                Thread.Sleep(2000);

                var response = await webClient.GetAsync($"http://{testcontainers.Hostname}:80");

                Thread.Sleep(2000);

                Assert.True(response.IsSuccessStatusCode);
            }
        }
    }
}
```
3. Run it with `dotnet test`
4. See the error

**Expected behavior**
I expect the test class (mentioned above) to pass without throwing an exception and to be able to set up the remote docker host through code only (without env variables or property file).

**Desktop:**
- Nuget: Testcontainers (2.1.0)
- Test running on Windows Server 2019 VM without docker installed
- Remote docker host on RHEL7 VM

**Workaround**
Use the `DOCKER_HOST` environment variable (or the properties file, but I haven't used that). I have to resolve to calling my test command as: `($env:DOCKER_HOST="the-same-host-as-in-WithDockerEndpoint") | dotnet test` or even use `Environment.SetEnvironmentVariable("DOCKER_HOST", "the-same-host-as-in-WithDockerEndpoint")` at the start of my test. But then what's the point of `WithDockerEndpoint`?

Hopefully this is concise and I'm not misunderstanding the design of this project. Thanks!

**Comment by HofmeisterAn** [comment]
> I was running this in a machine without docker installed.

Testcontainers tries to detect the Docker endpoint right at the beginning (by reading the env variable or properties file). In your case, it's not able to find one, and throws `System.InvalidOperationException : Sequence contains no elements` at:

https://github.com/testcontainers/testcontainers-dotnet/blob/f3d1f28359b240b337e0bca6a015d4c3b9a774ac/src/Testcontainers/Configurations/TestcontainersSettings.cs#L33

`FirstOrDefault` would support your use case I guess, but I'm not sure about any other side effects TBH. I think configuring the Docker endpoint via env variable or the properties file is fine.

> But then what's the point of `WithDockerEndpoint`?

This is a left over from the beginning of `testcontainesr-dotnet`. I kept it because it allows a much more specific configuration (accessing multiple endpoints) than just the env variable. I didn't expect a configuration like that 😅.

**Comment by BenasB** [comment]
Understood, thank you for the swift response. I was reluctant to set env variables or create property files because I will be running these tests in CI agents in which I don't have a lot of possibility for configuration. I think I will settle for the `Environment.SetEnvironmentVariable("DOCKER_HOST", "the-same-host-as-in-WithDockerEndpoint")` and get rid of  `WithDockerEndpoint`. Although it would be nice for newcomers to know that 

> Testcontainers tries to detect the Docker endpoint right at the beginning (by reading the env variable or properties file)

And it doesn't take into account `WithDockerEndpoint` or `TestcontainersSettings.OS`, but thanks nonetheless!

**Comment by HofmeisterAn** [comment]
> And it doesn't take into account `WithDockerEndpoint` or `TestcontainersSettings.OS`, but thanks nonetheless!

It does, but first it sets the default value — then you're able to override it. Your use case dosen't provide any default value at all.

> I was reluctant to set env variables or create property files because I will be running these tests in CI agents in which I don't have a lot of possibility for configuration.

Hm, I don't understand that. The concept of env variables is very common on all kind of pipelines. From my experience, it's pretty usual to configure certain tasks in a pipeline with env variables. I wouldn't use `Environment.SetEnvironmentVariable("DOCKER_HOST", "the-same-host-as-in-WithDockerEndpoint")`. I suggest something like this: https://github.com/testcontainers/testcontainers-dotnet/blob/ff76e0fb4ff00bc81b657fda982ab8c1608f6fd3/.github/workflows/cicd.yml#L130

**Comment by BenasB** [comment]
Thinking about it again, I would be able to set the environment variable in pipeline, but from time to time I (or my colleague) would like to run the test on local machines (not in pipeline) - this is why I'd like to have the docker host specified in code and committed in source control (all of us will be using the same remote docker host, no need to have different configurations).

**Comment by HofmeisterAn** [comment]
But isn't then the auto-detect feature the perfect solution? The pipeline uses the env variable, devs can decide where the env variable points to or if they would like to use something like the UNIX socket or npipe? No configuration necessary.

**Comment by BenasB** [comment]
Well the whole point of the remote docker host for us is to have a dedicated machine running our test containers, so ideally a developer that pulls a source code repo should automatically default to that remote docker host (without additional setup). I understand where you're coming from, so no big deal if this issue gets no action as a design choice.

**Comment by HofmeisterAn** [comment]
Probably we can do something like this: https://github.com/testcontainers/testcontainers-dotnet/issues/529#issuecomment-1199228210, but we need to make sure that there are no other side effects. We need to guard all builders. If one of you like, you can test it and create a pull request. I mean the error message if OC bad 😀 and not very helpful.

**Comment by BenasB** [comment]
I tested my setup using `2.2.0-beta.2835065501` and it's working as expected, much thanks @HofmeisterAn!
