### ISSUE TITLE
More descriptive error message when failing to resolve the Docker daemon

### ISSUE THREAD

**Issue by Xitric** [testcontainers/testcontainers-dotnet#529]
**Describe the bug**

A few of my colleagues have an odd setup of Docker, which led to a minor configuration mistake that caused testcontainers to fail resolving the Docker daemon. This has uncovered a small shortcoming in the `TestcontainersSettings` implementation when resolving `DockerEndpointAuthConfig`:

https://github.com/testcontainers/testcontainers-dotnet/blob/ff76e0fb4ff00bc81b657fda982ab8c1608f6fd3/src/Testcontainers/Configurations/TestcontainersSettings.cs#L27-L33

If there is no daemon at `npipe://./pipe/docker_engine` or `unix:/var/run/docker.sock`, only the `DOCKER_HOST` environment variable is left to consider. If that environment variable is missing or incorrect, the resolution fails with a very unhelpful error message:

```
OneTimeSetUp: System.TypeInitializationException : The type initializer for 'DotNet.Testcontainers.Configurations.TestcontainersSettings' threw an exception.
  ----> System.InvalidOperationException : Sequence contains no elements
  Exception doesn't have a stacktrace
```

**To Reproduce**

1. Ensure that the Docker daemon is not available at `npipe://./pipe/docker_engine` or `unix:/var/run/docker.sock`
2. Configure a DOCKER_HOST environment variable that does not point at a proper Docker daemon
3. Create a small test calling `new TestcontainersBuilder()`
4. Run the test and observe the exception during the constructor call above

**Expected behavior**

What we would like is for the code to handle the case of a missing Docker daemon gracefully, and present the user with a meaningful error (and certainly not an empty stacktrace - this might be due to running the code with `.AsParallel()`). This would have helped us to identify the error (an outdated `DOCKER_HOST` environment variable) much faster.

**Versions**

- Any version of Docker will do
- Testcontainers version 2.1.0

**Additional context**

None.

**Comment by HofmeisterAn** [comment]
> A few of my colleagues have an odd setup of Docker, which led to a minor configuration mistake that caused testcontainers to fail resolving the Docker daemon.

It looks like not just your colleagues use this odd setup, see #528 😀. What do you think? Should we use `FirstOrDefault` instead of `First` and check while building the configuration if the endpoint is set? E.g. here:

https://github.com/testcontainers/testcontainers-dotnet/blob/ff76e0fb4ff00bc81b657fda982ab8c1608f6fd3/src/Testcontainers/Builders/TestcontainersBuilder.cs#L310-L313

**Comment by Xitric** [comment]
Wow, I think I might actually have been in the process of writing this issue when the other one was posted!

I think that `FirstOrDefault` would be a good solution if combined with a check during the build, yes. After all we can manually set the Docker endpoint, so even if testcontainers fails inside `TestcontainersSettings`, we could still end up with a valid configuration by the time `Build` is invoked, right?

**Comment by HofmeisterAn** [comment]
> we could still end up with a valid configuration by the time `Build` is invoked, right?

Yes, I would asume, but I'm not 100% without looking into the code.
