### ISSUE TITLE
MongoDb Replica Set Mode Exits

### ISSUE THREAD

**Issue by the-avid-engineer** [testcontainers/testcontainers-dotnet#538]
**Describe the bug**
It appears that the MongoDb container cannot be switched to replica set mode - the container just exits after completing initialization. When I run an equivalent setup using `docker-compose.yml` (albeit not using resource reaper), I do not have the issue - the container keeps running just fine and replica set mode is available for usage.

**To Reproduce**
Make an xunit test.

Add the following file, with paths relative to the test project's csproj file, and configure the csproj to always copy this file to output.

`./DockerEntrypoints/MongoDb/Init/init.js`
```js
rs.initiate(
    {
        _id: "repro",
        version: 1,
        members: [
            {_id: 0, host: "127.0.0.1:27017"}
        ]
    }
);
```
```xml
    <ItemGroup>
      <None Update="DockerEntrypoints\**\*">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
```

Create this fixture and inject it into a test.
```cs
public class DatabaseContainerFixture : IAsyncLifetime
{
    private static readonly MongoDbTestcontainerConfiguration _mongoDbConfiguration = new("mongo:5.0.9")
    {
        Database = "repro",
        Username = "repro",
        Password = "repro"
    };
    public MongoDbTestcontainerConfiguration MongoDbConfiguration => _mongoDbConfiguration;

    public MongoDbTestcontainer MongoDbContainer { get; } = new TestcontainersBuilder<MongoDbTestcontainer>()
        .WithDatabase(_mongoDbConfiguration)
        .WithBindMount(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "DockerEntrypoints", "MongoDb", "Init"), "/docker-entrypoint-initdb.d/")
        .WithCommand("--replSet", "repro")
        .Build();

    public async Task InitializeAsync()
    {
        await MongoDbContainer.StartAsync();
    }

    public async Task DisposeAsync()
    {
        await MongoDbContainer.DisposeAsync();
    }
}
```

The following error (or similar) is thrown in InitializeAsync:

```
Docker.DotNet.DockerApiException: 'Docker API responded with status code=Conflict, response={"message":"Container 6dbd85acf7896537f92122901013146c988682581c3119a8932ae5bcf24048f6 is not running"}
```

The task exists, and if you look into the logs, the last line will be:

```
MongoDB init process complete; ready for start up.
```

**Expected behavior**
If you run an equivalent setup using docker-compose, the container does not exit - it keeps going.

```yml
version: "3.3"
services:
  mongodb:
    image: mongo:5.0.9
    ports:
      - "27017:27017"
    volumes:
      - ./DockerEntrypoints/MongoDb/Init:/docker-entrypoint-initdb.d/
    command: --replSet repro
```

**Desktop (please complete the following information):**
4.3.2 / v20.10.11 (Docker Version?)

**Additional context**
Replica set mode allows for MongoDb transactions. It's very critical to have transactions in my tests.

**Comment by HofmeisterAn** [comment]
It looks like that the container does not start properly (it exits almost immediately). With the example above, I get the following error:

```sh
[...]
BadValue: security.keyFile is required when authorization is enabled with replica sets
try 'mongod --help' for more information
[...]

MongoDB init process complete; ready for start up.
```

If I create the security key file, set the right permissions and assign the `mongodb` user and group to it, the container starts:

```cs
public sealed class GitHub : IAsyncLifetime
{
  private static readonly string Source = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

  private static readonly string Destination = "/docker-entrypoint-initdb.d";

  private static readonly string SecurityKeyFilePath = $"{Destination}/replica.key";

  private readonly TestcontainerDatabase mongoDb = new TestcontainersBuilder<MongoDbTestcontainer>()
    .WithDatabase(new MongoDbTestcontainerConfiguration { Database = "GitHub", Username = "mongodb", Password = "mongodb" })
    .WithBindMount(Source, Destination)
    .WithEntrypoint("/bin/sh", "-c", $"chown 999:999 {SecurityKeyFilePath} && mongod")
    .WithCommand("--replSet", "repro")
    .Build();

  [Fact]
  public Task Issue538()
  {
    return Task.CompletedTask;
  }

  public Task InitializeAsync()
  {
    return this.mongoDb.StartAsync();
  }

  public Task DisposeAsync()
  {
    return this.mongoDb.DisposeAsync().AsTask();
  }
}
```

Is your security key file setup properly?

**Comment by the-avid-engineer** [comment]
Interesting, I didn't even know about that setting / haven't had to configure it up to this point using docker compose - I will take a look, thank you 😀

**Comment by the-avid-engineer** [comment]
I tried fiddling with the security key but that was painful.. Instead I just removed the username/password, because the security key is not required if auth isn't set up. The only issue is that the connection string has the auth component even though there's no username/password

`mongodb://:@localhost:...`

Instead of

`mongodb://localhost:...`

Easy enough to fix in my code with a string replacement, though I wonder if the package should just not include this component of the connection string if `Username` and `Password` are null?

Either way, thank you for the help! :)

**Comment by HofmeisterAn** [comment]
> I wonder if the package should just not include this component of the connection string if Username and Password are null?

OC, we can change the behavior. Modules heavily rely on contribution, I'm not a MongoDB expert. Supporting more use cases would be great. If you have any improvement in mind, a contribution is more than welcome.

**Comment by the-avid-engineer** [comment]
https://github.com/testcontainers/testcontainers-dotnet/pull/547
