### ISSUE TITLE
Allow custom Database-name in MsSqlTestcontainerConfiguration

### ISSUE THREAD

**Issue by FelixSFD** [testcontainers/testcontainers-dotnet#541]
**Is your feature request related to a problem? Please describe.**
I'm trying to switch all our tests to use Testcontainers instead of real databases on a server. However, at least one of our Entity Framework migrations contains code to alter the current database. This does not work, because `MsSqlTestcontainerConfiguration` defaults to the `master`-DB which may not be altered.

> Microsoft.Data.SqlClient.SqlException : Cannot alter the database 'master' because it is a system database.

When I try to set the DB-name in the configuration, a `NotImplementedException` will be thrown.

```csharp
TestcontainerDatabaseConfiguration containerConfig = new MsSqlTestcontainerConfiguration
{
  Password = Random.Shared.NextAlphaNumeric(16),
  Database = $"TestDb_{Random.Shared.NextAlphaNumeric(5)}"
};
```

```stacktrace
System.NotImplementedException : The method or operation is not implemented.
MsSqlTestcontainerConfiguration.set_Database(String value)
TestStartupBase.GetTestDbContainer() line 174
TestStartupBase.StartTestDbContainer(Int32 timeout) line 142
TestStartupBase.GetTestDbConnectionString() line 156
Startup.ConfigureServices(IServiceCollection services) line 32
```

https://github.com/testcontainers/testcontainers-dotnet/blob/fff8c08385f0617c79963d569a7e5bb244133b0d/src/Testcontainers/Configurations/Modules/Databases/MsSqlTestcontainerConfiguration.cs#L34-L38

**Describe the solution you'd like**
`MsSqlTestcontainerConfiguration.Database` should be customizeable.

**Describe alternatives you've considered**
I don't know any alternatives (yet).

**Additional context**
This is probably the migration that fails when using the `master`-DB:

```csharp
migrationBuilder.AlterDatabase(collation: "Latin1_General_CS_AS");
```

**Comment by FelixSFD** [comment]
I should have checked the Pull-Requests before creating an issue... 🤦‍♂️
#521

**Comment by HofmeisterAn** [comment]
> I should have checked the Pull-Requests before creating an issue... 🤦‍♂️ #521

Yep 😅. Would you like to take a look at that? Any help is more than welcome.

**Comment by mrpmorris** [comment]
You can achieve this by calling `ExecuteScriptAsync` on your `MsSqlContainer` to create a database, and then replacing `Database=master` with your own value.

Here is some code I use in my unit tests.

```c#
internal static class TestSqlServerDatabaseFactory
{
    private static readonly Lazy<ValueTask<MsSqlContainer>> GetServerInstance = new(CreateServerInstanceAsync);
    private static int? Port;

    public static async ValueTask<string> CreateDatabaseAndGetConnectionStringAsync()
    {
        MsSqlContainer serverInstance = await GetServerInstance.Value;
        string databaseName = "Test" + Guid.NewGuid().ToString().Replace("-", "");
        await serverInstance.ExecScriptAsync($"create database [{databaseName}]");
        string connectionString =
            serverInstance
                .GetConnectionString()
                .Replace("Database=master", $"Database={databaseName}");
        return connectionString;
    }

    public static void SetPort(int port)
    {
        if (Port is not null && Port != port)
            Port = port;
    }

    private static async ValueTask<MsSqlContainer> CreateServerInstanceAsync()
    {
        var result =
            new MsSqlBuilder()
                .WithAutoRemove(autoRemove: true)
                .WithExposedPort(Port ?? 54465)
                .Build();

        await result.StartAsync();
        return result;
    }
}
```
