### ISSUE TITLE
Question: Roadmap

### ISSUE THREAD

**Issue by enginexon** [testcontainers/testcontainers-dotnet#544]
Hi,

I discovered https://testcontainers.org/ a few days ago.
It's a brilliant idea. The first thing I did was check the .NET implementation.
That is how I found this repository and immediately used it on one of my pet projects. It works like a charm. **Thank you for doing this great library.**

Based on nuget.org and GitHub, I also discovered that you are not from the initial team related to Java implementation.
This repository is a part 'Test Containers' organization, and you did some rebranding.

What does it mean for this project? Will you continue to be independent?
Does it mean you will be part of a bigger team and implement all features from Java implementation? Maybe even will be part of https://www.atomicjar.com/?

Regards,
Eugene

**Comment by HofmeisterAn** [comment]
Yes, we decided to move the project to the official Testcontainers organization to bundle the work and obtain more synergies. Furthermore, it is much more convenient for devs to have different languages organized by one organization. This helps a lot to develop a sustainable community.

I'll continue to maintain this project. Getting `testcontainers-dotnet` closer to the Java implementation with all kinds of features and modules is a major milestone we would like to achieve. There are a few things we need to prepare first, but we will start to work on this topic soon.

**Comment by HofmeisterAn** [comment]
I'll close this. If you have any further questions, don't hesitate to reopen it again or get in touch with us on Slack.
