### ISSUE TITLE
Cannot access private repository

### ISSUE THREAD

**Issue by ohadvano** [testcontainers/testcontainers-dotnet#563]
In my container builder, I am pointing to an image that is located in a private container registry (hosted on azure).
For example:
`.WithImage("myacr.azurecr.io/myimage:1.2.3.4")`

When the application is starting, I get the following error: 
`Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: myacr.azurecr.io/myimage:1.2.3.4"}`

I am authenticated with the ACR and when manually pulling the image using docker pull, the operation succeeds.

**To Reproduce**
Can't reproduce as this is a private repository

**Expected behavior**
Image will be successfully pulled from ACR

**Desktop (please complete the following information):**
Running on Windows 11

**Comment by HofmeisterAn** [comment]
How do you login into the private registry? Right now, we support these options:

- https://docs.docker.com/engine/reference/commandline/login/
- https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#access-an-image-from-a-private-container-registry

**Comment by ohadvano** [comment]
I login using "az acr login" command and Azure Managed Identity
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication-managed-identity?tabs=azure-cli
I can't tell the underlying implementation, but I suspect it would use docker login

**Comment by HofmeisterAn** [comment]
Did you try one of the latest snapshot releases too (like `2.2.0-beta.2835065501`)?

**Comment by ohadvano** [comment]
Updating to that version solved the problem, Thank you.
