### ISSUE TITLE
Cleaner way to connect to containers from inside and outside of docker

### ISSUE THREAD

**Issue by redzimskidev** [testcontainers/testcontainers-dotnet#570]
**Is your feature request related to a problem? Please describe.**
What I'm trying to accomplish is to have one set of integration/e2e tests working both from test runner and from a docker container in CI/CD. Some tests require calling RabbitMQ management HTTP API. I'm using this to get the link to this API:

```
    public Uri GetManagementUri() => InDocker
        ? new Uri($"http://host.docker.internal:{_rabbitMqContainer.GetMappedPublicPort(15672)}")
        : new Uri($"http://localhost:{_rabbitMqContainer.GetMappedPublicPort(15672)}");

    private bool InDocker => Environment.GetEnvironmentVariable("DOTNET_RUNNING_IN_CONTAINER") == "true";
```

I thought it might be possible to move this logic to the library instead.

**Describe the solution you'd like**
Not sure, I know the library already figures out if it's running inside of docker, so maybe expose a bool value representing that? Maybe the container could point to the HTTP address with the port similiar to how it does with connection strings, but not sure how popular of a requirement that is.

**Describe alternatives you've considered**
Well, the above solution works, I'm just after something cleaner.

**Comment by redzimskidev** [comment]
My bad, didn't figure out Hostname is a thing in time.

**Comment by HofmeisterAn** [comment]
No, worries. There is also a similar concept of `DOTNET_RUNNING_IN_CONTAINER`:

https://github.com/testcontainers/testcontainers-dotnet/blob/96c72633858d7e2f64d457035faaa4803c4b0f21/src/Testcontainers/Clients/TestcontainersClient.cs#L71-L77
