### ISSUE TITLE
Building TestcontainersBuilder<MsSqlTestcontainer> throws a NotImplementedException Exception

### ISSUE THREAD

**Issue by Onik97** [testcontainers/testcontainers-dotnet#573]
**Describe the bug**
Building TestcontainersBuilder<MsSqlTestcontainer> throws a NotImplementedException Exception

**To Reproduce**
`
public static MsSqlTestcontainer _dbContainer = new TestcontainersBuilder<MsSqlTestcontainer>()
        .WithDatabase(new MsSqlTestcontainerConfiguration
        {
            Database = "DiscordBotDb",
            Username = "username",
            Password = "password123!"
        }).Build();
`
Running the code causes the Exception

**Expected behavior**
A container should run on docker

**Comment by Onik97** [comment]
Worth noting that the following is working
`public static MySqlTestcontainer _dbContainer = new TestcontainersBuilder<MySqlTestcontainer>()
        .WithDatabase(new MySqlTestcontainerConfiguration
        {
            Database = "DiscordBotDb",
            Username = "username",
            Password = "password123!"
        }).Build();`

Difference: The above is MySQL, the bug is MS SQL

**Comment by HofmeisterAn** [comment]
It is not a bug. The Microsoft SQL Server image does not support the `Database` property (and others #439). You need to take care and create the database instead. However, with one of the recent changes it is possible to create the database now. Use the latest snapshot release `2.2.0-beta.2835065501`:

https://github.com/testcontainers/testcontainers-dotnet/blob/fcbd4df81c370185ccdc10f948b43949f6ffcf2a/tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/MsSqlFixture.cs#L14

**Comment by Onik97** [comment]
Thank you for the quick response @HofmeisterAn, updated to the pre release and it works, looking forward to the next release!
