### ISSUE TITLE
Add support for localstack (AWS emulator)

### ISSUE THREAD

**Issue by fabiogouw** [testcontainers/testcontainers-dotnet#592]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem

**Describe the solution you'd like**
[Localstack](https://github.com/localstack/localstack) is used to simulate AWS services, like SQS queues. It would be great if we could have a module that help us to setup this container for the .NET version of Testcontainers.

**Describe alternatives you've considered**
When I needed to test againts a localstack container, I've spinned up it with the TestcontainersContainer class.

**Additional context**
The Java version of Testcontainers already have [this module](https://github.com/testcontainers/testcontainers-java/tree/master/modules/localstack), I can help porting this code to C#. There's the #493 issue that aims to move modules to their own project, I think we could start this one here following the pattern.

**Comment by bgener** [comment]
In the initial implementation, the tests execute the script in the running container to create the sqs queue. The tests can be extended to cover the rest of localstack resources
