### ISSUE TITLE
You can create a state with `DisposeAsync` where you get `ObjectDisposedErrors`

### ISSUE THREAD

**Issue by paule96** [testcontainers/testcontainers-dotnet#595]
**Describe the bug**

The `DisposeAsync` method isn't thread safe and as a user of the library you also don't have any option to write a thread safe wrapper around it.

**To Reproduce**

see the sample

**Expected behavior**

The `SemaphoreSlim` that is used by `TestcontainersContainer` should be disposed thread safe. Or at least the cosument of an `TestcontainersContainer` should have bean any sign that the object is disposed. 

**Screenshots**

**Desktop (please complete the following information):**
- Version 2.1.0
- dotnet 6.0.401

**Additional context**

Here is a sample implementation to reproduce the bug. It's happen around 1/3 tries:

```csharp
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;

const TestcontainersState testcontainersCreatedStates = TestcontainersState.Created | TestcontainersState.Running | TestcontainersState.Exited;
Console.WriteLine("Hello, World!");
var config = new MsSqlTestcontainerConfiguration()
{
    Password = Guid.NewGuid().ToString()
};
var myContainer = new TestcontainersBuilder<MsSqlTestcontainer>()
                    .WithDatabase(config);
var dbTestContainer = myContainer.Build();
await dbTestContainer.StartAsync();
await Task.WhenAll(stopIt(dbTestContainer), stopIt(dbTestContainer));

async Task stopIt(MsSqlTestcontainer dbTestContainer)
{
    try
    {
        if (dbTestContainer.State != testcontainersCreatedStates)
        {
            await dbTestContainer.DisposeAsync();
        }

    }
    catch (ObjectDisposedException ex)
    {
        Console.WriteLine($"lol error: {ex.Message}");
    }
}

```

**Comment by HofmeisterAn** [comment]
Thanks for reporting the issue.

**Comment by paule96** [comment]
@HofmeisterAn thanks for the fast fix. :)

**Comment by paule96** [comment]
btw. you solutions is nice. I was thinking twice about the code. But I learned that this is a pretty nice way :)
