### ISSUE TITLE
Option to always pull image when creating a container

### ISSUE THREAD

**Issue by BenasB** [testcontainers/testcontainers-dotnet#601]
**Is your feature request related to a problem? Please describe.**
I have a case where my tests should always retrieve the latest image. AFAIK, this library now pulls an image only if it's missing (sort of like `docker run --pull "missing" ...`, which is the default) but I would like to **always** pull the image (so it gets the most up to date version of it) before starting the container (like `docker run --pull "always" ...` does).

**Describe the solution you'd like**
An option that enables this behavior would be perfect, for example a `.WithImagePull(PullType)` builder method where `PullType` could be `Missing` (default behavior) or `Always`. Although I am not sure how this could be implemented.

**Describe alternatives you've considered**
The image pull can be done explicitly before building/starting the container by using [Docker.DotNet](https://github.com/dotnet/Docker.DotNet) directly and this would be okay, but testcontainers-dotnet already has support for credential helpers (AFAIK Docker.DotNet does not support that) which I'm trying to take advantage of (since I'm authenticating to a private registry)

How much would this be feasible? Thanks!

**Comment by HofmeisterAn** [comment]
An equivalent to the Java [withImagePullPolicy](https://www.testcontainers.org/features/advanced_options/#image-pull-policy) would be great.

**Comment by BenasB** [comment]
That's exactly what I've imagined, although I don't have experience with the Java version. I will try to take a look at how it's implemented there and see how I could implement a similar feature for testcontainers-dotnet

**Comment by kiview** [comment]
@BenasB Let us know if you have any questions regarding the Java implementation 🙂
