### ISSUE TITLE
Unnamed images after successful test run 

### ISSUE THREAD

**Issue by schmallaria** [testcontainers/testcontainers-dotnet#602]
Good morning,

I have a test case where i create two docker images using the `ImageFromDockerfileBuilder`. Everything is working as expected. But when i look into docker desktop after the test run I found two images called `<none>`. Every time I run the test, two new images (same size) named `<none>` are added.

![2022-10-05_06h52_55](https://user-images.githubusercontent.com/14905344/193984523-cf9c2490-6671-47b6-b14c-a71209eb0f7d.png)

The images are created with the following code:
```
new ImageFromDockerfileBuilder().WithDockerfileDirectory("../../../../ProxyServer")
            .WithName("ProxyServer")
            .WithDeleteIfExists(true)
            .WithCleanUp(true)
            .Build();
```

I'm not sure if it's a bug or if i miss something.

**Comment by HofmeisterAn** [comment]
I am sorry, I cannot reproduce it with your configuration. It just keeps the images with `WithDeleteIfExists(false)`. Which makes sense (it tags the new image with an existing name). See my example below. Can you share some more code or information of your configuration?

```csharp
public sealed class GitHub : IAsyncLifetime
{
  private IImageFromDockerfileBuilder imageFromDockerfileBuilder = new ImageFromDockerfileBuilder()
    .WithDockerfileDirectory(CommonDirectoryPath.GetGitDirectory(), Path.Combine("tests", "Testcontainers.Tests", "Assets"))
    .WithDeleteIfExists(false)
    .WithName("github:issue602");

  [Fact]
  public async Task Issue602_1()
  {
    await this.imageFromDockerfileBuilder.Build()
      .ConfigureAwait(false);
  }

  [Fact]
  public async Task Issue602_2()
  {
    await this.imageFromDockerfileBuilder.Build()
      .ConfigureAwait(false);
  }

  public Task InitializeAsync()
  {
    return Task.CompletedTask;
  }

  public Task DisposeAsync()
  {
    return Task.CompletedTask;
  }
}
```

**Comment by schmallaria** [comment]
Sure, i've created a new solution [testcontainers-test.zip](https://github.com/testcontainers/testcontainers-dotnet/files/9721371/testcontainers-test.zip) and put all relevant files on it.

If you execute the test you will see one image named `<none>` (now it's only one image, because in the test it's only one image which is being created).

Maybe my Dockerfile is not correct?

**Comment by HofmeisterAn** [comment]
If you run `docker inspect ${image_id}`, you will see that those "images" are related to your Dockerfile. As far as I know this behavior is intended and a result of the multi-stage Dockerfile, see: https://github.com/moby/moby/issues/34151#issuecomment-316049721.

@kiview How does tc-java handle it? Maybe we can label the intermediate images with the resource reaper session?

**Comment by kiview** [comment]
@HofmeisterAn I just checked and we don't have a test for a multi-stage Dockerfile build in `testcontainers-java`. We are adding the labels to the `BuildImageCmd`, but I can't tell if this means that they will be automatically added to the intermediate images as well, this is something we would need to verify (/cc @eddumelendez).

**Comment by eddumelendez** [comment]
the behavior is the same in `testcontainers-java`. After test finished there is a unamed image which serves as a cache for upcoming builds as explained in https://github.com/moby/moby/issues/34151#issuecomment-316049721

**Comment by schmallaria** [comment]
I don't know what to now (i'm very new to docker)? Should I remove those images manually? Are you looking for an automated solution?

**Comment by HofmeisterAn** [comment]
I do not think you need to bother with those intermediate images (layers). As mentioned in the comment, this is the default behavior of Docker. Docker caches those images to improve the performance.

It is important to understand, that those intermediate images do not take (a lot of) additional space. It will not store the same image twice or something like that.

If you still would like to remove the images you can use one of the suggestions from the discussion on the Moby Project.

----

With Testcontainers for .NET there is an additional way to get rid of the intermediate images while running the tests:

1. Add the `testcontainers.resource-reaper-session` label to each stage (line 3-4, 15-16).
2. Pass the Resource Reaper session ID to the Docker image build.

```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
ARG CSPROJ_FILE_PATH="src/WeatherForecast/WeatherForecast.csproj"
ARG RESOURCE_REAPER_SESSION_ID
LABEL "testcontainers.resource-reaper-session"=$RESOURCE_REAPER_SESSION_ID
WORKDIR /app

COPY . .

RUN dotnet restore $CSPROJ_FILE_PATH

RUN dotnet publish $CSPROJ_FILE_PATH --configuration Release --output out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
ARG CSPROJ_FILE_PATH="src/WeatherForecast/WeatherForecast.csproj"
ARG RESOURCE_REAPER_SESSION_ID
LABEL "testcontainers.resource-reaper-session"=$RESOURCE_REAPER_SESSION_ID
WORKDIR /app

EXPOSE 443

COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WeatherForecast.dll"]
```

```csharp
_ = new ImageFromDockerfileBuilder()
  .WithBuildArgument("RESOURCE_REAPER_SESSION_ID", ResourceReaper.DefaultSessionId.ToString("D"))
  .Build();
```

I do not think there is much more we can do, but we will discuss about it the following week.

**Comment by schmallaria** [comment]
@HofmeisterAn your solution works for now. Thanks a lot.

**Comment by HofmeisterAn** [comment]
We have decided not to continue working on this topic. Testcontainers for .NET (incl. other implementations) behave like Docker in this case. Detecting the intermediate images by the Resource Reaper would be great, unfortunately the API is not capable of that.

We think the workaround is an acceptable solution for now. If you have anything else in mind just reopen the issue and let us know.
