### ISSUE TITLE
ICSharpCode.SharpZipLib.Tar.TarException : Entry closed at '0' before the '9630' bytes specified in the header were written

### ISSUE THREAD

**Issue by Omrisha** [testcontainers/testcontainers-dotnet#609]
**Describe the bug**
When running the test of the Weather Forecast project getting an error with TAR archive operation.

**To Reproduce**
1. Clone testcontainers-dotent repo
2. open SLN file in visual studio (I used visual studio 2022)
3. Build solution
4. Go to test explorer
5. Run the tests and get the issue.

**Expected behavior**
The tests will be completed successfully with no TAR exception

**Screenshots**
![image](https://user-images.githubusercontent.com/1386140/195300932-8eaee23f-ae8f-4dfd-93a8-fe829ea1564e.png)

**Additional context**
I'm on Windows 11, using visual studio 2022 and docker version 4.12.0.

**Comment by HofmeisterAn** [comment]
Oh, that one is interesting. Can you add `.vs` (probably `.idea` too) to the `.dockerignore` file (https://github.com/testcontainers/testcontainers-dotnet/blob/develop/examples/WeatherForecast/.dockerignore) and try it again? I am pretty sure this will fix it.

**Comment by Omrisha** [comment]
@HofmeisterAn Hey, I added .vs and .idea to .dockerignore and it worked. Do you know why this caused a problem?

**Comment by Omrisha** [comment]
Also when I could use CommonDirectoryPath in order to make docker image in my project like your project?

**Comment by HofmeisterAn** [comment]
Visual Studio has some exclusive file access. We cannot put those files into the tarball. I will add a fix later that day.

> Also when I could use CommonDirectoryPath in order to make docker image in my project like your project?

You can use anywhere you want. Just make sure it can resolve the [right files](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers/Builders/CommonDirectoryPath.cs#L62-L95) in the directory tree.

**Comment by Omrisha** [comment]
@HofmeisterAn when it will be available on the nuget package?

**Comment by HofmeisterAn** [comment]
> @HofmeisterAn when it will be available on the nuget package?

It is part of the latest snapshot release.
