### ISSUE TITLE
Build an image running with Nuke gives TarException 

### ISSUE THREAD

**Issue by lucasteles** [testcontainers/testcontainers-dotnet#618]
**Describe the bug**
I use [Nuke](https://github.com/nuke-build/nuke) to automate a lot of tasks on my projects, like tests environment configuration, and I did not have any problem running containers with it.
But, when I try to build an image I'm getting: 
```shell
Unhandled exception. ICSharpCode.SharpZipLib.Tar.TarException: Entry closed at '0' before the '3183' bytes specified in the header were written
      at ICSharpCode.SharpZipLib.Tar.TarOutputStream.CloseEntry()
      at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Finish()
      at ICSharpCode.SharpZipLib.Tar.TarOutputStream.Dispose(Boolean disposing)
      at System.IO.Stream.Close()
      at System.IO.Stream.Dispose()
      at ICSharpCode.SharpZipLib.Tar.TarArchive.Dispose(Boolean disposing)
      at ICSharpCode.SharpZipLib.Tar.TarArchive.Dispose()
      at DotNet.Testcontainers.Images.DockerfileArchive.Tar()
      at DotNet.Testcontainers.Clients.DockerImageOperations.BuildAsync(IImageFromDockerfileConfiguration configuration, CancellationToken ct)
      at Program.<Main>$(String[] args) in C:\d\nuke-testcontainers\src\Program.cs:line 24
      at Program.<Main>(String[] args)
```

This happens if I run a test, csproj, or even if I put the build logic inside the Nuke Target.

If I run the logic outside Nuke everything works as expected

**To Reproduce**

Just try to build an image with/from a Nuke target

I made an example to demonstrate the bug:
https://github.com/lucasteles/nuke-testcontainers

If you run on the repository root: 
```ps
dotnet run --project .\src\
```
it will work as normal

To get the error run on the repository root : 
```ps
dotnet tool restore
dotnet nuke
```

**Expected behavior**
Should not throw an exception when running from Nuke

**Comment by HofmeisterAn** [comment]
Is VS running? Exclude the `.vs` directory via `.dockerignore`, see (#609):

https://github.com/testcontainers/testcontainers-dotnet/blob/aba9f75020bcd7f309e905fe71c874a765919eef/examples/WeatherForecast/.dockerignore#L2

Or another process is blocking a file. In your case you probably need to exclude the Nuke binaries. I assume they have something similar like Cake's tool directory..

**Comment by HofmeisterAn** [comment]
The .NET implementations use Glob pattern matching, it looks like there are more cases covered by Docker or Go. As far as I know, `*` will match everything except slashes. Files in `.nuke/` are not ignored e.g.

Try the following:

```
**
!src
src/obj
src/bin
```

OC, `*` should behave the same like in Docker.

**Comment by lucasteles** [comment]
@HofmeisterAn changing the glob to `**` worked 🎉

**Comment by HofmeisterAn** [comment]
👍 I will reopen it. It makes sense to support `*` too (same behavior as Docker). Other developers may stumble across the same issue. We can map a single `*` to `**` internal, that would fix the issue without much effort.
