### ISSUE TITLE
Sign/Strongly name the Testcontainers.dll file.

### ISSUE THREAD

**Issue by RobbeDGH** [testcontainers/testcontainers-dotnet#619]
**Is your feature request related to a problem? Please describe.**
The Testcontainers.dll downloaded from the NuGet package is not signed/strongly named. This makes it not possible to use from another strongly named/signed assembly.

It is default behavior for NuGet assemblies to be signed.

**Describe the solution you'd like**
Testcontainers.dll is now signed and strongly named. 
I.e. "sn.exe -v Testcontainers.dll" now succeeds.

**Describe alternatives you've considered**
I can maybe make my project no longer strongly signed but this is might not be possible.

**Additional context**
I would try to make a pull request but I cannot (or should not :)) generate the private keys used while signing.

A common use case where this is very useful:
A library you use in production is signed. This library exposes internals via the [InternalsVisibleTo] attribute to a unit test project. This makes the unit test dll obligated to be signed as well. This in turn makes it mandatory for every referenced dll to be signed as well, which means it's no longer possible to use Testcontainers.

**Comment by HofmeisterAn** [comment]
Do you know if we can use the Strong Name Tool with Ubuntu (maybe with Mono)? Or how do you add the strong name to the assembly on Linux? I know it is a left over from the .NET Framework and may exclude developers (like your case).

> I would try to make a pull request but I cannot (or should not :)) generate the private keys used while signing.

I think you can create a pull request. Strong names are not critical regarding security. MS recommends to add the private key to the vcs:

> If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system.

**Comment by RobbeDGH** [comment]
I'm unfortunately not that familiar with building on Linux.

I did try running "sn" in a Ubuntu Server VM and although it did not find the binary anywhere, it did suggest installing mono-develop as a possible solution, so maybe that's an option.

Either way I did make Pull Request #622 for this, incorporating your suggestion of including the keys.

I generated a keypair locally (on windows) using the sn.exe tool.

Waiting for the pipelines to finish to see if it will build or not.

Small note, to make it usuable though, will have to do the same thing for Docker.DotNet.

**Comment by HofmeisterAn** [comment]
> I'm unfortunately not that familiar with building on Linux.

No worries. I can take a closer look at it tomorrow. Your pull request or build looks good though.

> Small note, to make it usuable though, will have to do the same thing for Docker.DotNet.

Ok, I was going to ask about that too. I know there is an open pull request (https://github.com/dotnet/Docker.DotNet/pull/567). I will try to get that PR merged first.

**Comment by ivd-git** [comment]
Thanks for the great work.

Just wanted to say that for me having a strongly named Testcontainers.dll file would also be very helpful.

If there is anything I can do to help, please reach out. On the other hand, #622 looks very good indeed.

**Comment by HofmeisterAn** [comment]
We are waiting for the Docker.DotNet release. @JamieMagee asked [yesterday](https://github.com/dotnet/Docker.DotNet/commit/82103a22fc514680e148b3061fb056dedd548bc8#commitcomment-99658104) and I did a while ago — sorry.

**Comment by HofmeisterAn** [comment]
Unfortunately, we are still waiting for the Docker.DotNet release, but I stumbled across the following project: https://github.com/dsplaisted/strongnamer. Perhaps this will be helpful for those of you who depend on strong names.
