### ISSUE TITLE
MySqlTestContainer fails in DinD environments

### ISSUE THREAD

**Issue by DanielHabenicht** [testcontainers/testcontainers-dotnet#632]
**Describe the bug**
See title, container will not come up as the `ExecScriptAsync` will always return an error, because the IP address set in Hostname is not accessible inside the container.

This seems to be the case in other test containers too. 

**Expected behavior**
https://github.com/testcontainers/testcontainers-dotnet/blob/e6dbb6313205d72f847773e7c197bc92307d7dd2/src/Testcontainers/Containers/Modules/Databases/MySqlTestcontainer.cs#L41

`{this.Hostname}` should be `localhost`

**Additional context**

From #629

**Comment by HofmeisterAn** [comment]
This is easy to fix. Since the commands run inside the container, the hostname is always `localhost`. Equivalent to the modules wait strategies. Replace `Hostname` with `localhost`.

**Comment by HofmeisterAn** [comment]
Published in `2.2.0-beta.3311860540`.

**Comment by DanielHabenicht** [comment]
Works on my project :+1:
https://github.com/OSPRS/DataDonation/pull/3
