### ISSUE TITLE
Container start timeout in azure pipelines

### ISSUE THREAD

**Issue by JBastiaan** [testcontainers/testcontainers-dotnet#633]
Hello,

we tried using testcontainers in our integrationtest setup to provide isolation between different testclasses. However we keep running into issues where the container times out trying to start when running our pipelines in Azure Devops. It happens not every time, sometimes it works, sometimes it does not.

See below our container setup. We added the WithPortBinding since we thought maybe there was some port clashes so this should select a random available host port presumably. Does anyone recognize these problems, or have any suggestions what we can try?

Our devops agents use `ubuntu-latest`.

```
public class AppFactory : WebApplicationFactory<IntegrationTestingStartup>, IAsyncLifetime
{   
    private readonly MsSqlTestcontainer _dbContainer =
        new TestcontainersBuilder<MsSqlTestcontainer>()
            .WithDatabase(new MsSqlTestcontainerConfiguration("mcr.microsoft.com/mssql/server:2019-latest")
            {
                Password = "12345678"
            })
            .WithPortBinding(1433, true)
            .Build();

    ...Omitted for brevity..

    private string GetSqlConnectionString()
    {
        var sqlConnectionStringBuilder = new SqlConnectionStringBuilder(_dbContainer.ConnectionString)
        {
            TrustServerCertificate = true
        };

        return sqlConnectionStringBuilder.ConnectionString;
    }

    public async Task InitializeAsync()
    {
        //Timeout here
        await _dbContainer.StartAsync();
    }

    public new async Task DisposeAsync()
    {
        await _dbContainer.StopAsync();
    }
}
```

**Comment by HofmeisterAn** [comment]
What error do you get exactly? Can you add the stack trace and container logs?

**Comment by JBastiaan** [comment]
Yea that's the thing, we do not get any exceptions, the dbcontainer appears to be hanging trying to start. Eventually the azure devops pipeline gives up after 1 hour.

**Comment by HofmeisterAn** [comment]
Enable logging and check the container logs. I am certain that the wait strategy does not complete then. `StartAsync` waits until all wait strategies are completed (I guess that is blocking). Do you use the Microsoft hosted agents or your own agents?

**Comment by JBastiaan** [comment]
Allright, yea we use Microsoft hosted agents for our build pipelines. Ill see if we can enable the logging and get something useful out of it.

**Comment by HofmeisterAn** [comment]
That is odd. Is the above example a reduced configuration of what you are using? GitHub-hosted runners are the same as the Microsoft hosted agents. All tests run on GitHub-hosted runners which is equivalent to your build environment then.

**Comment by JBastiaan** [comment]
What do you mean by reduced configuration?

**Comment by HofmeisterAn** [comment]
I assume the example above does not contain all the code you are using to create a container instance. Can you add the missing parts?

**Comment by JBastiaan** [comment]
```
public class AppFactory : WebApplicationFactory<IntegrationTestingStartup>, IAsyncLifetime
{
    private readonly MsSqlTestcontainer _dbContainer =
        new TestcontainersBuilder<MsSqlTestcontainer>()
    .WithDatabase(new MsSqlTestcontainerConfiguration("mcr.microsoft.com/mssql/server:2019-latest")
    {
        Password = "12345678"
    })
    .WithPortBinding(1433, true)
    .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(1433))
    .Build();

    protected override IHostBuilder CreateHostBuilder()
    {
        var hostBuilder = Host.CreateDefaultBuilder()
            .AddSerilog(false)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<IntegrationTestingStartup>();
            });

        hostBuilder.UseEnvironment(Common.Infrastructure.Configuration.Constants.Environments.Local);
        return hostBuilder;
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        var assemblyLocation = Assembly.GetAssembly(typeof(AssetServiceFactory))!.Location;
        var path = Path.Join(Path.GetDirectoryName(assemblyLocation), "test-configuration.json");

        builder
            .ConfigureAppConfiguration(config =>
            config
                .AddJsonFile(path, false)
                .AddInMemoryCollection(
                AssetServiceConfiguration.Create(GetSqlConnectionString())));

        base.ConfigureWebHost(builder);
    }

    private string GetSqlConnectionString()
    {
        var sqlConnectionStringBuilder = new SqlConnectionStringBuilder(_dbContainer.ConnectionString)
        {
            TrustServerCertificate = true
        };

        return sqlConnectionStringBuilder.ConnectionString;
    }

    public async Task InitializeAsync()
    {
        var logger = LoggerFactory.Create(config =>
        {
            config.SetMinimumLevel(LogLevel.Debug);
            config.AddDebug();
            config.AddConsole();
        }).CreateLogger("TestContainers");

        TestcontainersSettings.Logger = logger;
        
        await _dbContainer.StartAsync();
        var scope = Services.CreateAsyncScope();
        var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
        await dbContext.Database.MigrateAsync();
        await DbUtilities.InitializeDbForTestsAsync(dbContext);
    }

    public new async Task DisposeAsync()
    {
        await _dbContainer.StopAsync();
    }
}
```

**Comment by JBastiaan** [comment]
Running with this now, trying to see if we get any logging in the pipeline, hope this helps

**Comment by JBastiaan** [comment]
Seems we were to soon to draw conclusions, after running with the Testcontainer logger we realized the testcontainer isnt even started on the failed runs so it seems to be something in our own startup. We did see testcontainer logging on the succesful pipeline runs. Thanks for your assistance, sorry it turned out to be unrelated to testcontainers.

**Comment by HofmeisterAn** [comment]
No worries, if you need further assistance or have any questions let us know.
