### ISSUE TITLE
Dockerfile ignored in .dockerignore, not sent in tarball to docker daemon

### ISSUE THREAD

**Issue by wterpstra** [testcontainers/testcontainers-dotnet#648]
**Describe the bug**
When a tarball is created, it uses the .dockerignore file to filter the tarball contents and reduce the amount of files that are sent to the docker daemon. However, when a .dockerignore file ignores itself or a Dockerfile these files should still appear in the tarball.

**To Reproduce**
1. Create a new solution and project(s) (mine is a solution with multiple projects with their own dockerfile)
2. Add a .dockerignore file in the root that ignores itself  and any Dockerfile so they won't show up in the image
3. Run the ImageFromDockerfileBuilder
4. Open the tarball from the temp directory
5. See that the .dockerignore file in the root is missing and the Dockerfile files in the project directories are missing
6. See the ImageFromDockerfileBuilder throw an exception that no image was built. This is a bit of a misleading error due to limitations on Docker.DotNet errors. It can't even build an image because the Dockerfile is missing from the tarball.

**Expected behavior**
 When reading the [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#dockerignore-file) it states that:

>You can even use the .dockerignore file to exclude the Dockerfile and .dockerignore files. These files are still sent to the daemon because it needs them to do its job. But the ADD and COPY instructions do not copy them to the image.

I think this means that when creating a tarball to send to the docker daemon the .dockerignore and Dockerfile files should always be included if they exist. If either file appears in the .dockerignore file the ADD and COPY instructions will make sure not to copy them in the resulting image.

**Screenshots**

**Desktop (please complete the following information):**
- Windows 11 Pro 22000.1098
- Docker Desktop for Windows 20.10.17
- Testcontainers 2.2.0

**Additional context**

**Comment by HofmeisterAn** [comment]
> when a .dockerignore file ignores itself or a Dockerfile these files should still appear in the tarball.

The `.dockerignore` file is always excluded:

https://github.com/testcontainers/testcontainers-dotnet/blob/3d1660e05ec0675f53889ba790a44923c76a7614/src/Testcontainers/Images/DockerIgnoreFile.cs#L31-L33

You are right, thanks for the issue. Testcontainers for .NET does not include `.dockerignore` and the `Dockerfile` (if it is excluded) in the tarball.

I assume we can simply add a negate pattern for `.dockerignore` and `Dockerfile` to the end of the ignore patterns list. WDYT? Would you like to create a pull request?

**Comment by wterpstra** [comment]
I'm not sure what the behavior is when something is added to the list and then also negated in the same list. I'll have a stab at this tomorrow and see. If it doesn't work we can always override the Accepts method of the `IgnoreFile` class

**Comment by HofmeisterAn** [comment]
I would expect it works as long as it is the last item (which we can control). Here is a test that should cover it:

https://github.com/testcontainers/testcontainers-dotnet/blob/3d1660e05ec0675f53889ba790a44923c76a7614/tests/Testcontainers.Tests/Fixtures/Images/IgnoreFileFixture.cs#L18
