### ISSUE TITLE
SharpZipLib 1.4.0 dependency may cause deadlocks

### ISSUE THREAD

**Issue by wterpstra** [testcontainers/testcontainers-dotnet#650]
**Describe the bug**
SharpZipLib has found a regression in its codebase (https://github.com/icsharpcode/SharpZipLib/issues/786) between 1.3.3 and 1.4.0 which can cause deadlocks when writing tarballs

v2.2.0 references SharpZipLib 1.4.0 which may cause deadlocks.

**To Reproduce**
In my case I was running Testcontainers in a BeforeFeature binding in Specflow.

**Expected behavior**
No deadlocks. I don't see any preview versions where this fix is included. However, rolling back to 1.3.3 should also work.

**Screenshots**

**Desktop (please complete the following information):**
- Testcontainers v2.2.0

**Additional context**
https://github.com/icsharpcode/SharpZipLib/issues/788
https://github.com/icsharpcode/SharpZipLib/pull/791

**Comment by HofmeisterAn** [comment]
I assume you call something like `Wait()`, `GetAwaiter().GetResult()` or `Result` in `BeforeFeature`? That will block the async context and is not recommended anyway. You will probably get around this by wrapping your call in `Task.Run(() => {});` (not recommended either), but might work. Best is to stick to the async context.

**Comment by wterpstra** [comment]
No, SpecFlow is all async, the BeforeFeature bindings are async too. The `.GetAwaiter().GetResult()` is done inside the SharpZipLib library code. 

See this diff: https://github.com/icsharpcode/SharpZipLib/pull/791/files#diff-99397a219e400099c43754f54b5b72a2fdd17d5e1bdbeef6ca31e160cef4b07bL384

They use an isAsync flag which was set incorrectly (this is the change where they fixed it). This change has not yet been released. With the isAsync flag set to true, like in 1.4.0, it will write out to the outputStream asynchronously. This is then awaited in the TarOutputStream: `public TarEntry GetNextEntry() => GetNextEntryAsync(CancellationToken.None, true).GetAwaiter().GetResult();` and deadlocks.

**Comment by HofmeisterAn** [comment]
Yep, that looks not right. I think you can override the version with `1.3.3` in your project file (in the dependency graph) in the meantime.

**Comment by wterpstra** [comment]
When I reference SharpZipLib 1.3.3 I get a package version downgrade detected error from dotnet restore because the Testcontainers v2.2.0 NuGet package has a SharpZipLib >= 1.4.0 dependency. I downgraded Testcontainers to v2.1.0 which also works for now! 👍
