### ISSUE TITLE
show docker build errors on ImageFromDockerfileBuilder build 

### ISSUE THREAD

**Issue by RAAvenger** [testcontainers/testcontainers-dotnet#656]
**problem**
We used "--mount=type=cache,id=nuget,target=/root/.nuget/packages \" in our dockerfile, so on docker build a buildkit related error occurred and build failed but only thing we could see was an "InvalidOperationException" saying "Docker image myimage has not been created.".
To debug this situation we set a logger to TestcontainersSettings.Logger and then we have seen actual problem. 

**solution**
It could be nice if you observed docker log and on error, throw an exception with error's message.

**Comment by HofmeisterAn** [comment]
Unfortunately, this is a limitation of Docker.DotNet. The latest release does not handle the error response. It got recently fixed in the development branch, though: https://github.com/dotnet/Docker.DotNet/pull/590. I update the dependency soon as it is released.

Notice we are also thinking about a default logging mechanism that works with different test frameworks in the future to provide more information what Testcontainers is doing.

**Comment by HofmeisterAn** [comment]
Since Docker.DotNet has just released a new version (that includes the mentioned fix above), you will receive error messages (exceptions) if building or pulling images fails. I have updated the dependency and it will be included in the next TC release.

**Comment by DanielHabenicht** [comment]
Is this already out? Because I still can't see the error of the build in the exception.

**Comment by HofmeisterAn** [comment]
Yes, it should be included in version 3.1.0 and should log an error if the message contains one:

https://github.com/testcontainers/testcontainers-dotnet/blob/bc176a09575277e657db3149ae0a95b567249b65/src/Testcontainers/Clients/TraceProgress.cs#L35-L38

You can set a custom logger and forward traces if necessary, they are [ignored](https://github.com/testcontainers/testcontainers-dotnet/blob/bc176a09575277e657db3149ae0a95b567249b65/src/Testcontainers/Logger.cs#L79-L95) to not pollute the output.

**Comment by DanielHabenicht** [comment]
I am on 3.2.0 and I did not get an error message without adding a logger for the trace output (see: #914)

**Comment by HofmeisterAn** [comment]
Unfortunate, then the message it not part of error property 😞. I am not happy with the current situation either. Increasing the log level or forwarding the messages to information will pollute the log output. However, leaving it unchanged is also not ideal.

**Comment by DanielHabenicht** [comment]
Thats unfortunate then. Hopefully Docker.DotNet can add it still. 

Coming from XUnit adding the logger to TestContainer (when using it in an IClassFixture) is quite complicated maybe we could add a 
A. a quick switch for setting Testcontainer to log everyhing (even Debug) 
B. n easier way to add IOutputHelper / respectively just Console.Out (`TextWriter`) to visualize the output.

**Comment by HofmeisterAn** [comment]
> A. a quick switch for setting Testcontainer to log everyhing (even Debug)

Maybe being able to set the default log level for the provided logger would be a good trade-off. If more customization is necessary, developers can still use a custom logger.

> B. n easier way to add IOutputHelper / respectively just Console.Out (`TextWriter`) to visualize the output.

Providing a good logging mechanism is not easy for us. I have described it [here](https://github.com/testcontainers/testcontainers-dotnet/issues/603#issuecomment-1284152927) and [here](https://github.com/testcontainers/testcontainers-dotnet/pull/684). However, we can certainly implement a module (an independent NuGet package) specifically for test frameworks like xUnit.net or NUnit to integrate with their default logging mechanism.
