### ISSUE TITLE
Tests are pending forever on Mac M1

### ISSUE THREAD

**Issue by jezzdk** [testcontainers/testcontainers-dotnet#662]
I'm trying to run my test suite using Rider on my M1 MacBook but the tests are stuck in a "pending" state. I've also tried to run the tests in the terminal, but it hangs after the last message, which is:
"Starting test execution, please wait...
A total of 1 test files matched the specified pattern."

It sits there forever. There is no timeout after 30 or 60 seconds or even half an hour.

The containers are all started and there are no suspicious messages in the logs. It seems the containers are working just fine, the tests just never runs.

**To Reproduce**
1. Run 'dotnet test'
2. The project is building fine
3. The containers are running fine
4. No tests are running, no errors in the logs and the process doesn't exit

**Expected behavior**
The tests should run.

**Screenshots**
![Screenshot 2022-11-08 at 13 47 33](https://user-images.githubusercontent.com/139632/200567608-9ebf7953-16fb-4b84-a980-6e8e95c44574.png)

**Desktop (please complete the following information):**
- macOS Ventura 13.0
- Docker Desktop 4.13.1
- .NET 6
- Testcontainers 2.2.0
- Jetbrains Rider 2022.2.3

**Comment by HofmeisterAn** [comment]
Without any code (example) I only can guess. I guess one of your wait strategy never completes. Testcontainers creates and starts a container and waits until the wait strategies complete. As soon as they are fulfilled it continues execution. Or you're blocking the async context and run into a deadlock.

**Comment by jezzdk** [comment]
That sounds interesting. I don't think I have implemented a wait strategy, at least not on purpose :)

I'm adding a MSSQL container, and the tests hang when it's started. The container is configured like this:
```
private static int MsSqlPort = 1433;
private readonly MsSqlTestcontainer _dbContainer = new TestcontainersBuilder<MsSqlTestcontainer>()
        .WithDatabase(new MsSqlTestcontainerConfiguration("mcr.microsoft.com/azure-sql-edge")
        {
            Port = MsSqlPort,
            Password = "some_random_password"
        })
        .WithName("OOA_T_MsSql_" + Guid.NewGuid().ToString())
        .WithExposedPort(MsSqlPort)
        .WithPortBinding(MsSqlPort, true)
        .Build();
```

And is started like this:
```
public async Task InitializeAsync()
{
    await _dbContainer.StartAsync();
}
```

Without the '_dbContainer.StartAsync()' the tests are running (but obviously failing).

**Comment by jezzdk** [comment]
Okay based on your input, and some guessing on my part as well, I was able to make the tests run :)

I added this to the container configuration:
```
.WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(MsSqlPort))
```

That did the trick. 

I'm not sure why this is needed though, since the same configuration has been working just fine on my Windows machine. Perhaps it's because of the special `mcr.microsoft.com/azure-sql-edge` image that the M1 needs. In any case, some more dotnet documentation on wait strategies would be appreciated :)

**Comment by HofmeisterAn** [comment]
Did you use the MSSQL module with a different image (`mcr.microsoft.com/azure-sql-edge`)? That would explain it. The MSSQL module runs some `sqlcmd` command that might not work for `azure-sql-edge`. I would be careful and double-check if it is enough to just wait for the port, that's not always the case.

> In any case, some more dotnet documentation on wait strategies would be appreciated :)

Any specific ideas or recommendations? What's missing [here](https://dotnet.testcontainers.org/api/wait_strategies/)? I am happy to update it.

**Comment by jezzdk** [comment]
@HofmeisterAn Well basically I was looking for information and examples about the different ways of implementing a waiting strategy. I ended up pretty much guessing, and frankly I was (pleasantly) surprised that it worked.
