### ISSUE TITLE
ElasticsearchTestcontainer + WithImage -> no way to change version

### ISSUE THREAD

**Issue by meriturva** [testcontainers/testcontainers-dotnet#669]
See this simple configuration:

```
_testcontainers = new TestcontainersBuilder<ElasticsearchTestcontainer>()
                        .WithImage("elasticsearch:8.5.0")
```

Container created still version 8.3.2 and no 8.5.0.

is it my fault? do I have to create a new `ElasticsearchTestcontainerConfiguration` to do that?
Thanks

**Comment by HofmeisterAn** [comment]
Are you sure this is the example or snippet you are running? It pulls the right version here. However, the above example is not set up correct to run a [module](https://dotnet.testcontainers.org/modules/). You need to invoke the extension method.

```csharp
_ = new TestcontainersBuilder<ElasticsearchTestcontainer>()
  .WithDatabase(new ElasticsearchTestcontainerConfiguration("elasticsearch:8.5.0") { Password = Guid.NewGuid().ToString() })
  .Build();
```

https://github.com/testcontainers/testcontainers-dotnet/blob/af9f7f86175de3aa48b866a95981ef9873bf3322/tests/Testcontainers.Tests/Fixtures/Containers/Unix/Modules/Databases/ElasticsearchFixture.cs#L19-L21

**Comment by meriturva** [comment]
Thanks @HofmeisterAn 
with:

`.WithDatabase(new ElasticsearchTestcontainerConfiguration("elasticsearch:8.5.0")`

works like a charm!
