### ISSUE TITLE
When will the next release be?

### ISSUE THREAD

**Issue by alandecastros** [testcontainers/testcontainers-dotnet#681]
Hi,

I'm looking forward to use WithResourceMapping so I want to know when will the next release be?

Regards

**Comment by HofmeisterAn** [comment]
I would like to merge one more features today or tomorrow, then I can publish a snapshot version.

**Comment by HofmeisterAn** [comment]
With some small delay, but we published `2.3.0-beta.3547636764` ✌️.

**Comment by alandecastros** [comment]
Thanks @HofmeisterAn!
