### ISSUE TITLE
Azurite Container not usable

### ISSUE THREAD

**Issue by Jejuni** [testcontainers/testcontainers-dotnet#682]
When using the default configuration for `AzuriteTestcontainer` the container builds fine, but no data can be uploaded or downloaded using Microsoft's `Azure.Storage.Blobs` library. It crashes with a `Azure.RequestFailedException`:

![image](https://user-images.githubusercontent.com/33608497/202917355-2681d5ff-d571-46ad-a891-51f20bfd7ed1.png)

## Simple repro

```cs
    [Fact]
    public async Task Should_Create_Azurite_Container()
    {
        // Arrange
        ITestcontainersBuilder<AzuriteTestcontainer> builder = new TestcontainersBuilder<AzuriteTestcontainer>()
            .WithAzurite(new AzuriteTestcontainerConfiguration("mcr.microsoft.com/azure-storage/azurite:3.20.1"));

        await using AzuriteTestcontainer? container = builder.Build();
        await container.StartAsync();

        var blobServiceClient = new BlobServiceClient(container.ConnectionString);
        string containerName = Guid.NewGuid().ToString().ToLowerInvariant();

        BlobContainerClient containerClient = await blobServiceClient.CreateBlobContainerAsync(containerName);

        BlobClient blobClient = containerClient.GetBlobClient("testdata");
        byte[] data = { 1, 2, 3 };

        // Act
        _ = await blobClient.UploadAsync(new MemoryStream(data), true);
        Response<BlobDownloadInfo> downloaded = await blobClient.DownloadAsync();

        // Assert
        Assert.NotNull(downloaded?.Value);
        var ms = new MemoryStream();
        await downloaded.Value.Content.CopyToAsync(ms);
        byte[] downloadedData = ms.ToArray();

        Assert.Equal(data, downloadedData);
    }
```

Test works up until `_ = await blobClient.UploadAsync(new MemoryStream(data), true);` is called.
That means that azurite is reachable and creates a container, but then it can't upload anything.

## Expected behavior
Upload and download should work with default configuration.

## Package Version:
- Testcontainers: v2.2.0
- Azure.Storage.Blobs: 12.14.1

**Comment by HofmeisterAn** [comment]
I have not much experience with Azurite, but I noticed that the upload (PUT) HTTP request probably uses a wrong path. If you look into the container logs you will notice something like:

    2022-11-22 10:08:25 172.17.0.1 - - [22/Nov/2022:09:08:25 +0000] "PUT /devstoreaccount1/testdata HTTP/1.1" 400 -

It looks like the container name is missing. Chaning the `GetBlobClient("testdata")` to `GetBlobClient(containerName + "/testdata")` returns:

    2022-11-22 10:11:51 172.17.0.1 - - [22/Nov/2022:09:11:51 +0000] "PUT /devstoreaccount1/bad1f4fc-72ca-4e96-b721-0f7d19b10147/testdata HTTP/1.1" 201 -
    2022-11-22 10:11:52 172.17.0.1 - - [22/Nov/2022:09:11:52 +0000] "GET /devstoreaccount1/bad1f4fc-72ca-4e96-b721-0f7d19b10147/testdata HTTP/1.1" 200 3

Running your example again Testcontainers Cloud immediately works somehow. Notice the difference of the `blobClient`'s `URI`. On the left side is TCC vs. Docker Desktop on the right:

![image](https://user-images.githubusercontent.com/9199345/203275181-db049359-1eba-4960-80c0-9a461c0c0905.png)

**Comment by Jejuni** [comment]
@HofmeisterAn That's a really good observation.

It should definitely work without specifying the containerName again, because the `BlobContainerClient` is used to create the `BlobClient`, and that one already has the containerName baked into the Uri.

I've got it to work with my own configuration (left out everything not relevant and used static port):

```cs
    public class TestAzuriteTestContainer : TestcontainersContainer
    {
        protected TestAzuriteTestContainer(ITestcontainersConfiguration configuration, ILogger logger) : base(configuration, logger)
        {
        }
        
        public int BlobPort { get; set; }

        public string ConnectionString =>
            $"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:{BlobPort}/devstoreaccount1";
    }


    [Fact]
    public async Task Should_Create_Azurite_Container()
    {
        // Arrange
        ITestcontainersBuilder<TestAzuriteTestContainer> builder = new TestcontainersBuilder<TestAzuriteTestContainer>()
            .WithImage("mcr.microsoft.com/azure-storage/azurite:3.20.1")
            .WithPortBinding(8089, 10000)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(10000))
            .ConfigureContainer(container =>
            {
                container.BlobPort = 8089;
            });

        await using TestAzuriteTestContainer? container = builder.Build();
        await container.StartAsync();

        var blobServiceClient = new BlobServiceClient(container.ConnectionString);
        string containerName = Guid.NewGuid().ToString().ToLowerInvariant();

        BlobContainerClient containerClient = await blobServiceClient.CreateBlobContainerAsync(containerName);

        BlobClient blobClient = containerClient.GetBlobClient("testdata");
        byte[] data = { 1, 2, 3 };

        // Act
        _ = await blobClient.UploadAsync(new MemoryStream(data), true);
        Response<BlobDownloadInfo> downloaded = await blobClient.DownloadAsync();

        // Assert
        Assert.NotNull(downloaded?.Value);
        var ms = new MemoryStream();
        await downloaded.Value.Content.CopyToAsync(ms);
        byte[] downloadedData = ms.ToArray();

        Assert.Equal(data, downloadedData);
    }
```

This configuration works and the test passes.
But it only worked after I switched from `AzuriteTestcontainer` to my own `TestAzuriteTestContainer`. Using the same builder, but using `AzuriteTestcontainer` shows the same problem.

Not sure how it's internally set up, but there seems to be something wrong with the `AzuriteTestcontainer`

**Comment by Jejuni** [comment]
I've figured out how to make it work, but I have no idea why it has to be that way.

The only difference I could find between your config and mine is that I used `127.0.0.1` instead of `localhost` in the ConnectionString.
And that seems to be the deciding factor.

Using the initial test I posted and simply adding `var conStr = container.ConnectionString.Replace("localhost", "127.0.0.1");` before passing the ConnectingString to the `BlobServiceClient` makes it work:

```cs
ITestcontainersBuilder<AzuriteTestcontainer> builder = new TestcontainersBuilder<AzuriteTestcontainer>()
            .WithAzurite(new AzuriteTestcontainerConfiguration("mcr.microsoft.com/azure-storage/azurite:3.20.1"));

await using AzuriteTestcontainer? container = builder.Build();
await container.StartAsync();

var conStr = container.ConnectionString.Replace("localhost", "127.0.0.1");
var blobServiceClient = new BlobServiceClient(conStr);
```

**Comment by HofmeisterAn** [comment]
That is a bit of a coincidence. Recently, we noticed that `localhost` may not work reliable depending on the host configuration (host that runs the tests). Docker does not always use the same port mapping for IPv4 and IPv6. There are cases where you need to use different ports for an IPv4 and IPv6 address. That is why we [changed](https://github.com/testcontainers/testcontainers-dotnet/blob/66ac45380a169656bcd3d5c2dcffe6e6b45835f8/src/Testcontainers/Containers/TestcontainersContainer.cs#L379) the hostname resolution (workaround). We are looking into a better fix, to support what ever IP address (address family) the host favours for `localhost`. **I do not think these issues relate to each other**.

----

> I've got it to work with my own configuration (left out everything not relevant and used static port):

This configuration stills fails for my tests on macOS and Windows and constructs a wrong URI for the HTTP request (without container name). It fails **without** Testcontainers too. I think it is an issue with the `BlobContainerClient` (not an Azurite expert). Lets take a closer look at it and start an Azurite container:

```console
docker run --rm -d -p 10000 mcr.microsoft.com/azure-storage/azurite:3.20.1 azurite-blob --blobHost 0.0.0.0
```

Get the random assigned public host port via `docker ps` and replace it in our test (first line):

```csharp
const string blobPort = "51264";

const string connectionString = "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:" + blobPort + "/devstoreaccount1";

var blobServiceClient = new BlobServiceClient(connectionString);

var blobContainerName = Guid.NewGuid().ToString("D");

BlobContainerClient blobContainerClient = await blobServiceClient.CreateBlobContainerAsync(blobContainerName)
  .ConfigureAwait(false);

var blobClient = blobContainerClient.GetBlobClient("data");

_ = await blobClient.UploadAsync(new MemoryStream(new byte[] { 0 }), true)
  .ConfigureAwait(false);

BlobDownloadInfo download = await blobClient.DownloadAsync()
  .ConfigureAwait(false);
```

You will get the exact same error. The client hits the container again without container name:

    2022-11-24 11:32:52 172.17.0.1 - - [24/Nov/2022:10:32:52 +0000] "PUT /devstoreaccount1/data HTTP/1.1" 400 -

I think this is a bug in the `BlobContainerClient` or the part that constructs and instantiates the object. If you look closer to the screenshot above, you will see that the `AccountName` is empty and `BlobContainerName` is the account name.

![image](https://user-images.githubusercontent.com/9199345/203769706-adedbd2e-49f4-481d-953d-d8082c4a7b66.png)

Can you please create an issue at [Azurite](https://github.com/Azure/Azurite)?

**Comment by Jejuni** [comment]
I've opened an issue on the Azure Blob Client repo: https://github.com/Azure/azure-sdk-for-net/issues/32809

**Comment by HofmeisterAn** [comment]
Looks very likely to be a bug in `BlobContainerClient`. I will close this issue in the meantime.
