### ISSUE TITLE
Running container inside container with custom network returns wrong gateway address

### ISSUE THREAD

**Issue by HofmeisterAn** [testcontainers/testcontainers-dotnet#683]
Testcontainers returns the wrong gateway address if a container is running "inside" another container and has a custom network assigned. The current implementations just looks for networks with the name `bridge`:

https://github.com/testcontainers/testcontainers-dotnet/blob/446f002a992dc026cc83ea44c09641de99660a7b/src/Testcontainers/Containers/TestcontainersContainer.cs#L391

_Originally posted by @ricardofmfreitasMP in https://github.com/testcontainers/testcontainers-dotnet/discussions/679#discussioncomment-4198806_

**Comment by kiview** [comment]
This is interesting. In this case, I would expect the same issue for `testcontainers-java`. Can you conceptionally share a reproducer for us? (.NET reproducer is also fine, we can port it)

**Comment by HofmeisterAn** [comment]
That's my test [example](https://dev.azure.com/HofmeisterAn/GitHub/_git/testcontainers-dotnet-679?path=/GitHub.cs). L75 contains the "workaround".

**Comment by HofmeisterAn** [comment]
@kiview @eddumelendez @mdelapenya Do we know why we have the [limitation](https://github.com/testcontainers/testcontainers-java/blob/a93183fb2ce3d72a982281bf34d94ec06695309c/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L425-L436) and only consider networks with the name `bridge`? I know `bridge` is default, but what do we return in case of someone assigns a custom network?

**Comment by kiview** [comment]
To add some context, I tracked the changes in `testcontainers-java`. This behavior was introduced through https://github.com/testcontainers/testcontainers-java/pull/2151. 

Before, we did a more manual and dynamic lookup using this method, leveraging a running container:
https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/core/src/main/java/org/testcontainers/dockerclient/DockerClientConfigUtils.java#L20
