### ISSUE TITLE
[Enhancement]: Start Ryuk as a privileged container

### ISSUE THREAD

**Issue by taspeotis** [testcontainers/testcontainers-dotnet#694]
### Problem

I'm using podman in lieu of docker. It seems to work fine with `TestcontainersSettings.ResourceReaperEnabled = false;` however this is not ideal. Without that setting it fails with permission errors.

I have podman running as rootful, I believe if testcontainers-dotnet had a similar option to `ryuk.container.privileged = true` (to create it with `--privileged`) it would work completely.

https://www.testcontainers.org/features/configuration/#customizing-ryuk-resource-reaper

https://github.com/containers/podman/discussions/14238#discussioncomment-2918978

### Solution

Some way to create Ryuk as privileged, for podman and whatever other reasons the testcontainers "Customizing Ryuk resource reaper" documentation refers to:

> In some environments ryuk must be started in privileged mode to work properly

### Benefit

Works with podman

### Alternatives

`TestcontainersSettings.ResourceReaperEnabled = false;`

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
Indeed, `ryuk.container.privileged` is not yet supported. We need to add the custom configuration property first, similar to 45a8935f3783f9f70770506d30672a35eaed686a. Afterwards with can update the [ResourceReaper](https://github.com/testcontainers/testcontainers-dotnet/blob/2d04584618b544edea0c38d3c2ecfaa03210466c/src/Testcontainers/Containers/ResourceReaper.cs#L56-L65) builder configuration. I suggest two separate PRs. Would you like to add the property first?

**Comment by taspeotis** [comment]
Thanks, I'll see what I can do in the next few days.

**Comment by taspeotis** [comment]
Sorry I wasn't able to contribute this but thank you for adding it!
