### ISSUE TITLE
[Enhancement]: NonDurability Config to Improve Performance

### ISSUE THREAD

**Issue by pdevito3** [testcontainers/testcontainers-dotnet#696]
### Problem

Databases used for testing are [leveraging durability](https://www.postgresql.org/docs/current/non-durability.html) at the cost of performance for no gain given the context.

### Solution

Given that this is a testing library, I'd propose that durability is disabled by default and could be added back with something like the below:

```csharp
        return new TestcontainersBuilder<PostgreSqlTestcontainer>()
            .WithDatabase(new PostgreSqlTestcontainerConfiguration
            {
                Database = "db",
                Username = "postgres",
                Password = "postgres"
            })
            .WithName($"IntegrationTesting_PeakLims_{Guid.NewGuid()}")
            .WithImage("postgres:latest")
            .Durable()
            .Build();
```

### Benefit

Enhanced performance of your tests. 
https://shusson.info/post/non-durable-postgres-for-e2e-tests

### Alternatives

?

### Would you like to help contributing this enhancement?

No

**Comment by HofmeisterAn** [comment]
With the current module implementation it is a bit difficult to achieve, it requires a dedicated extension method (to turn it on / off). This will be definitely possible with https://github.com/testcontainers/testcontainers-dotnet/issues/493#issuecomment-1319938591.

We can set the `postgresql.conf` file f.g. in the meantime with the recently added `WithResourceMapping(byte[], string)` builder method, before the container and PostgreSQL starts.

**Comment by HofmeisterAn** [comment]
I [disabled](https://github.com/testcontainers/testcontainers-dotnet/blob/07b5c8cea7466b6b0419384ef10d6246af38fe67/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs#L89-L91) the PostgreSQL durability in the new module. BTW, I noticed you can disable it already with the legacy module approach by using `WithCommand(params string[])`.
