### ISSUE TITLE
[Bug]: Hang docker desktop with running MsSqlTestcontainer

### ISSUE THREAD

**Issue by meysamhadeli** [testcontainers/testcontainers-dotnet#702]
### Testcontainers version

2.2.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows 11

### Host arch

x64

### .NET version

7.0

### Docker version

```shell
Docker Desktop 4.14.1
```

### Docker info

```shell
_container = new TestcontainersBuilder<MsSqlTestcontainer>()
            .WithDatabase(new MsSqlTestcontainerConfiguration
            {
                Password = Guid.NewGuid().ToString()
            })
            .WithImage("mcr.microsoft.com/mssql/server:2022-latest")
            .Build();
```

### What happened?

My Docker desktop and project hang when I start the `MsSqlTestcontainer`!
In the case of `PostgresTestcontainer`, I have no issues.

This issue hasn't been resolved yet, according to what I've read about MsSqlTestcontainer in testcontainer.

**Comment by HofmeisterAn** [comment]
> This issue hasn't been resolved yet, according to what I've read about MsSqlTestcontainer in testcontainer.

What makes you think of that? Even the pre-configured module does not use the latest MSSQL image your example runs fine here. Usually, I see projects block the async context. Can you share how you start the container? Does the container exist?

**Comment by meysamhadeli** [comment]
> > This issue hasn't been resolved yet, according to what I've read about MsSqlTestcontainer in testcontainer.
> 
> What makes you think of that? Even the pre-configured module does not use the latest MSSQL image your example runs fine here. Usually, I see projects block in the async context. Can you share how you start the container?

Thanks for reaching out.
I add this line `.WithPortBinding(1433, true)` base on your advice in this question and my problem fixed: https://github.com/testcontainers/testcontainers-dotnet/discussions/533

could you set this config as behind the scene for default config!? that we don't need to add this mandatory line!

**Comment by meysamhadeli** [comment]
> > This issue hasn't been resolved yet, according to what I've read about MsSqlTestcontainer in testcontainer.
> 
> What makes you think of that? Even the pre-configured module does not use the latest MSSQL image your example runs fine here. Usually, I see projects block the async context. Can you share how you start the container? Does the container exist?

I don't block thread, I use it asynchronously in start of my tests with implementation of `IAsyncLifetime`:
```csharp
    private MsSqlTestcontainer MsSqlTestContainer;

    public async Task InitializeAsync()
    {
        // for example using of MsSqlTestContainer
        MsSqlTestContainer = TestContainers.MsSqlTestContainer;
        await MsSqlTestContainer.StartAsync();
    }

    public async Task DisposeAsync()
    {
        await MsSqlTestContainer.StopAsync();
    }
```

**Comment by HofmeisterAn** [comment]
> could you set this config as behind the scene for default config!? that we don't need to add this mandatory line!

We do that already. It is done by the `WithDatabase(TestcontainerDatabaseConfiguration)` extension method.

https://github.com/testcontainers/testcontainers-dotnet/blob/360651350081a0b5d8bac33cce2caa2834271c96/src/Testcontainers/Builders/TestcontainersBuilderDatabaseExtension.cs#L26

It is important to configure modules through the extension method.

> Due to a design flaw in the current module system, pre-configured containers must be configured through their corresponding extension method (WithDatabase or WithMessageBroker):

You will find more information in our [docs](https://dotnet.testcontainers.org/modules/) and in this Stackoverflow [answer](https://stackoverflow.com/a/74040305/690017). We will fix this design flaw with the new and enhanced module API. If you still have issues to get your configuration running, please share an example. I am happy to take a closer look at it.

**Comment by meysamhadeli** [comment]
> > could you set this config as behind the scene for default config!? that we don't need to add this mandatory line!
> 
> We do that already. It is done by the `WithDatabase(TestcontainerDatabaseConfiguration)` extension method.
> 
> https://github.com/testcontainers/testcontainers-dotnet/blob/360651350081a0b5d8bac33cce2caa2834271c96/src/Testcontainers/Builders/TestcontainersBuilderDatabaseExtension.cs#L26
> 
> It is important to configure modules through the extension method.
> 
> > Due to a design flaw in the current module system, pre-configured containers must be configured through their corresponding extension method (WithDatabase or WithMessageBroker):
> 
> You will find more information in our [docs](https://dotnet.testcontainers.org/modules/) and in this Stackoverflow [answer](https://stackoverflow.com/a/74040305/690017). We will fix this design flaw with the new and enhanced module API. If you still have issues to get your configuration running, please share an example. I am happy to take a closer look at it.

Thanks for your guide :)
