### ISSUE TITLE
Receiving ICSharpCode.SharpZipLib.Tar.TarException Even with Latest Version

### ISSUE THREAD

**Issue by bryanllewis** [testcontainers/testcontainers-dotnet#716]
### Testcontainers version

2.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

7.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.11.1)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 67
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.36GiB
 Name: docker-desktop
 ID: 6IB7:3ID4:KR5C:P7CU:ICZH:FQD4:TA3U:XT62:PSNM:QFBV:VQCK:Z6F5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

I am attempting to build my image but I get an exception:

`ICSharpCode.SharpZipLib.Tar.TarException : Entry closed at '0' before the '136355' bytes specified in the header were written`

The code being run is:

```
var myAppImageBuilder = new ImageFromDockerfileBuilder()
      .WithName("rabbittoredisbridge")
      .WithDockerfileDirectory("C:/Source")
      .WithDockerfile("DevOps/Docker/MyApp-Dockerfile");

var myAppImage = await myAppImageBuilder.Build();
```

I tried running the test via the Visual Studio Test Explorer and I get the exception listed.  If I close VS and just run "dotnet test" it still fails but I get less verbose output.  I have seen references to similar exceptions in the Issues, but I am running the latest version Testcontainers and my .dockerignore file does contain references to both .vs and .idea.  Not sure what else to try.

### Relevant log output

```shell
Message: 
ICSharpCode.SharpZipLib.Tar.TarException : Entry closed at '0' before the '136355' bytes specified in the header were written

  Stack Trace: 
TarOutputStream.CloseEntryAsync(CancellationToken cancellationToken, Boolean isAsync)
TarOutputStream.FinishAsync(CancellationToken cancellationToken, Boolean isAsync)
TarOutputStream.Finish()
TarOutputStream.Dispose(Boolean disposing)
Stream.Close()
TarArchive.Dispose(Boolean disposing)
TarArchive.Dispose()
DockerfileArchive.Tar()
DockerImageOperations.BuildAsync(IImageFromDockerfileConfiguration configuration, CancellationToken ct)
RabbitToRedisWorkerTests.InitializeAsync() line 67
```

**Comment by HofmeisterAn** [comment]
> my .dockerignore file does contain references to both .vs and .idea. Not sure what else to try.

I have only seen this issue when a file is in exclusive access by another process (like files inside the `.vs` directory). SharpZipLib cannot add these files to the tarball. Your configuration will create a tarball that includes everything underneath `C:/Source`. Make sure non of the files are in exclusive access by another process.

1. Debugging into `DockerfileArchive` should help to identify the file or directory:
    https://github.com/testcontainers/testcontainers-dotnet/blob/768dfd265d395341130510c20447e4de30efc346/src/Testcontainers/Images/DockerfileArchive.cs#L95
2. Move the `.dockerignore` file to `C:/Source`.
3. Make sure you are using the correct Glob patterns. Without knowing the file structure, I guess something like this will do it:
    ```
    **/.vs
    **/bin
    **/obj
    ```

**Comment by HofmeisterAn** [comment]
The next version will show a more meaningful [error message](https://github.com/testcontainers/testcontainers-dotnet/blob/33b1d74f0b528adb498b28eefb5f57292b39afe3/src/Testcontainers/Images/DockerfileArchive.cs#L117) (incl. root exception). We add the `.vs` and `.idea` directory by default to the [ignore list](https://github.com/testcontainers/testcontainers-dotnet/blob/33b1d74f0b528adb498b28eefb5f57292b39afe3/src/Testcontainers/Images/DockerIgnoreFile.cs#L51-L53) too. This should cover and help with most configurations. As explained above add the file that is in exclusive access to the `.dockerignore` file.

I will close this issue in the meantime. If you have any further questions do not hesitate to reopen the issue again.
