### ISSUE TITLE
[Bug]: Docker.DotNet.DockerImageNotFoundException : testcontainers/ryuk:0.3.4 image not found 

### ISSUE THREAD

**Issue by ghost** [testcontainers/testcontainers-dotnet#722]
### Testcontainers version

2.2.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

6

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:28:44 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.1 (90346)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.12.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.3)
  extension: Manages Docker extensions (Docker Inc., v0.2.13)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 15
  Running: 13
  Paused: 0
  Stopped: 2
 Images: 13
 Server Version: 20.10.20
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 201.1GiB
 Name: docker-desktop
 ID: 4RTG:AO6B:6WZD:QZM7:TXNK:OG7V:WC25:RRQX:KIGA:UJGK:HD7G:6GGR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

I'm trying to use testcontainers in order to write some db integration tests. 

Following is the setup

`using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Containers;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace __e2e.Setup
{
    public class ContainersFactory<TEntryPoint, TDbContext> : WebApplicationFactory<TEntryPoint>, IAsyncLifetime
        where TEntryPoint : EntryPoint
        where TDbContext : DbContext
    {
        private readonly MsSqlTestcontainer _dbContainer;

        public ContainersFactory()
        {
            _dbContainer = new TestcontainersBuilder<MsSqlTestcontainer>()
                .WithImage("mcr.microsoft.com/mssql/server:2017-latest")
                .WithEnvironment("SA_PASSWORD", "Your_password123")
                .WithEnvironment("MSSQL_PID", "Developer")
                .WithEnvironment("ACCEPT_EULA", "Y")
                .WithPortBinding(41433, 1433)
                .WithCleanUp(true)
                .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(1433))
                .Build();
        }

        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureTestServices(
                services =>
                {
                    services.AddDbContext<TDbContext>(options => options.UseSqlServer(_dbContainer.ConnectionString));
                });
        }

        async Task IAsyncLifetime.DisposeAsync()
        {
            await _dbContainer.DisposeAsync();
        }

        async Task IAsyncLifetime.InitializeAsync()
        {
            await _dbContainer.StartAsync();
        }
    }
}
`

Test class 

`
   public class ApiReportingTests : IClassFixture<ContainersFactory<Program, AppDbContext>>
    {
        private readonly AppDbContext _appDbContext;
        private readonly ContainersFactory<Program, AppDbContext> _factory;

        public ApiReportingTests(ContainersFactory<Program, AppDbContext> factory)
        {
            _factory = factory;

            using (IServiceScope scope = factory.Services.CreateScope())
            {
                _appDbContext = scope.ServiceProvider.GetService<AppDbContext>();
            }
        }

        [Fact]
        public async Task Test()
        {
            HttpClient httpClient = _factory.CreateClient();
        }
    }
`

When trying to run the tests I'm getting `Docker.DotNet.DockerImageNotFoundException`

Tried downgrading the version to 2.1.0 but still facing very simillar issues  as for 2.2.0

`Message: 
Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: ghcr.io/psanetra/ryuk:2021.12.20"}

  Stack Trace: 
<.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
IAsyncLifetime.InitializeAsync() line 72
`

### Relevant log output

```shell
Message: 
Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: testcontainers/ryuk:0.3.4"}


  Stack Trace: 
<.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
MsSqlTestcontainer.StartAsync(CancellationToken ct)
IAsyncLifetime.InitializeAsync() line 72
```

**Comment by HofmeisterAn** [comment]
I am a bit confused which version you use. The latest version is `2.3.0`. Can you please try `2.3.0` and append the log output?

**Comment by ghost** [comment]
> I am a bit confused which version you use. The latest version is `2.3.0`. Can you please try `2.3.0` and append the log output?

I've tried 2.1.0 , 2.2.0 and right now I've just tried 2.3.0 .

And I' getting

`
Message: 
Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: testcontainers/ryuk:0.3.4"}


  Stack Trace: 
<.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IDockerImage resourceReaperImage, IMount dockerSocket, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IDockerImage resourceReaperImage, IMount dockerSocket, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct)
ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
TestcontainersContainer.Create(CancellationToken ct)
TestcontainersContainer.StartAsync(CancellationToken ct)
MsSqlTestcontainer.StartAsync(CancellationToken ct)
IAsyncLifetime.InitializeAsync() line 72
`

This are my .csproj references 

`
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="6.0.10" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="xunit" Version="2.4.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="3.2.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture.Xunit2" Version="4.17.0" />
		<PackageReference Include="FluentAssertions" Version="6.8.0" />
		<PackageReference Include="Testcontainers" Version="2.3.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Api.Reporting\Api.Reporting.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="AutoFixture" />
		<Using Include="AutoFixture.Xunit2" />
		<Using Include="Xunit" />
	</ItemGroup>

</Project>

`

**Comment by HofmeisterAn** [comment]
Please append the log output. You will find the logs in the debug output window (running tests with the debug configuration). Does `docker pull testcontainers/ryuk:0.3.4` work?

**Comment by ghost** [comment]
> Please append the log output. You will find the logs in the debug output window (running tests with the debug configuration). Does `docker pull testcontainers/ryuk:0.3.4` work?

I've tried to pull the image using docker cli but it does not work

> Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.128:3128: connect: no > route to host

Trying to run tests in debug mode I only get this 

`
   Source: Api.Reporting.Tests.cs line 28
   Duration: 1 ms

  Message: 
    Docker.DotNet.DockerImageNotFoundException : Docker API responded with status code=NotFound, response={"message":"No such image: testcontainers/ryuk:0.3.4"}
    

  Stack Trace: 
    <.cctor>b__30_1(HttpStatusCode statusCode, String responseBody)
    DockerClient.HandleIfErrorResponseAsync(HttpStatusCode statusCode, HttpResponseMessage response, IEnumerable`1 handlers)
    DockerClient.MakeRequestAsync(IEnumerable`1 errorHandlers, HttpMethod method, String path, IQueryString queryString, IRequestContent body, IDictionary`2 headers, TimeSpan timeout, CancellationToken token)
    ContainerOperations.CreateContainerAsync(CreateContainerParameters parameters, CancellationToken cancellationToken)
    DockerContainerOperations.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
    TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
    TestcontainersContainer.Create(CancellationToken ct)
    TestcontainersContainer.StartAsync(CancellationToken ct)
    ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IDockerImage resourceReaperImage, IMount dockerSocket, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct)
    ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IDockerImage resourceReaperImage, IMount dockerSocket, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct)
    ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
    TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
    TestcontainersContainer.Create(CancellationToken ct)
    TestcontainersContainer.StartAsync(CancellationToken ct)
    MsSqlTestcontainer.StartAsync(CancellationToken ct)
    IAsyncLifetime.InitializeAsync() line 72
`

In the output window I don't see anything

**Comment by HofmeisterAn** [comment]
> In the output window I don't see anything

They appear in the IDE's debug window. However, your Docker environment is not able to pull the image at all.

    Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.128:3128: connect: no > route to host

Sounds like there is a proxy in between? Does it allow traffic to Docker Hub?

**Comment by ghost** [comment]
"Sounds like there is a proxy in between? Does it allow traffic to Docker Hub?"

Yes , I mean I could download other images like (mssql, rabbit, redis, elk ... )

**Comment by ghost** [comment]
I've managed to make this work, 
It looked that there was an issue with my docker.

Did the following in order to make it work 

1. updated docker 
2. removed networks with bridge drivers that were not in use.
