### ISSUE TITLE
[Enhancement]: Refactor the `IImage` properties (align with DSL)

### ISSUE THREAD

**Issue by HofmeisterAn** [testcontainers/testcontainers-dotnet#740]
### Problem

The `IImage` interface does not follow the correct naming conventions.

### Solution

The interface should use the following properties: `Registry`, `Repository`, `Tag`, `FullName`.

### Benefit

Align with the DSL.

### Alternatives

\-

### Would you like to help contributing this enhancement?

Yes

**Comment by jacobjmarks** [comment]
Has this been resolved with #729?

**Comment by HofmeisterAn** [comment]
No, it is something we still need to change. I have not touched it because it introduces breaking changes. To align with the Docker DSL we need to rename (adjust) the properties, e.g.

|  | Actual | Expected |
|---|---|---|
| Registry | - | myregistryhost:5000 |
| Repository | myregistryhost:5000/fedora | fedora/httpd |
| Name | httpd | - |
| Tag | version1.0 | version1.0 |
| GetHostname() | myregistryhost:5000 | - |

**Comment by jacobjmarks** [comment]
Happy to work on this if it's something you'd like to see done, despite the breaking changes.
