### ISSUE TITLE
Add Minio container

### ISSUE THREAD

**Issue by Sossenbinder** [testcontainers/testcontainers-dotnet#747]
Hello,

I'd like to propose adding a default container for Minio. I think given there is an Azurite Container already, it would be reasonable to also offer an S3-compatible storage for the AWS devs.

I already use throwaway minio instances in some integration tests of mine, so it definitely fits the idea of throwaway containers.

In case this is something you would be interested in, I could also offer to try to implement this myself - I've already checked out the repo, I might just need some hints on how to deal with the new structure (I've seen that there was a bigger change to module structure recently).

Let me know if this would be an addition you'd like to see.

**Comment by HofmeisterAn** [comment]
OC, sounds great 👍. I will publish the version `2.4.0` this week. This includes the preparation to publish modules as independent NuGet dependencies too - perfect timing (#732 and #730 are also waiting for it).

> I might just need some hints on how to deal with the new structure (I've seen that there was a bigger change to module structure recently).

Sure, I'm happy to help. After the release, I will work on an article about how to create and implement a module for Testcontainers for .NET. `2.4.0` includes a .NET [template](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src/Templates) to scaffold modules too. We can discuss questions in the meantime either here or in Slack.

**Comment by Sossenbinder** [comment]
Great - Looking forward to it!

**Comment by HofmeisterAn** [comment]
I know some developers are waiting for the article or documentation about how to add a new module to Testcontainers for .NET. It is not finished yet, we are polishing it. If you would like to play around with modules in the meantime you can take a look at #757 (the interesting part is the `MsSqlBuilder` class). To scaffold a module simply run:

```console
git clone --branch develop git@github.com:testcontainers/testcontainers-dotnet.git
cd ./testcontainers-dotnet/
dotnet new --install ./src/Templates
dotnet new tcm --name PostgreSql --official-module true --output ./src
dotnet sln add ./src/Testcontainers.PostgreSql/Testcontainers.PostgreSql.csproj
```
