### ISSUE TITLE
Support TimescaleDb

### ISSUE THREAD

**Issue by rafaelKu** [testcontainers/testcontainers-dotnet#749]
I would like to see a predefined TimescaleDbTestcontainer. 

In general, there is not a big difference as using the PostgreSqlTestcontainer. But at the moment we need to catch the exception when we are creating the hypertable and assert to this specififc exception. All the other repository methods are also easy to test with the PostgreSqlTestcontainer.

I think [TimescaleDb](https://www.timescale.com/) is commonly used, and we almost decided against testcontainers because there is no support. Therefore, I think it would be a useful feature and not too much work for you.

Thanks and best regards

**Comment by HofmeisterAn** [comment]
Sure, same applies here as for: https://github.com/testcontainers/testcontainers-dotnet/issues/747#issuecomment-1409262016. Would you like to help contributing a Timescale container implementation?

**Comment by eddumelendez** [comment]
PostgreSQL implementation should be used for Timescale. At least, there is no difference in the configuration besides just use the proper image. The same applies to PostGIS

**Comment by HofmeisterAn** [comment]
Considering that it is only necessary to override the PostgreSQL module image, I do not think we need a dedicated module for Timescale as well. Thank you, @eddumelendez.

You can override the image for every builder e.g.:

```csharp
_ = new PostgreSqlBuilder().WithImage("timescale/timescaledb:latest-pg15").Build();
```
