### ISSUE TITLE
[Bug]: 2.4.0 contains breaking changes

### ISSUE THREAD

**Issue by pellared** [testcontainers/testcontainers-dotnet#751]
### Testcontainers version

2.4.0

### Using the latest Testcontainers version?

Yes

### Host OS

n/a

### Host arch

n/a

### .NET version

n/a

### Docker version

```shell
n/a
```

### Docker info

```shell
n/a
```

### What happened?

The version for `2.4.0` release should be `3.0.0`. This is breaking the NuGet (and SemVer) versioning rules: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-basics

### Additional information

I think that the package should be released as `3.0.0` to avoid confusion as well as [unlist](https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages) the `2.4.0` package.

**Comment by pellared** [comment]
I have not seen 

> we have flagged all upcoming breaking changes as obsolete

We fail the build when there is a warning. Sorry for false negative.

**Comment by pellared** [comment]
Reopening as e.g. the change of `IWaitUntil` is breaking.

**Comment by HofmeisterAn** [comment]
> Reopening as e.g. the change of `IWaitUntil` is breaking.

Yes, it is mentioned [here](https://github.com/testcontainers/testcontainers-dotnet/releases/tag/2.4.0). We will keep the version and not unlist it. The behavior has not changed, it was only renamed.
