### ISSUE TITLE
Return support for explicit image registry authentication

### ISSUE THREAD

**Issue by chmely** [testcontainers/testcontainers-dotnet#755]
**Is your feature request related to a problem? Please describe.**
In my CI pipeline I'd like to pass authentication data when creating a container. At the moment the authentication data needs to be read from `.docker/config.json` and there doesn't seem to be any other way. We obtain the AWS ECR authentication token programmatically through [AWSSDK.ECR](https://www.nuget.org/packages/AWSSDK.ECR) nuget package when our CI tests start.

Interestingly, the `Docker.DotNet` library has a support for this, so you can do e.g.
```
var c = new Docker.DotNet.DockerClientConfiguration(new Uri("tcp://localhost:2375")).CreateClient();
var i = c.Images.CreateImageAsync(
    new Docker.DotNet.Models.ImagesCreateParameters() { FromImage = "xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/myimage", Tag = "latest" },
    new Docker.DotNet.Models.AuthConfig { ServerAddress = "xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com", Username = "AWS", Password = ecrAuthorizationToken },
    ....);
```
the above works perfectly fine, it pulls the image.

However, there is no way to pass such authentication data through Testcontainers, the `registryAuthenticationProvider` is hardcoded [here](https://github.com/testcontainers/testcontainers-dotnet/blob/3f5755124e1aeb419fbb3bf3c96487f501117ad9/src/Testcontainers/Clients/TestcontainersClient.cs#L59)

**Describe the solution you'd like**
I think it would be nice to have the ability to pass an instance of `IDockerRegistryAuthenticationProvider` to the builder, something like `.WithCustomRegistryAuthentication(IDockerRegistryAuthenticationProvider authProvider)`

**Describe alternatives you've considered**
I could manipulate/update the `.docker/config.json` with the password when the tests start, but I found it cumbersome, why it can't be done directly in the code?

**Comment by HofmeisterAn** [comment]
> why it can't be done directly in the code?

Usually, it is preferred or kind of a best practice to login or set the credentials (`config.json`) in a previous pipeline step. Setting the credentials in the code will likely lead to issues running the tests on different machines (like developer or CI environments).

Testcontainers for .NET supports the [GitLab CI](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#determine-your-docker_auth_config-data) `DOCKER_AUTH_CONFIG` environment variable. Basically, it is an environment variable, that holds the content of the `config.json`. Can you export the credentials to this environment variable during runtime? _Note: The credentials are cached. You need to export it befor pulling the first image._

**Comment by chmely** [comment]
Well, if I have to construct a JSON content for the `DOCKER_AUTH_CONFIG` env variable I can just as well update the config file directly. But I still think it would still be nice to have that option. If there is already a support for `DOCKER_AUTH_CONFIG` option we could just as well have a builder method, so instead of having to build a JSON and assign to env variable we could simply pass the login credentials to a method.

One thing is during CI, there I can make sure I do an explicit login to the ECR as you suggested as a best practice, but when running the tests on e.g. developer machines it's easy to forget to login to the repo and `Docker.DotNet.Client.Images.CreateImageAsync` doesn't throw an exception when authentication fails, so the code [here](https://github.com/testcontainers/testcontainers-dotnet/blob/741a948d9d72517bafb485176e7b00a226d265c3/src/Testcontainers/Clients/DockerImageOperations.cs#L79) happily continues giving the impression that the latest image is being used if, like in our case, we run with `.WithImagePullPolicy(PullPolicy.Always)` and that could cause unexpected test failures.

Sure, I can do an explicit pull by using the Docker.DotNet directly before running our tests
```
var c = new Docker.DotNet.DockerClientConfiguration(new Uri("tcp://localhost:2375")).CreateClient();
var i = c.Images.CreateImageAsync(
    new Docker.DotNet.Models.ImagesCreateParameters() { FromImage = "xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/myimage", Tag = "latest" },
    new Docker.DotNet.Models.AuthConfig { ServerAddress = "xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com", Username = "AWS", Password = ecrAuthorizationToken },
    ....);
```

but I just think it'd be much cleaner if I could simply pass the auth data into the Testcontainer builder, is all.

**Comment by HofmeisterAn** [comment]
> `Docker.DotNet.Client.Images.CreateImageAsync` doesn't throw an exception when authentication fails, so the code [here](https://github.com/testcontainers/testcontainers-dotnet/blob/741a948d9d72517bafb485176e7b00a226d265c3/src/Testcontainers/Clients/DockerImageOperations.cs#L79) happily continues giving the impression that the latest image is being used if, like in our case, we run with `.WithImagePullPolicy(PullPolicy.Always)` and that could cause unexpected test failures.

I think that got fixed with https://github.com/dotnet/Docker.DotNet/pull/590. Unfortunately, there is no new release yet.

In fact, the feature you are requesting (kind of) was already part of a [previous version](https://github.com/testcontainers/testcontainers-dotnet/blob/53d37fa25ca6523e4f0fc47feee1c5f5f739715c/src/Testcontainers/Builders/TestcontainersBuilder.cs#L266-L269C6) of Testcontainers for .NET. It got removed in the process of the language alignment and  the support of Docker's credential mechanism.

May I ask which CI pipeline you are using? Can't you use the `docker-credential-ecr-login` credential helper?

**Comment by chmely** [comment]
We use AppVeyor. But as I said, the CI is not a problem, there we can use aws CLI to login to the repo before running the tests. This is just to simplify the setup for developers and testers, firstly the `docker-credential-ecr-login` doesn't seem to work, I am getting `Error saving credentials: error storing credentials - err: exit status 1, out: 'not implemented'` and I don't have time to investigate what it means, second, it just creates a dependency on yet another tool/component that needs to be approved, installed, configured and maintained on dev machines. 
If we could have that method back that would authenticate during the test run itself it would imo simplify the way we could write those tests, the tests would be self-contained without dependencies on either other tools or devs/testers having to execute some steps before running the tests, etc. They'd just simply run the test and the code would take care of everything.
Also the code would be self-documenting, exactly describing what it's doing.

**Comment by HofmeisterAn** [comment]
I have spoken with the other Testcontainers maintainers, and we have decided not to support the suggested API due to security concerns. It is too easy to expose credentials with this API, and it goes against the recommended and widely supported approach for authenticating and logging into a Docker registry.

The suggested approach above is defacto the standard, as it is recommended by [Docker](https://docs.docker.com/engine/reference/commandline/login/#credential-helpers) and widely supported by many different software that interact with Docker registries. We believe it is important to follow the best practices outlined by Docker and the wider community.
