### ISSUE TITLE
Add webdriver container

### ISSUE THREAD

**Issue by refaeli-io** [testcontainers/testcontainers-dotnet#762]
**Is your feature request related to a problem? Please describe.**
Hi with the java library of test containers, there is the option to add containers of Webdriver:
https://www.testcontainers.org/modules/webdriver_containers/
I want the same option with dotnet.

I would like to help develop this feature because I am an automation developer with selenium and dotnet that a lot about the DevOps world (see my projects )

how we can start developing this? 
Collaborate with me :) I will like to help

**Comment by HofmeisterAn** [comment]
Thanks for reaching out! We appreciate your interest in Testcontainers for Java Webdriver container and agree that equivalent support for .NET would be a great addition. With the latest .NET release, the ability to implement independent modules opens up the possibility for us to implement the Webdriver container for .NET as well. While it might not be an easy task, we would be more than happy to accept a contribution in this regard. I would suggest starting by getting familiar with the Java implementation and the new [module](https://www.atomicjar.com/2023/02/how-to-create-a-testcontainers-for-dotnet-module/) API in .NET. I am available to provide any assistance needed.

**Comment by refaeli-io** [comment]
@HofmeisterAn 
Thanks :sunglasses:

**Comment by ShaharM7** [comment]
The code is merged 😀  :confetti_ball:
This issue can be close :tada:

**Comment by refaeli-io** [comment]
The code is merged 😀 🎊
This issue can be closed 🎉
