### ISSUE TITLE
[Bug]: Database does not get created

### ISSUE THREAD

**Issue by petar-maletic** [testcontainers/testcontainers-dotnet#786]
### Testcontainers version

2.4.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

7.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 50.09GiB
 Name: docker-desktop
 ID: 3ZJD:EC2O:PSOJ:E2Q3:WTG6:W7G5:6KRW:ZKY5:PI3Y:CCXD:X2FS:546I
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

When I use any other database name except "master", nothing gets created, I've tried following WeatherForecast test example, everything works ok, but 

`IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = '{Database}')
          BEGIN
            CREATE DATABASE [{Database}];
          END;`

simply does nothing for me. I've tried checking the DB while container is up, only master db and other sys databases get created, but not the one I've specified (using Database propery), so of course my connection string is also invalid.

**Comment by HofmeisterAn** [comment]
> When I use any other database name except "master", nothing gets created, I've tried following WeatherForecast test example, everything works ok, but

The WeatherForecast example creates a custom database:

https://github.com/testcontainers/testcontainers-dotnet/blob/fe9f55a84341b57f5e054e631043f590dd2cc74c/examples/WeatherForecast/src/WeatherForecast/DatabaseContainerConfiguration.cs#L11-L15

Running `SELECT name FROM sys.databases;` returns:

```
name                                
------------------------------------
master                              
tempdb                              
model                               
msdb                                
f787e847-ed33-4853-b323-231089789a5c
```

The connection string is:

    Server=127.0.0.1,56279;Database=f787e847-ed33-4853-b323-231089789a5c;User Id=sa;Password=39f1665e-3515-431a-be3e-c008f31bcc91;

I do not see any issue here. Can you please share the builder configuration?

_Notice_: Initially, the new module API will not introduce any additional features to the Docker image. For instance, if the image does not have the capability to support different database names, we will not implement this functionality in the first instance. It is the responsibility of the user.

**Comment by HofmeisterAn** [comment]
We haven't received any response from you lately, and I wanted to check if you are still having issues setting up the container?

**Comment by HofmeisterAn** [comment]
I will close this issue since we got no response.
