### ISSUE TITLE
[Bug]: Working with MsSql Container getting `Initialization has been cancelled` exception

### ISSUE THREAD

**Issue by iozcelik** [testcontainers/testcontainers-dotnet#794]
### Testcontainers version

2.4.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x64

### .NET version

7.0.3

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 17
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.23GiB
 Name: docker-desktop
 ID: 4ISY:LGCG:5LYK:ITFR:XEMK:7OQS:4G7R:YW2W:VZJV:OECG:XLT3:GL6G
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

I try to create a simple sample test. However I get an exception. `DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.`

Docker logs not shown much information:
```
PS C:\Users\ismai> docker logs --follow testcontainers-ryuk-2780f9f8-55e4-4a1d-8d3a-efdc05c5a2ba
2023/02/19 19:37:20 Pinging Docker...
2023/02/19 19:37:20 Docker daemon is available!
2023/02/19 19:37:20 Starting on port 8080...
2023/02/19 19:37:20 Started!
panic: Timed out waiting for the first connection

goroutine 1 [running]:
main.main()
        /go/src/github.com/testcontainers/moby-ryuk/main.go:53 +0x4da
```

### Additional information

My all test code is here.

```csharp
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;
using Microsoft.Data.SqlClient;

namespace TestProject1;

public sealed class MsSqlTest : IAsyncLifetime {
    private static readonly ContainerBuilder<MsSqlTestcontainer> testcontainersBuilder = new ContainerBuilder<MsSqlTestcontainer>();
    private static readonly MsSqlTestcontainer customUserEntityDatabase = testcontainersBuilder.WithDatabase(new MsSqlTestcontainerConfiguration {
        Password = "localdevpassword#123",
        Database = "TestDatabase"
    }).WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(1433))
            .Build();

    public async Task DisposeAsync() {
        await customUserEntityDatabase.DisposeAsync();
    }

    public async Task InitializeAsync() {
        await customUserEntityDatabase.StartAsync();
    }

    [Fact]
    public async Task ShouldUseDefaultImageWhenImageIsNotSpecifiedAsync() {
        await InitContainerTestAsync();
    }

    private async Task InitContainerTestAsync() {
        using (var connection = new SqlConnection($"{customUserEntityDatabase.ConnectionString}TrustServerCertificate=true;")) {

            connection.Open();

            using (SqlCommand command = new SqlCommand("SELECT '1'", connection)) {
                using (SqlDataReader reader = command.ExecuteReader()) {
                    while (reader.Read()) {
                        Console.WriteLine("{0}", reader.GetString(0));
                    }
                }
            }
        }
    }
}
```

**Comment by HofmeisterAn** [comment]
Can you please take a look if you run into the excluded port ranges: https://github.com/docker/for-win/issues/3171?

**Comment by iozcelik** [comment]
I already check that issue. Also, I look java side. Actually I cannot pull testcontainers-ryuk manually.

**Comment by HofmeisterAn** [comment]
> Actually I cannot pull testcontainers-ryuk manually.

`docker pull testcontainers/ryuk` does not work? Which error do you get? That sounds like a more general issue.

**Comment by iozcelik** [comment]
Console output is:

```
C:\Windows\System32>docker pull testcontainers/ryuk
Using default tag: latest
latest: Pulling from testcontainers/ryuk
31603596830f: Pull complete
c307511530fc: Pull complete
6d9b4cc4a42f: Pull complete
Digest: sha256:b2762871bff62df9bfcec62609da821803a575e06d74aa7ce1654ded208cc7c5
Status: Downloaded newer image for testcontainers/ryuk:latest
docker.io/testcontainers/ryuk:latest

C:\Windows\System32>docker run testcontainers/ryuk
2023/02/20 10:27:41 Pinging Docker...
panic: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

goroutine 1 [running]:
main.main()
        /go/src/github.com/testcontainers/moby-ryuk/main.go:36 +0x457
```

I use Windows 11...

**Comment by HofmeisterAn** [comment]
Can you share `docker context ls` please? Looks really weird. Ryuk cannot mount the Docker daemon socket, which worked on your previous run.

**Comment by HofmeisterAn** [comment]
You cannot run `docker run testcontainers/ryuk`, see [usage](https://github.com/testcontainers/moby-ryuk#usage). Testcontainers can start the Ryuk container, but cannot connect to it. Can you please share `netsh interface ipv4 show excludedportrange protocol=tcp` incl. the host port Docker assigns to the container.

**Comment by iozcelik** [comment]
Command result:

```
C:\Windows\System32>netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
        80          80
      8080        8080     *
      8884        8884
     50000       50059     *
     50080       50080
     50443       50443

* - Administered port exclusions.
```

<img width="1526" alt="image" src="https://user-images.githubusercontent.com/10682780/220098863-f8351fe1-801b-4ed6-ada4-7412f824da91.png">

After one minute, it is gone.

**Comment by HofmeisterAn** [comment]
This looks odd, the container has no port mapping 🤔. Can you add the container inspect (`docker inspect ${container_id}`) please? Can you try version `2.3.0`? We added the following two lines to `2.4.0`:

https://github.com/testcontainers/testcontainers-dotnet/blob/d3ae00f3b656df0ea7d27f38b1cca61eb8344a70/src/Testcontainers/Builders/ContainerBuilder%603.cs#L159-L160

If you are using the develop branch, you can also comment out these two lines.

**Comment by iozcelik** [comment]
<img width="1604" alt="image" src="https://user-images.githubusercontent.com/10682780/220114986-d6cf09e6-535d-43b9-a01b-39c1336b7691.png">
With `2.3.0` it is working expected.

**Comment by HofmeisterAn** [comment]
Could you please test the `develop` branch without the two lines mentioned above? It would be really helpful in understanding whether this is a regression or not. I am unable to reproduce the issue. Thank you for your assistance.

**Comment by iozcelik** [comment]
I test with develop branch and both cases are work well with comment and without comment that 2 lines. However with `2.4.0`, I get same error.

**Comment by HofmeisterAn** [comment]
Interesting, I do not want to bother you, but can you test the following commit: eaa6068162880b1586d8576e2bf0c6b44db080d3 😬? As I mentioned earlier, unfortunately, I am unable to reproduce it.

**Comment by HofmeisterAn** [comment]
We haven't received any response from you lately, and I wanted to check if you are still having issues with Ryuk?

**Comment by bealtis** [comment]
Hi, I had the same problem and got it working with version `2.3.0`. 
But I had to manually pull the required DB Images `mcr.microsoft.com/mssql/server:2017-CU28-ubuntu-16.04` from Docker.

**Comment by HofmeisterAn** [comment]
> Hi, I had the same problem and got it working with version `2.3.0`.

Which version? `2.4.0`? Which Docker version? Could you test `develop` instead?

> But I had to manually pull the required DB Images `mcr.microsoft.com/mssql/server:2017-CU28-ubuntu-16.04` from Docker.

This should not be necessary.

**Comment by iozcelik** [comment]
> We haven't received any response from you lately, and I wanted to check if you are still having issues with Ryuk?

Yes, still have problem. I use 2.4 version.

**Comment by HofmeisterAn** [comment]
Hm, based on the response it is very difficult for me to triage the issue 🤔.

**Comment by janwiebe-glasbergen** [comment]
I encountered the same issue.
It looks like it's a timing related issue, as the identical code worked on faster machines. 

For me using the develop version solves the issue.

Could you release a patch version for 2.4.0?

**Comment by HofmeisterAn** [comment]
> Could you release a patch version for 2.4.0?

We plan to publish a major release later next week.

**Comment by HofmeisterAn** [comment]
Since we now have the new release, I will close this issue. Let's see if it reappears 🤞.
