### ISSUE TITLE
[Bug]: WithCleanup(true) does not properly work

### ISSUE THREAD

**Issue by ohadvano** [testcontainers/testcontainers-dotnet#795]
### Testcontainers version

2.4.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x64

### .NET version

7.0.100

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:36:18 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.3 (96739)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.79.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.34GiB
 Name: docker-desktop
 ID: FYG7:2I2H:LWWB:Y4VE:53I3:WKTA:64ON:JMU6:IBXY:Y6EG:UFDN:3KBU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

Configuring a builder for a container with "WithCleanup(true)", does not fully delete the resource.
The error happens when running a test twice. At the first run, the container is started and attached to a specific IP in an associated network (attached with "WithNetwork(network)").
After the test finishes, it starts again with the same setup, only this time starting the container fails, with the following error:
"Docker.DotNet.DockerApiException : Docker API responded with status code=Forbidden, response={"message":"Pool overlaps with other one on this address space"}".

The only way I found to fix this, is manually calling "container.DeleteAsync()" after the test finish, that way the second iteration works as expected.

**Comment by HofmeisterAn** [comment]
> After the test finishes, it starts again with the same setup

What does that mean? According to the error message it sounds you create a resource with the same (static) configuration again:

    Pool overlaps with other one on this address space

Can you please share your test configuration?

**Comment by ohadvano** [comment]
What part of the configuration do you want me to share?
And yes, I am indeed running the same resources again with the same IPs, but I would expect it to work since I expect it to clean up on test finish. Only after adding "DeleteAsync" it really deletes everything

**Comment by HofmeisterAn** [comment]
> What part of the configuration do you want me to share?

Your test code.

> And yes, I am indeed running the same resources again with the same IPs, but I would expect it to work since I expect it to clean

The Resource Reaper cleans up the resources after the test processes have been finished. If you would like to clean up during the tests, it is necessary to call `DisposeAsync()` or `DeleteAsync()`.

**Comment by ohadvano** [comment]
> The Resource Reaper cleans up the resources after the test processes have been finished. If you would like to clean up during the tests, it is necessary to call `DisposeAsync()` or `DeleteAsync()`.

I guess that explains the behavior then. By the time the resource reaper really cleans up the resources, the new test starts and tries to bind the container to the same IP as in the previous test run, although the network resources from previous run have not fully cleaned up. Does it make sense that this is what's happening?

Is there a way to block the test until the resource reaper finishes its action?

**Comment by HofmeisterAn** [comment]
> Does it make sense that this is what's happening?

It is possible - yes, but since I have not seen the test code, I only can guess.

> Is there a way to block the test until the resource reaper finishes its action?

Do you use the same network name? I would assume different network names will work.

**Comment by ohadvano** [comment]
Yes that would solve this, but it adds some code that I was hoping not to maintain, because it's actually not just the names it would also require me to adjust the subnet address and IPs. Is there a way to wait for the Resource Reaper to finish before the test finishes?

**Comment by HofmeisterAn** [comment]
> Is there a way to wait for the Resource Reaper to finish before the test finishes?

No.

We consider it a bad practice to use fixed names (values) for resources. This usually indicates poor design. Depending on fixed names, port bindings, etc. can result in unreliable tests.

**Comment by ohadvano** [comment]
Well, not always it's possible to modify these stuff just for testing, as it might require modifying production code. Can we consider this as a feature request?

**Comment by HofmeisterAn** [comment]
> Can we consider this as a feature request?

The Resource Reaper ([moby-ryuk](https://github.com/testcontainers/moby-ryuk)) container has a graceful period to reconnect, and if the connection is dropped for more than 60 seconds (which indicates that the tests are finished), it starts to clean up the resources. The behavior you are experiencing is by design.

That said, you may want to look into using the [network alias](https://dotnet.testcontainers.org/api/create_docker_network/) feature, which allows you to access containers via their names rather than their IP addresses. 

If you still choose to rely on static names, configurations, etc. and do not follow the best practices, you will need to take care of the cleanup by yourself.

**Comment by ohadvano** [comment]
Due to internal business logic, I am unable to use network alias where the problem is caused in.
1. Can you please refer me to a doc that explains on those best practices?
2. Would it not be reasonable to consider an "on-demand" cleanup by the RR?

**Comment by HofmeisterAn** [comment]
> 1. Can you please refer me to a doc that explains on those best practices?

The link above shows how to set up the network configuration.

> 2. Would it not be reasonable to consider an "on-demand" cleanup by the RR?

As I said, you can [disable](https://dotnet.testcontainers.org/custom_configuration/) Ryuk and implement your own logic as you suggested. However, I would like to note that disabling Ryuk may result in leaving resources behind and could potentially mess up the CI and development environment. Ryuk is the only way to [cleanup](https://dotnet.testcontainers.org/api/resource-reaper/) the environment reliable. Maybe the reusable feature will help in the future, but that is not yet part of TC for .NET.

**Comment by ohadvano** [comment]
I wouldn't want to disable Ryun. As you said it might mess the environment and I would like to make use of it to clean up my resources. Only thing I would expect is some way make it clean up on-demand, even with a static method "await Ryuk.CleanupAsync()" or something similar, instead of manually implementing this cleanup logic.
I could try helping implement this, but currently I'm trying to understand if it's a legitimate feature request. Is there a reason why it couldn't be supported?

**Comment by HofmeisterAn** [comment]
Ryuk runs as an independent container ("out of process"). We start it once and never touch it again.

If you'd like, I can take a look at your test and see if there's anything that can be improved in your setup.

I spoke with the other TC maintainers too, and we don't believe that this is a missing feature. From what we can see, it's working as intended and expected, so we don't have any plans to change its behavior.

**Comment by ohadvano** [comment]
Thanks for the good intentions, I believe there would be ways to make this work with some workarounds. I'm just trying to avoid them with feature that to me sounds trivial. I'm not trying to argue here, but I think it worths a second thought merely because adding such feature would not change current behavior, only enable a non-conflicting option to invoke the cleanup. I'm not a maintainer of this repository, but if you seek the perspective of a user - this is a desired feature.

**Comment by HofmeisterAn** [comment]
> I would expect is some way make it clean up on-demand, even with a static method "await Ryuk.CleanupAsync()"

You can clean up individual resources by calling `DisposeAsync()` or `DeleteAsync()` on your test's teardown.

Calling a cleanup method from the test process will never work reliable. If the test process dies or the test throws an exception (while cleaning up), your resources will remain. Even a member like `Ryuk.CleanupAsync()` will run into this issue.

We truly appreciate when users take the time to share their perspectives and suggestions with us. We always strive to find solutions and help our users as much as possible. We take user feedback seriously and discuss feature requests like this with other maintainers to get different perspectives from other languages. We acknowledge that your feature request is desired by you as a user, but after careful consideration, we've concluded that it doesn't fit into how TC (moby-ryuk) currently works.

I hope that you'll continue to use TC and that we can continue to work together to improve it. If you have any further suggestions or feedback, please feel free to share them with us.
