### ISSUE TITLE
[Enhancement]: Better method for sending multiple files to the conainer

### ISSUE THREAD

**Issue by dgiddins** [testcontainers/testcontainers-dotnet#811]
### Problem

`.WithResourceMapping()` Allows us to send files to the container. When there are many files to be sent calling `StartAsync()` on the container can timeout. Probably as files are sent in parallel https://github.com/testcontainers/testcontainers-dotnet/blob/6688b92d217e710a773e87126fc98c78b27de253/src/Testcontainers/Clients/TestcontainersClient.cs#L294-L298

### Solution

To allow sending of archives that are then automatically unzipped in the container. Or this could be implemented as providing a list of files to the container builder so that the builder creates the archive and then unzips into a specified target directory.

https://github.com/testcontainers/testcontainers-dotnet/blob/6688b92d217e710a773e87126fc98c78b27de253/src/Testcontainers/Clients/TestcontainersClient.cs#L166-L206

### Benefit

When using sqitch for managing changes to database schemas the schema repo can grow very large resulting in many files needing to be moved.

### Alternatives

Using volume mounts which is not advised.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
To create a Docker image, a lot of similar code is necessary. I think we can reuse and restructure a lot. [This](https://github.com/testcontainers/testcontainers-dotnet/blob/a1e14cbf8002aea59b3ee0a9fcb4130fdd578792/src/Testcontainers/Images/DockerfileArchive.cs#L82-L120) part implements `ITarArchive` to create a tarball of the Docker image build context, which includes all files and subdirectories of a directory.

I believe we need to overload [CopyFileAsync](https://github.com/testcontainers/testcontainers-dotnet/blob/a1e14cbf8002aea59b3ee0a9fcb4130fdd578792/src/Testcontainers/Clients/TestcontainersClient.cs#L166) with a source and target paths and determine whether the source path is a directory or not. Based on the `FileSystemInfo`, we can construct the tarball and pass it to the Docker endpoint.
