### ISSUE TITLE
[Bug]: Docker.DotNet breaking change

### ISSUE THREAD

**Issue by lbruun** [testcontainers/testcontainers-dotnet#814]
### Testcontainers version

2.4

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

X86

### .NET version

7.0

### Docker version

```shell
n/a
```

### Docker info

```shell
n/a
```

### What happened?

The folks at Docker has introduced some breaking change between v3.125.13 and v.3.125.12 of the [Docker DotNet library](https://github.com/dotnet/Docker.DotNet).

For Testcontainers, this result in the following error on `ContainerBuilder().Build()`:

```text
error CS0012: The type 'CreateContainerParameters' is defined in an assembly that is not referenced. 
You must add a reference to assembly 'Docker.DotNet, Version=3.125.0.0, Culture=neutral, PublicKeyToken=null'. [
```

Solution at the moment is to explicitly reference NuGet package  `Docker.DotNet`  in your project and pin it to version  `3.125.12` .

Logging it here for information even though it is likely something that needs to be fixed in the Docker.DotNet project.

**Comment by HofmeisterAn** [comment]
How to you get `3.125.13`? Do you reference it explicit?

**Comment by lbruun** [comment]
> How to you get `3.125.13`? Do you reference it explicit?

No, it is TestContainers which uses an "at-least-version-X" dependency on `Docker.DotNet`. (pros and cons on that, I guess)

https://www.nuget.org/packages/Testcontainers/2.4.0#dependencies-body-tab

**Comment by HofmeisterAn** [comment]
AFAIK, if you do not override the transitive dependency it restores `3.125.12`. I am wondering how you get the version `3.125.13` automatically. Did you run an upgrade? My test project restores `3.125.12`.

**Comment by lbruun** [comment]
Using Paket. Don't know if that makes a difference.

In any case, as per the screenshot bellow, NuGet seems to think that it is `>=`  :
![image](https://user-images.githubusercontent.com/32431476/222436758-6b26ed7b-09b0-4eae-bca7-ff9601c5644d.png)

so, I don't think Paket is doing anything wrong when it resolves that dependency to `3.125.13`.

Or ?

**Comment by HofmeisterAn** [comment]
I know what you are referring to, but I do not think `nuget` nor `dotnet restore` automatically restores the latest patch version. If you build a project with `2.4.0` you still should get `3.125.12` expect you override the version by yourself. Nevertheless, there will be a new release soon that includes `3.125.13`.

**Comment by lbruun** [comment]
Ahh. I think it is because Paket defaults to a **_highest matching version_** strategy, while NuGet defaults to a **_lowest matching strategy_** version.

More here: https://fsprojects.github.io/Paket/dependencies-file.html#Resolver-strategy-for-transitive-dependencies

In conclusion, I think the problem exists only for those using Paket .. or another dependency manager using the max strategy.

**Comment by HofmeisterAn** [comment]
Docker.DotNet signs now the assembly with a strong name. That's probably the reason why you see the message above. We will ship a new release soon. Please pin the version in the meantime. Anything something I would recommend. Can we close the issue?

**Comment by lbruun** [comment]
Thanks. Much appreciated. Nothing more that can be done here.
