### ISSUE TITLE
[Enhancement]: `ImageFromDockerfileBuilder` cannot pull from private registries

### ISSUE THREAD

**Issue by HofmeisterAn** [testcontainers/testcontainers-dotnet#824]
### Problem

The implementation of `ImageFromDockerfileBuilder` does not support building images from private registries. It is unable to read dependent images from the Dockerfile and collect the Docker registry authentication credentials required to pull the images.

### Solution

Retrieve the dependent Docker images from the Dockerfile (resolving build arguments too) and pull the images with the private registry authentication credentials.

### Benefit

Building images from private registries.

### Alternatives

\-

### Would you like to help contributing this enhancement?

Yes

**Comment by jdtempleton** [comment]
@HofmeisterAn I think am running up against this in some work I am doing where my `Dockerfile` looks like this:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
# ... brevity

FROM private-registry/custom-build-image:latest AS build
# ... brevity

FROM build AS publish
# ... brevity

FROM base AS final
# ... brevity
```

The `build` stage uses a custom image we have on a private registry. 

If you haven't started working on this and are still looking for someone to contribute, I may be interested in doing this if you have some ideas on what would need to be implemented to handle this.

**Comment by HofmeisterAn** [comment]
👋 as far as I know, no one is working on it. I think, we should move the following part to the implementation of `DockerImageOperations` in order to retrieve credentials for pulling or building images (and share the code base). Here is the specific code block we need to adjust:

https://github.com/testcontainers/testcontainers-dotnet/blob/90a300675660f6109e68ab61ea48de4b232936a7/src/Testcontainers/Clients/TestcontainersClient.cs#L282-L292

After that, we can read the images from the Dockerfile (specifically, the lines that begin with `FROM`) and pull those images in advance after this code block:

https://github.com/testcontainers/testcontainers-dotnet/blob/90a300675660f6109e68ab61ea48de4b232936a7/src/Testcontainers/Clients/DockerImageOperations.cs#L95

Your contribution would be greatly appreciated.

**Comment by donioe** [comment]
any new about it ?
or a workaround?

**Comment by HofmeisterAn** [comment]
No, the feature has not been implemented yet. However, you can obtain the image, for example, by using the CLI before running the tests.
