### ISSUE TITLE
[Enhancement]: Support identitytoken based authentication (OAuth2)

### ISSUE THREAD

**Issue by lbruun** [testcontainers/testcontainers-dotnet#841]
### Problem

Some containers registries use OAuth2 protocol for authentication. For example Azure Container Registry. 
After obtaining such credentials, Docker's `config.json` file look something like this:

```json
{
    "auths": {
        "myprivateregistry.azurecr.io": {
            "auth": "MDAwMDAwMDAtMDAwMC0wMDAwLTAwMDAtMDAwMDAwMDAwMDAwOg==",
            "identitytoken": "gwHEWT356ASfg....eUWR"
        }
    }
}
```
This is a use-case which testcontainers-dotnet cannot handle at the moment. 

With the above, testcontainers-dotnet will produce the following exception:
```text
Docker.DotNet.DockerApiException : Docker API responded with status code=InternalServerError, response=
{"message":"Head \"https://myprivateregistry.azurecr.io/v2/myapp/manifests/latest\": 
unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."}
```

This is because testcontainers-dotnet completely ignores the `identitytoken`. It solely looks at the `auth` value and attempts to extract username/password from that.  In the above case the username is `00000000-0000-0000-0000-000000000000` and the password is empty string. It will use those values for authentication which will of course fail.
  
Note: The above config file works with the Docker CLI, but doesn't work with testcontainers-dotnet.

### Solution

Use the `identitytoken` value if present. Only try to extract username/password from the `auth` property if the `identitytoken` is _not_ present.

See https://docs.docker.com/engine/api/v1.42/#section/Authentication

The fix is trivial as Docker.DotNet library has full support for this use-case.

### Benefit

Support for Azure Container Registry.
(especially from a CI pipeline)

### Alternatives

No known workarounds.

It would actually work as-is if the CI pipeline had a credstore available, because testcontainers-dotnet actually [already support this use-case with identitytoken](https://github.com/testcontainers/testcontainers-dotnet/blob/581a3cd85cb2b9b33b2550b6a82bf4b3913677ce/src/Testcontainers/Configurations/AuthConfigs/DockerRegistryAuthenticationConfiguration.cs#L41). However, CI workflows typically do not have such facility available, hence the `docker login` command will put the identitytoken directly in the config file.

### Would you like to help contributing this enhancement?

Yes

**Comment by lbruun** [comment]
Created PR #842  as a proposed fix.

**Comment by HofmeisterAn** [comment]
May I ask in which CI environment you are running?

**Comment by lbruun** [comment]
> May I ask in which CI environment you are running?

GitHub.

**Comment by HofmeisterAn** [comment]
Why don't you use the Docker login [action](https://github.com/docker/login-action#azure-container-registry-acr)?

**Comment by lyager** [comment]
AFAIK, when having the Docker Registry in Azure, the way to login is with `az acr`, which leaves you with the identitytoken Dockers config.json file?

**Comment by lbruun** [comment]
We can try the Docker login action.

We are currently doing it like this in the GitHub workflow:

1. First a general login to Azure using the [AZ-login action](https://github.com/Azure/login).
2. Then an `az acr login` command.

I would guess that the [Docker login action](https://github.com/docker/login-action#azure-container-registry-acr) simply conflates the two so we would end up with the same `~/.docker/config.json`  file.   But will give it a try.

**Comment by lbruun** [comment]
@HofmeisterAn 

Yes, you right. 

Doing like this in a GitHub Workflow will **not** work


```yaml
 - name: 'Azure CLI login'
   uses: azure/login@v1
   with:
     ...

 - name: 'ACR login'
   run: az acr login --name ${{ vars.ACR_NAME }}
```

but this will:

```yaml

- name: Login to ACR
   uses: docker/login-action@v2
   with:
     registry: ${{ vars.ACR_NAME }}
     username: ${{ secrets.AZURE_CLIENT_ID }}
     password: ${{ secrets.AZURE_CLIENT_SECRET }}   
```

So basically, it really needs to be username/password authentication in order for testcontainers-dotnet to understand it. 

Since the change is so trivial (see the PR) and since I think testcontainers-dotnet should have the goal of supporting the same authentication that Docker CLI does, then I think the PR is still worthwhile.

But thanks, @HofmeisterAn , the `docker/login-action`  will do the trick and is a valid workaround for us.

**Comment by HofmeisterAn** [comment]
> Since the change is so trivial (see the PR) and since I think testcontainers-dotnet should have the goal of supporting the same authentication that Docker CLI does, then I think the PR is still worthwhile.

The issue is that I am unsure whether the configuration you provided above is correct or not. It does not seem right to me. In my understanding, `az acr login` is intended for an individual AD identity, whereas a service principle should be used instead. I could be mistaken on this matter. Nevertheless, having more information and clarity about the appropriate approach would help me in determining the validity of the proposal. I would like to first understand the correct approach. Currently, it seems like more of a workaround, and other (CLI) tools that rely on Docker's login mechanism could also fail with the configuration you have provided. @cristianrgreco @eddumelendez @mdelapenya @kiview any experiences, ideas or thoughts on that topic?

**Comment by lbruun** [comment]
Well, the config I've provided works with the [Docker CLI](https://github.com/docker/cli).

From what I can tell from the Docker CLI source code, is that their [AuthConfig](https://github.com/docker/cli/blob/master/cli/config/types/authconfig.go) object will be [populated](https://github.com/docker/cli/blob/master/cli/config/configfile/file.go#L69) with all fields found in the config file (so including the `identitytoken`) but always with the username/password too. So in this respect somewhat different from my PR.

This is what I believe the Docker CLI sends to the endpoint with my example:

```json
{
  "username": "00000000-0000-0000-0000-000000000000",
  "serveraddress": "...",
  "identitytoken": "gwHEWT356ASfg....eUWR"
}
```

(the password - as derived from the `auth` property - is an empty string so the Docker CLI will leave it out of the JSON object).

So, yes, slightly different than my PR where it would be sending solely this to the endpoint:

```json
{
  "identitytoken": "gwHEWT356ASfg....eUWR"
}
```

For Azure Container Registry at least, both forms seem to work.  But the way the Docker CLI does it should probably be the benchmark.

I've looked at testcontainers-java. Crucial points are [here](https://github.com/testcontainers/testcontainers-java/blob/3b0c1cbbf798f69ff18c22fdb9c2ce7fb0390d2a/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L141) and [here](https://github.com/testcontainers/testcontainers-java/blob/3b0c1cbbf798f69ff18c22fdb9c2ce7fb0390d2a/core/src/main/java/org/testcontainers/utility/RegistryAuthLocator.java#L203). My conclusion is that the underlying Docker library, docker-java, is [prepared for it](https://github.com/docker-java/docker-java/blob/main/docker-java-api/src/main/java/com/github/dockerjava/api/model/AuthConfig.java), but testcontainers-java never populates the identitytoken field. So similar situation to testcontainers-dotnet. Therefore, @HofmeisterAn, I think you are right when you say that other libraries might also fail on the config I've provided.  But the Docker CLI doesn't and that is the important thing.

I'll update the PR to mimic more precisely what the Docker CLI does.

**Comment by mdelapenya** [comment]
In Testcontainers for Go, when autodiscovering the docker auth configs, we leverage [a library](https://github.com/cpuguy83/dockercfg) to read from the credential helpers, and in there, the identity token takes precedence when present (see https://github.com/cpuguy83/dockercfg/blob/main/auth.go#L66-L68 and https://github.com/testcontainers/testcontainers-go/blob/main/docker_auth.go#L53).

**Comment by HofmeisterAn** [comment]
Considering @mdelapenya's response, I think we can add another provider to `DockerRegistryAuthenticationProvider` that resolves the identity token from the Docker config incl. [tests](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/tests/Testcontainers.Tests/Unit/Configurations/DockerRegistryAuthenticationProviderTest.cs):

https://github.com/testcontainers/testcontainers-dotnet/blob/7a5cc2e22dbdaf3d02f4844490f8dee619fe3c20/src/Testcontainers/Builders/DockerRegistryAuthenticationProvider.cs#L96-L99

Somehow, my assumption was resolving the identity token goes always through the credential helpers and I was wondering e.g. why Java does not handle it (AFAIK). Not a proper solution, but you can mimic the credential helper in the meantime too. Something we do in our [tests](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/tests/Testcontainers.Tests/Assets/credHelpers) too.

**Comment by eddumelendez** [comment]
I did some tests last week which are related to this. But, azure was not in that test

## GCP

```
cat token.json | docker login https://us-east1-docker.pkg.dev --username _json_key_base64 --password-stdin
```

## AWS

```
aws ecr-public get-login-password --region <my-region> | docker login <registry> --username AWS --password-stdin
```

and what I can see in both cases by executing `echo "https://us-east1-docker.pkg.dev" | docker-credential-desktop get` is the response with `SeverURL`, `Username` and `Secret` returned. I expect something similar in azure

**Comment by HofmeisterAn** [comment]
@eddumelendez you're using a credential helper. This issue is explicit for an environment without credential helper. Which stores the identity token in the Docker config.

**Comment by lbruun** [comment]
@HofmeisterAn : Regarding creating a new Provider class vs amending the existing provider (`Base64Provider`). This is an implementation concern. You can find this type consideration already mentioned in the PR (see "[Implementation notes](https://github.com/testcontainers/testcontainers-dotnet/pull/842)"). (spoiler alert: a kinda agree with you).

**Comment by PSanetra** [comment]
We are still experiencing this issue with version 3.5.0 and are transforming the docker auth config via the following script locally as a workaround. It would be nice if the Testcontainers library could support the identitytoken natively.

```bash
#!/bin/sh -e

test -n "${ACR_NAME}" || ( echo "ACR_NAME is not defined!" && false )
test -n "${ARM_SUBSCRIPTION_ID}" || ( echo "ARM_SUBSCRIPTION_ID is not defined!" && false )

az acr login --name "${ACR_NAME}" --subscription "${ARM_SUBSCRIPTION_ID}"

TOKEN=$(jq -r ".auths[\"${ACR_NAME}.azurecr.io\"].identitytoken" ~/.docker/config.json)

DOCKER_CONFIG=$(cat ~/.docker/config.json | jq "del(.auths[\"${ACR_NAME}.azurecr.io\"].identitytoken)")

AUTH=$(echo -n "00000000-0000-0000-0000-000000000000:${TOKEN}" | base64 --wrap=0 -)

DOCKER_CONFIG=$(echo "${DOCKER_CONFIG}" | jq ".auths[\"${ACR_NAME}.azurecr.io\"].auth = \"${AUTH}\"")

echo "${DOCKER_CONFIG}" > ~/.docker/config.json

jq . ~/.docker/config.json

```

**Comment by HofmeisterAn** [comment]
There was a pull request (https://github.com/testcontainers/testcontainers-dotnet/pull/842) some time ago. I think we can merge it once we add the [missing test](https://github.com/testcontainers/testcontainers-dotnet/pull/842#discussion_r1146210592).

**Comment by philip-reed** [comment]
Running into the same issue currently and wondering if anyone has a source for this comment from op:
> The fix is trivial as Docker.DotNet library has full support for this use-case.

There's a similar thread over on Docker.DotNet about the same issue:
https://github.com/dotnet/Docker.DotNet/issues/295

**Comment by Anchita** [comment]
Hi, do we have an example of this somewhere? I am trying to pass the the credentials from github actions to my c# code which spins up the test container. However, can't seem to find doicumentation around it. Thanks

**Comment by HofmeisterAn** [comment]
> Hi, do we have an example of this somewhere? I am trying to pass the the credentials from github actions to my c# code which spins up the test container. However, can't seem to find doicumentation around it. Thanks

Just use the [Docker login GH Action](https://github.com/docker/login-action?tab=readme-ov-file#azure-container-registry-acr). Testcontainers will automatically pick up the credentials, you do not need to pass anything to the .NET implementation.

**Comment by Anchita** [comment]
Thank you, that's really helpful.
