### ISSUE TITLE
[Bug]: Update to 3.0.0 breaks runing test container inside other containers

### ISSUE THREAD

**Issue by lukasswm** [testcontainers/testcontainers-dotnet#847]
### Testcontainers version

3.0.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

7.0.202

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:43:10 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.1 (101757)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2+
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.62GiB
 Name: docker-desktop
 ID: XQCN:MJA6:YM73:K7UH:OQZ6:WFXP:DJNY:T5G3:DB4M:UERD:M656:PROM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

I use the new Kafka Module to run the following test

```C#
using Confluent.Kafka;
using Confluent.Kafka.Admin;
using Testcontainers.Kafka;

namespace RunInDockerContainerReproduceV3;

[TestClass]
public class ReproduceWithV3
{
    [TestMethod]
    public async Task TestMethod1()
    {
        await using var kafkaContainer = new KafkaBuilder()
            .WithName("KafkaTestContainerV3")
            .Build();
        
        await kafkaContainer.StartAsync();

        var kafkaBootstrapServer = kafkaContainer.GetBootstrapAddress();
        
        using var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = kafkaBootstrapServer }).Build();
        await adminClient.CreateTopicsAsync(new TopicSpecification[]
        {
            new() {Name = "reproduce.topic", ReplicationFactor = 1, NumPartitions = 12},
        });
    }
}

```

In my setup i run the test containers inside an other container. To execute the tests I use the following command:

docker run -t -i -v /C/Source/RunInDockerContainerReproduce:/build -v /var/run/docker.sock:/var/run/docker.sock -w /build --rm mcr.microsoft.com/dotnet/sdk:7.0-alpine dotnet test -c Release RunInDockerContainerReproduceV3

The Test Breaks when trying to create the kafka topic with the following Exceptions. It seems for me that the kafka test container is not reachable.

Error Message:
   Test method TestPrRunInDockerContainerReproduceV3.ReproduceWithV3.TestMethod1 threw exception:
Confluent.Kafka.KafkaException: Failed while waiting for controller: Local: Timed out
  Stack Trace:
      at TestPrRunInDockerContainerReproduceV3.ReproduceWithV3.TestMethod1() in /build/RunInDockerContainerReproduceV3/ReproduceWithV3.cs:line 22
   at TestPrRunInDockerContainerReproduceV3.ReproduceWithV3.TestMethod1() in /build/RunInDockerContainerReproduceV3/ReproduceWithV3.cs:line 22
   
Executing the test with `dotnet test -c Release RunInDockerContainerReproduceV3` works fine

having the same Test with Version 2.3 works in both szenarios fine.

My Test for the 2.3 Version

```C#
using Confluent.Kafka;
using Confluent.Kafka.Admin;
using DotNet.Testcontainers.Builders;
using DotNet.Testcontainers.Configurations;
using DotNet.Testcontainers.Containers;

namespace RunInDockerContainerReproduceV2_3;

[TestClass]
public class WorkingTestsWithV2_3
{
    [TestMethod]
    public async Task TestMethod1()
    {
        await using var kafkaContainer = new TestcontainersBuilder<KafkaTestcontainer>()
            .WithKafka(new KafkaTestcontainerConfiguration("confluentinc/cp-kafka:6.1.9"))
            .WithPortBinding(9092, true)
            .WithName("kafkatest")
            .Build();
        
        await kafkaContainer.StartAsync().ConfigureAwait(false);

        var kafkaBootstrapServer = kafkaContainer.BootstrapServers;
        
        using var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = kafkaBootstrapServer }).Build();
        await adminClient.CreateTopicsAsync(new TopicSpecification[]
        {
            new() {Name = "reproduce.topic", ReplicationFactor = 1, NumPartitions = 12},
        });
    }
}

```

how can I solve this?

Thank you! :)

### Additional information

See the attached zip and containing read me to reproduce error.

[RunInDockerContainerReproduce.zip](https://github.com/testcontainers/testcontainers-dotnet/files/11054563/RunInDockerContainerReproduce.zip)

**Comment by HofmeisterAn** [comment]
It looks like you are running into #845. Can you verify if the patch works for your setup too?

**Comment by lukasswm** [comment]
Thanks for the quick response!

Thats quite interesting. I changed my configuration as following:

```C#
await using var kafkaContainer = new KafkaBuilder()
            .WithStartupCallback((Func<IContainer, CancellationToken, Task>) ((container, ct) =>
            {
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append("#!/bin/bash");
                stringBuilder.Append('\n');
                stringBuilder.Append("echo 'clientPort=" + 2181 + "' > zookeeper.properties");
                stringBuilder.Append('\n');
                stringBuilder.Append("echo 'dataDir=/var/lib/zookeeper/data' >> zookeeper.properties");
                stringBuilder.Append('\n');
                stringBuilder.Append("echo 'dataLogDir=/var/lib/zookeeper/log' >> zookeeper.properties");
                stringBuilder.Append('\n');
                stringBuilder.Append("zookeeper-server-start zookeeper.properties &");
                stringBuilder.Append('\n');
                stringBuilder.Append("export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://" + container.Hostname + ":" + container.GetMappedPublicPort(KafkaBuilder.KafkaPort) + ",BROKER://" + container.IpAddress + ":" + KafkaBuilder.BrokerPort);
                stringBuilder.Append('\n');
                stringBuilder.Append("echo '' > /etc/confluent/docker/ensure");
                stringBuilder.Append('\n');
                stringBuilder.Append("/etc/confluent/docker/run");
                return container.CopyFileAsync("/testcontainers.sh", Encoding.Default.GetBytes(stringBuilder.ToString()), 493, 0, 0, ct);
            }))
            .WithName("KafkaTestContainerV3")
            .Build();

```
It does not fix my example with the docker run command that I made up to reproduce. But it does fix my original Problem in my CI Pipepline.

**Comment by HofmeisterAn** [comment]
I have looked into your example, and I believe you have encountered two different issues. First, you run into #845. A fix is expected in the next few days. Replacing the `Hostname` with the `IpAddress` property seems to fix it.

As for the second issue, I am not entirely sure why you are facing it. However, I believe that adding `-e TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal` to your Docker run command (**Docker Desktop only**) will prevent it. It looks like the regression was introduced in [2.3.0...2.4.0](https://github.com/testcontainers/testcontainers-dotnet/compare/2.3.0...2.4.0).

**Comment by HofmeisterAn** [comment]
The second issue relates to following change:

https://github.com/testcontainers/testcontainers-dotnet/blob/3e3710de13b0d95521ebc08d7245d8b48e3eebb2/src/Testcontainers/Builders/ContainerBuilder%603.cs#L177-L179

It does not work with the host port `string.Empty`, but with `0`. Docker assigns a random host port from a different range. While `string.Empty` assigns in the range of ~ 57892, `0` assigns in ~ 32785. I need to read and unerstand https://github.com/docker/for-mac/issues/5588#issuecomment-934600089 again. I am not sure what is the right fix TBH 🤔.

**Comment by HofmeisterAn** [comment]
> It does not fix my example with the docker run command that I made up to reproduce.

@lukasswm please use `-v /var/run/docker.sock.raw:/var/run/docker.sock`, this should work.

**Comment by lukasswm** [comment]
> @lukasswm please use -v /var/run/docker.sock.raw:/var/run/docker.sock, this should work.

this does not fix the issue running

```
docker run -t -i -v /C/Source/RunInDockerContainerReproduce:/build -v /var/run/docker.sock.raw:/var/run/docker.sock -w /build --rm mcr.microsoft.com/dotnet/sdk:7.0-alpine dotnet test -c Release RunInDockerContainerReproduceV3
```

> As for the second issue, I am not entirely sure why you are facing it. However, I believe that adding -e TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal to your Docker run command (Docker Desktop only) will prevent it.
this does not work either.

```
docker run -t -i -v /C/Source/RunInDockerContainerReproduce:/build -v /var/run/docker.sock:/var/run/docker.sock -e TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal -w /build --rm mcr.microsoft.com/dotnet/sdk:7.0-alpine dotnet test -c Release RunInDockerContainerReproduceV3
```

>It looks like the regression was introduced in [2.3.0...2.4.0](https://github.com/testcontainers/testcontainers-dotnet/compare/2.3.0...2.4.0).

probably. That's why I used V2.3 for my reproduction example because I was not able to run the V2.3 example with the 2.4.0 Version of the package locally as well with the dotnet test command, but there were diffent problems. That's a lot of different confusing scenarios.

**Edit: had the wrong setup both run commands are working just fine.**

**Comment by HofmeisterAn** [comment]
> this does not fix the issue running

Using the raw socket works fine on my machine. Which error do you get?

    PS C:\Users\atomicjar\Downloads\RunInDockerContainerReproduce> docker run -t -i -v C:/Users/atomicjar/Downloads/RunInDockerContainerReproduce:/build -v /var/run/docker.sock.raw:/var/run/docker.sock -w /build --rm mcr.microsoft.com/dotnet/sdk:7.0-alpine dotnet test -c Release RunInDockerContainerReproduceV3
      Determining projects to restore...
      Restored /build/RunInDockerContainerReproduceV3/RunInDockerContainerReproduceV3.csproj (in 6.39 sec).
      RunInDockerContainerReproduceV3 -> /build/RunInDockerContainerReproduceV3/bin/Release/net7.0/RunInDockerContainerReproduceV3.dll
    Test run for /build/RunInDockerContainerReproduceV3/bin/Release/net7.0/RunInDockerContainerReproduceV3.dll (.NETCoreApp,Version=v7.0)
    Microsoft (R) Test Execution Command Line Tool Version 17.5.0 (x64)
    Copyright (c) Microsoft Corporation.  All rights reserved.

    Starting test execution, please wait...
    A total of 1 test files matched the specified pattern.

    Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 4 s - RunInDockerContainerReproduceV3.dll (net7.0)

> That's a lot of different confusing scenarios.

Indeed, there have been a few changes in the past. The setup is a bit difficult, especially because we are facing internal Docker Desktop bugs. However, we have now aligned the implementation with Java, where using raw sockets seems to be the right way.

**Comment by lukasswm** [comment]
still the same error:
Confluent.Kafka.KafkaException: Failed while waiting for controller: Local: Timed out

but what is more confusing is that even the dotnet test command gets this error now. Even restarted my machine but still...

As it worked before It's most likely something on my machine changed but I don't know what.

**Comment by HofmeisterAn** [comment]
> still the same error:
> Confluent.Kafka.KafkaException: Failed while waiting for controller: Local: Timed out

As mentioned above, those are two different issues. The Kafka timeout issue is fixed. The fix is included in the next release. In the meantime you can override `WithStartupCallback`. To run the Docker Wormhole pattern (sibling containers) you need to mount Docker's raw socket.

```csharp
await using var kafkaContainer = new KafkaBuilder()
    .WithName("KafkaTestContainerV3")
    .WithStartupCallback((container, ct) =>
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append("#!/bin/bash");
        stringBuilder.Append('\n');
        stringBuilder.Append("echo 'clientPort=" + 2181 + "' > zookeeper.properties");
        stringBuilder.Append('\n');
        stringBuilder.Append("echo 'dataDir=/var/lib/zookeeper/data' >> zookeeper.properties");
        stringBuilder.Append('\n');
        stringBuilder.Append("echo 'dataLogDir=/var/lib/zookeeper/log' >> zookeeper.properties");
        stringBuilder.Append('\n');
        stringBuilder.Append("zookeeper-server-start zookeeper.properties &");
        stringBuilder.Append('\n');
        stringBuilder.Append("export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://" + container.Hostname + ":" + container.GetMappedPublicPort(KafkaBuilder.KafkaPort) + ",BROKER://" + container.IpAddress + ":" + KafkaBuilder.BrokerPort);
        stringBuilder.Append('\n');
        stringBuilder.Append("echo '' > /etc/confluent/docker/ensure");
        stringBuilder.Append('\n');
        stringBuilder.Append("/etc/confluent/docker/run");
        return container.CopyFileAsync("/testcontainers.sh", Encoding.Default.GetBytes(stringBuilder.ToString()), 493, 0, 0, ct);
    })
    .Build();

await kafkaContainer.StartAsync();

var kafkaBootstrapServer = kafkaContainer.GetBootstrapAddress();

using var adminClient = new AdminClientBuilder(new AdminClientConfig { BootstrapServers = kafkaBootstrapServer }).Build();
await adminClient.CreateTopicsAsync(new TopicSpecification[]
{
    new() {Name = "reproduce.topic", ReplicationFactor = 1, NumPartitions = 12},
});
```

incl.

    docker run -t -i -v C:/Users/atomicjar/Downloads/RunInDockerContainerReproduce:/build -v /var/run/docker.sock.raw:/var/run/docker.sock -w /build --rm mcr.microsoft.com/dotnet/sdk:7.0-alpine dotnet test -c Release RunInDockerContainerReproduceV3
    
runs fine.

**Comment by lukasswm** [comment]
Layer 8 issue. Sorry for that! Played around with my exmaple trying out different configurations. Did not saw the changes as it was not under source control.

works fine with the socket.raw as you said!

**Comment by HofmeisterAn** [comment]
> works fine with the socket.raw as you said!

Great! We will update the [docs](https://github.com/testcontainers/testcontainers-dotnet/pull/852) accordingly. If you do not mind I would close the issue?

**Comment by lukasswm** [comment]
Yes. I'm happy! Thanks for the great support!
