### ISSUE TITLE
[Enhancement]: Add CreateIfNotExists() to IFutureDockerImage

### ISSUE THREAD

**Issue by WojciechNagorski** [testcontainers/testcontainers-dotnet#853]
### Problem

I'm using TestContainers 3.0.0 and it is a fantastic tool. In my test, I have to build an image from Dockerfile. I'm using `ImageFromDockerfileBuilder`:

```C#
    this.controllerImage = new ImageFromDockerfileBuilder()
        .WithName("docker-ctrl-1-image")
        .WithDockerfileDirectory(CommonDirectoryPath.GetSolutionDirectory(), "Services\\LocalNodes")
        .WithDockerfile("Dockerfile")
        .Build();

    await this.controllerImage.CreateAsync();
```

The code works perfectly but I would like to Create an image only if it not exists. 

I do not know how to achieve this behavior using version 3.0.0.

### Solution

Maybe add `CreateIfNotExistsAsync()` to the `IFutureDockerImage` interface:

Usage could look like this:
`await this.controllerImage.CreateIfNotExistsAsync();` 

### Benefit

It will speed up integration tests on the local machine.

### Alternatives

I could use Dotnet.Docker library but it is not such an elegant solution. 

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
I am afraid that this is not possible yet, but what are your thoughts on implementing a similar mechanism to the image pull policy?

https://github.com/testcontainers/testcontainers-dotnet/blob/2a3688d885f445984bd15f055e88fafaba696c72/src/Testcontainers/Clients/TestcontainersClient.cs#L273-L283

It exposes a builder API where the developer can pass a function to determine whether Testcontainers pulls the image or not:

https://github.com/testcontainers/testcontainers-dotnet/blob/2a3688d885f445984bd15f055e88fafaba696c72/src/Testcontainers/Builders/ContainerBuilder%603.cs#L95-L98

We can do something similar to determine whether we build an image or not. Incl. default [policies](https://github.com/testcontainers/testcontainers-dotnet/blob/2a3688d885f445984bd15f055e88fafaba696c72/src/Testcontainers/Images/PullPolicy.cs).
