### ISSUE TITLE
[Bug]: Cake .NET tool (the Cake.Git package) doesn't support macOS (ARM64) OOB

### ISSUE THREAD

**Issue by olitomlinson** [testcontainers/testcontainers-dotnet#859]
### Testcontainers version

3.0.0

### Using the latest Testcontainers version?

Yes

### Host OS

Mac OS 13.2.1

### Host arch

ARM (M1)

### .NET version

6.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:35:19 2023
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.0 (99724)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:31:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
olivertomlinson@TCH-UK-LM-QG00-129 testcontainers-dotnet-dapr %
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 12
  Running: 4
  Paused: 0
  Stopped: 8
 Images: 291
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.49-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 5
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: 4T5W:AHW7:FA3G:XWM3:SBSN:AUQF:CTEB:DFAN:6JXA:SYPK:ZTNF:XLAD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Trying to run `dotnet cake` from the root folder and it blows up with

`Error: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception`
 
 Tried within the Dev Container and without, same issue. 

### Relevant log output

```shell
Error: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception
```

### Additional information

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4224880/229214503-d40ccdec-d754-4686-8980-b93d01656c84.png">

dotnet --list-sdks
6.0.302 [/usr/local/share/dotnet/sdk]
6.0.400 [/usr/local/share/dotnet/sdk]

**Comment by HofmeisterAn** [comment]
I am certain that the Cake configuration is working as expected. We are using it in our pipeline with both Linux and Windows runners, and it is running properly in our Codespace configuration as well (GitHub, Linux, Windows, Intel-based macOS).

```
@HofmeisterAn ➜ /workspaces/testcontainers-dotnet (develop) $ dotnet tool restore
Tool 'cake.tool' (version '3.0.0') was restored. Available commands: dotnet-cake

Restore was successful.
@HofmeisterAn ➜ /workspaces/testcontainers-dotnet (develop) $ dotnet cake --target=Build-Information

----------------------------------------
Setup
----------------------------------------
Building version 3.1.0-beta of Testcontainers (develop@5152cffa097b660292989cddd490f80dcfefa994)

========================================
Build-Information
========================================
...

----------------------------------------
TearDown
----------------------------------------

Task                          Duration
--------------------------------------------------
Setup                         00:00:00.0174056
Build-Information             00:00:00.0070899
Teardown                      00:00:00.0003957
--------------------------------------------------
Total:                        00:00:00.0248912
```

I believe that you are experiencing the following known issues:

- https://github.com/cake-contrib/Cake_Git/issues/165
- https://github.com/libgit2/libgit2sharp/issues/1951

We cannot do much until the upstream issue is addressed for Apple Silicon Macs. This is not an issue in Testcontainers.

**Comment by olitomlinson** [comment]
That's fair. Thanks for the reply.

**Comment by HofmeisterAn** [comment]
I will close this issue. If you still think it is relevant, please do not hesitate to reopen it.

**Comment by digital88** [comment]
How I "fixed" this issue on arm macOS:

Copy file `.cake-tools/Addins/Cake.Git.4.0.0/runtimes/osx-arm64/native/libgit2-a2bde63.dylib` to folder `.cake-tools/Addins/Cake.Git.4.0.0/lib/{$TFM}/` and replace existing `libgit2-a2bde63.dylib`. $TFM in my case was `net8.0`.

I don't understand why, but authors of Cake.Git package put x64 libs in `lib` folder by default.

@HofmeisterAn  maybe this issue is worth a note [somewhere](https://github.com/testcontainers/testcontainers-dotnet/blob/54f45516856fe8f621316a215aae675dbee58b34/docs/contributing.md?plain=1#L10C37-L10C94) in readme ? I checked latest version of cake and Cake.Git (5.0.0), and it's still not working "out of the box".

Also related: https://github.com/cake-build/cake/issues/4402

**Comment by HofmeisterAn** [comment]
> I don't understand why, but authors of Cake.Git package put x64 libs in `lib` folder by default.

@digital88 while I was reading your comment, I was thinking, couldn't we use Cake's [Setup](https://github.com/testcontainers/testcontainers-dotnet/blob/54f45516856fe8f621316a215aae675dbee58b34/build.cake#L11-L21) to copy the file to the correct directory on macOS? Or at least display a message and exit Cake until it's not properly configured. WDYT?

**Comment by digital88** [comment]
Unfortunately, it fails before executing any targets. We should also somehow check the arch of host. Arm linux and arm windows has this issue too.

Maybe just pin this issue on top? Zero code changes needed, the fix is simple to do manually and it's a one time thing (`.cake-tools` is cached on disk). And in the future cake authors may fix the issue on their side.

I think pinning this issue will be helpful in troubleshooting why cake fails on arm and how to fix. Maybe rename title to `[Bug]: dotnet cake does not work on arm (macOS M-series chip)` or something like that.
