### ISSUE TITLE
[Enhancement]: Add Keycloak module

### ISSUE THREAD

**Issue by Dmitry0108** [testcontainers/testcontainers-dotnet#879]
### Problem

There is no support for Keycloak OIDC

### Solution

Add support for Keycloak container

### Benefit

We can run integration tests for services that used Keycloak authentication and authorization

### Alternatives

No alternatives

### Would you like to help contributing this enhancement?

No

**Comment by VMelnalksnis** [comment]
I've already created a package for Keycloak, with the ability to configure realms, clients and users from code - https://github.com/VMelnalksnis/Testcontainers/tree/master/source/VMelnalksnis.Testcontainers.Keycloak. The only caveat is that is does not work with v3, as it was written for v2.3.0 before the breaking changes.

I'd be willing to help to move it to the testcontainers package if needed. Migrating to the new format feels like a complete rewrite though. At least when I tried I couldn't get it working again, so it would be great if someone could point to either some documentation on how the new modules should be written

**Comment by HofmeisterAn** [comment]
> it would be great if someone could point to either some documentation on how the new modules should be written

We explain it in our documentation ([docs](https://dotnet.testcontainers.org/modules/#implement-a-module)), and there are already numerous module [implementations](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src) available. It's important to note that we typically don't expose APIs through the builder for configurations that the Docker image exposes through environment variables or client functionalities. Instead, we aim to pre-configure the container with whatever is necessary to start it.

Did you encounter any particular issues? I suggest we look into creating an MVP, and I would be happy to help.

**Comment by VMelnalksnis** [comment]
I think the main issues were regarding exposing configuration to the user, so I guess that makes sense since that is not really supported.

Regarding pre-configuration, what would be expected for Keycloak? I think that the minimum would be a single realm, client and user, however the configuration for those will most likely be different for applications. Would it maybe be better to expose `CreateRealm/CreateClient/CreateUser` methods on the container, similiar to what I already have [here](https://github.com/VMelnalksnis/Testcontainers/blob/master/source/VMelnalksnis.Testcontainers.Keycloak/KeycloakTestcontainer.cs)? Or does that also not belong in official modules?

Edit: I've also successfully migrated to v3.1.0 - https://github.com/VMelnalksnis/Testcontainers/blob/master/source/VMelnalksnis.Testcontainers.Keycloak/KeycloakContainer.cs

**Comment by HofmeisterAn** [comment]
> Regarding pre-configuration, what would be expected for Keycloak?

I am not an expert in Keycloak, but I would expect something similar to other modules. For example, the database modules spin up containers and indicate readiness, but they do not seed data. Couchbase is a more complex [module](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/src/Testcontainers.Couchbase/CouchbaseBuilder.cs) and configures an entire instance until it is ready to use. 

> Would it maybe be better to expose `CreateRealm/CreateClient/CreateUser` methods on the container, similiar to what I already have [here](https://github.com/VMelnalksnis/Testcontainers/blob/master/source/VMelnalksnis.Testcontainers.Keycloak/KeycloakTestcontainer.cs)?

The link does not work. Considering that there are Keycloak clients (such as Keycloak.Net) that utilize the Keycloak REST API, I would expect that the responsibility of creating a realm or user lies with them.

**Comment by VMelnalksnis** [comment]
> The link does not work.

That link was to the old version, I linked the v3.1.0 code in the edit - https://github.com/VMelnalksnis/Testcontainers/blob/master/source/VMelnalksnis.Testcontainers.Keycloak/KeycloakContainer.cs. I used `kcadm.sh` and `ExecAsync`, but I guess equivalent commands are exposed via the API. 

I'll create PR without the realm initialization then.

**Comment by HofmeisterAn** [comment]
We likely only need to start Keycloak and retrieve the authentication token or any other credentials that Keycloak uses to authenticate against the REST API. I assume that users can configure any additional settings using clients like Keycloak.NET or alternatives.
