### ISSUE TITLE
Add commit message guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by HofmeisterAn** [testcontainers/testcontainers-dotnet#88]

**Comment by Jacques-Murray** [comment]
I've added the guidelines to a separate branch. I do however need permissions to publish the branch to this repository.

**Comment by HofmeisterAn** [comment]
You have to fork the project and create a pull request from your forked branch. You will find further information [here](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). Thanks for your contribution.

**Comment by Jacques-Murray** [comment]
> You have to fork the project and create a pull request from your forked branch. You will find further information [here](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork). Thanks for your contribution.

Thank you. I've created the fork and pull request.

**Comment by HofmeisterAn** [comment]
Closed with #89.
