### ISSUE TITLE
[Bug]: no documentation for configurations

### ISSUE THREAD

**Issue by mikeblas** [testcontainers/testcontainers-dotnet#886]
### Testcontainers version

2.4..0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

7.0.3

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:20:14 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.10.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.68GiB
 Name: docker-desktop
 ID: f14878de-c3ab-45c2-9859-187799ce8114
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

Unable to discover how to use TestContainers.NET to connect to Docker on a remote host

### Additional information

The [Custom configuration](https://dotnet.testcontainers.org/custom_configuration/) documentation says that configuration is possible at runtime "through the `TestcontainersSettings` class". I can't find a shred of documentation about this class.

From inspecting code, it has a couple of properties -- but far fewer than the ones exposed in the configuration file. My goal is pretty simple: I just want to have Testcontainers connect to a different endpoint than the default, and I guess I'll also need to figure out how to manage security for that. How do I do so?

Am I missing links to reference material that would help out with this?

**Comment by HofmeisterAn** [comment]
To configure the Docker endpoint, use either the [mentioned](https://dotnet.testcontainers.org/custom_configuration/) properties file together with the `docker.host` key or the environment variable `DOCKER_HOST`:

>The Docker daemon socket to connect to.

*~/testcontainers.properties file*:
```console
docker.host=tcp://127.0.0.1:2375
```

*Environment variable*:

```console
DOCKER_HOST=tcp://127.0.0.1:2375
```

**Comment by mikeblas** [comment]
So configuration can't be done at runtime, like the docs say? That seems to match what I've found so far -- the `TestcontainerSettings.DockerHostOverride` property doesn't seem to be connected to anything. And `ICustomConfiguration` looks promising, but I can't find it exposed in any way.

**Comment by HofmeisterAn** [comment]
> So configuration can't be done at runtime, like the docs say? That seems to match what I've found so far -- the `TestcontainerSettings.DockerHostOverride` property doesn't seem to be connected to anything.

You are mixing up two different configurations, and there are even more options available to configure a remote endpoint (during runtime). The configuration called `DockerHostOverride` (`TESTCONTAINERS_HOST_OVERRIDE`, `host.override`) is used to override the DNS name resolution, which is required in some container runtime environments. However, this configuration is not related to configuring a remote endpoint.

To set a remote endpoint during runtime, you can use either of both:

```csharp
TestcontainersSettings.OS = new Unix(new Uri("tcp://127.0.0.1:2375"));
```

```csharp
_ = new ContainerBuilder()
    .WithDockerEndpoint(new Uri("tcp://127.0.0.1:2375"))
    .WithImage("alpine:3.17")
    .Build();
```

However, we do not recommend using the static approach because it needs to be one of the first calls and developers tend to set it too late. In fact, `TestcontainersSettings` is only kept for backwards compatibility and user feedback. The best approach to configure Testcontainers is either by using the properties file or environment variables.

I recommend using the environment variable because it is a de facto standard and is used by other tools etc.

I will update the docs regarding the two recommended approaches.

**Comment by mikeblas** [comment]
Actually, there's no confusion of these concepts -- it's just that I don't know them *at all*! 😆  I'm trying to discover these undocumented features. You say that "there are even more options available to configure a remote endpoint (during runtime)".  What are they, and where can I find documentation on how to use them?

Your response uses the `OS` property of `TestcontainerSettings`. I never would've thought that name would lead to a way to configure a remote endpoint. Where are this, and other properties of `TestcontainerSettings` documented? It looks like the `Unix` class comes from TestContainers.NET, as well. Where can I find its documentation? 

Which of the two approaches that you've described is "the static approach"? Where can I read the details of that recommendation, and other recommendations for using the library?

Where can I read about this and other "de facto standards"?

If properties files and environment variables are the best approach for configuration, why does the documentation say " If you prefer to configure your test environment at runtime, you can set or override the configuration through the `TestcontainersSettings` class. "?

If I were to use environment variables for configuration, it seems like I'd need to wrap any process that uses Testcontainers.NET into another process that set up the environment variables. 

The documentation (can it be trusted, at this point?) says "with the Testcontainers [properties file](https://docs.oracle.com/cd/E23095_01/Platform.93/ATGProgGuide/html/s0204propertiesfileformat01.html) (~/testcontainers.properties)", which implies that there is one properties file in the home directory of the user. What if I need to concurrently use two different configurations? That must mean I need two different users? 

Then, where is the properties file itself documented? The link goes off to some weird Oracle documentation for one of their web commerce platforms. Is that platform where this configuration model originated?

I guess I *am* confused about something: How do new users learn to use this library? Where can I find comprehensive documentation for it?
