### ISSUE TITLE
[Bug]: DroneIO

### ISSUE THREAD

**Issue by dmp2tech** [testcontainers/testcontainers-dotnet#887]
### Testcontainers version

3.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

7.0.4

### Docker version

```shell
23.0.5
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 31
  Running: 14
  Paused: 0
  Stopped: 17
 Images: 60
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 8avbyb7layoc6i0sld0bshbw7
  Is Manager: false
  Node Address: XXX.XXX.XXX
  Manager Addresses:
   xxxx.XXXX.XXX
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-146-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.58GiB
 Name: cat
 ID: 4BFS:WQJC:YTRL:MGQI:BI23:T5VL:5YUS:5FN7:5TFE:TYRY:U7TI:US5Y
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### What happened?

I try to launch my environment test with drone, but I have as error  

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[testcontainers.org 00:00:00.07] Connected to Docker:
  Host: unix:///var/run/docker.sock
  Server Version: 23.0.5
  Kernel Version: 5.4.0-146-generic
  API Version: 1.42
  Operating System: Alpine Linux v3.17 (containerized)
  Total Memory: 15.58 GB
[testcontainers.org 00:00:00.17] Docker config "/root/.docker/config.json" not found
[testcontainers.org 00:00:00.17] Searching Docker registry credential in Auths
[testcontainers.org 00:00:00.17] Docker registry credential https://index.docker.io/v1/ not found
[testcontainers.org 00:00:02.28] Docker image testcontainers/ryuk:0.4.0 created
[testcontainers.org 00:00:02.82] Docker container 1668da235948754cb20760d444efd108d4b3ab4ae27e51976cf1d1f07758f1f6 created
[testcontainers.org 00:00:02.89] Start Docker container 1668da235948754cb20760d444efd108d4b3ab4ae27e51976cf1d1f07758f1f6
[testcontainers.org 00:01:03.28] Stop Docker container 1668da235948754cb20760d444efd108d4b3ab4ae27e51976cf1d1f07758f1f6
[testcontainers.org 00:01:03.52] Docker container ef6dfb5f9d5e2b62d7bae44f9961fd61c9b7b77ce520b38deca7ccdff5684d94 created
[testcontainers.org 00:01:03.52] Start Docker container ef6dfb5f9d5e2b62d7bae44f9961fd61c9b7b77ce520b38deca7ccdff5684d94

Failed xxxxx [1 ms]
  Error Message:
   DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.
  Stack Trace:
     at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, IImage resourceReaperImage, IMount dockerSocket, Boolean requiresPrivilegedMode, TimeSpan initTimeout, CancellationToken ct)

**Comment by dmp2tech** [comment]
After several searches I found a plugin made for drone. And it works. 
https://github.com/testcontainers/dind-drone-plugin

**Comment by HofmeisterAn** [comment]
Great 👍 , I was trying to test it myself, but I couldn't create an account:

> Drone Cloud is no longer accepting new registrations. We recommend installing Drone on your own hardware, or you can try out the new Harness CI Cloud.
