### ISSUE TITLE
[Enhancement]: Add IContainer.CreateAsync

### ISSUE THREAD

**Issue by tyb-dev** [testcontainers/testcontainers-dotnet#891]
### Problem

I need to copy some files into the container before it gets started. In Docker, it's possible to _create_ but not _start_ a container to accomplish this. However, TestContainers only offers StartAsync. 

### Solution

Add the missing method. It seems there's already a non-public UnsafeCreateAsync to accomplish this. It's just not available as a user of the library. 

### Benefit

Copy test-related files into the container before it gets started. 

### Alternatives

A workaround is to use binding redirects, but they do not work properly on many build platforms, for example when running a container inside a container while sharing the docker socket. 

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
The container builder offers `WithResourceMapping(string, string)` and several other overloads. Resource mappings are copied to the container before it starts, which is likely what you require. Here is a test / an example:

https://github.com/testcontainers/testcontainers-dotnet/blob/36ded55005230c39cf6e3dd51b0e398c84023efe/tests/Testcontainers.Tests/Unit/Containers/Unix/CopyResourceMappingContainerTest.cs#L26-L30

**Comment by tyb-dev** [comment]
Thanks
