### ISSUE TITLE
[Enhancement]: Code summary on methods does not show correct documentation

### ISSUE THREAD

**Issue by StefH** [testcontainers/testcontainers-dotnet#917]
### Problem

I've this c# code:
``` c#
var sql = new MsSqlBuilder()
            .WithCleanUp(true)
            .Build();
```

And when hovering over ".WithCleanup" in VS2022, I see this:
![image](https://github.com/testcontainers/testcontainers-dotnet/assets/249938/7c1f0387-58a8-4c44-b871-94fc32b70c39)

### Solution

This documentation should be displayed:

![image](https://github.com/testcontainers/testcontainers-dotnet/assets/249938/11c30ae5-bb66-4163-8f54-16cc69fef356)

### Benefit

Correct code comments

### Alternatives

-

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
Thank you for bringing the issue to our attention. I believe it is related to the `cref="IContainerBuilder{TBuilderEntity, TContainerEntity}"` attribute in the `inheritdoc` tag, e.g.:

https://github.com/testcontainers/testcontainers-dotnet/blob/bc176a09575277e657db3149ae0a95b567249b65/src/Testcontainers/Builders/ContainerBuilder%603.cs#L38

Without the attribute, the documentation inherits correct in Rider. Can you confirm it for VS too?
