### ISSUE TITLE
[Bug]: MySql DefaultDatabase conflicts with system schema

### ISSUE THREAD

**Issue by ghost** [testcontainers/testcontainers-dotnet#948]
### Testcontainers version

3.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86

### .NET version

7.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.10
 Git commit:        7155243
 Built:             Thu Jan 19 17:43:10 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.17.1 (101757)
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.10
  Git commit:       6051f14
  Built:            Thu Jan 19 17:32:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.84GiB
 Name: docker-desktop
 ID: CXGU:TYQT:5U5R:7A67:6KNS:UY7H:XTSD:SOJD:OIPE:HE5Q:37NP:6JMU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

Im getting an exception: "Access to system schema MySql is rejected"
This is happening because the schema already exists as a system schema: https://dev.mysql.com/doc/refman/8.0/en/system-schema.html

Running `container = new MySqlBuilder().WithDatabase("TestDatabase").Build();` fixes the issue, as we are not longer trying to run our database on the same database as a system schema.

I would fix this my self, but I dont have push permissions.

**Comment by HofmeisterAn** [comment]
> Im getting an exception: "Access to system schema MySql is rejected"

By using the [default](https://github.com/testcontainers/testcontainers-dotnet/blob/5662d26201b3c60249e08d6b6f4d97b6e6cc1666/src/Testcontainers.MySql/MySqlBuilder.cs#L11-L15) MySQL builder configuration? I do not entirely understand which configuration fails. Our [tests](https://github.com/testcontainers/testcontainers-dotnet/blob/5662d26201b3c60249e08d6b6f4d97b6e6cc1666/tests/Testcontainers.MySql.Tests/MySqlContainerTest.cs) run fine against the default configuration. Can you share a reproducer?

> I would fix this my self, but I dont have push permissions.

That is intended. To submit a feature or fix, you need to fork the repository and create a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

**Comment by ghost** [comment]
Its happening on `Context.Database.EnsureDeleted()`.
Im getting the following exception when running with default databasename:

`{"@timestamp":"2023-07-18T11:54:40.7622081+02:00","level":"Error","messageTemplate":"Failed executing DbCommand ({elapsed}ms) [Parameters=[{parameters}], CommandType='{commandType}', CommandTimeout='{commandTimeout}']{newLine}{commandText}","message":"Failed executing DbCommand (\"2\"ms) [Parameters=[\"\"], CommandType='Text', CommandTimeout='30']\"\r\n\"\"DROP DATABASE `mysql`;\"","fields":{"elapsed":"2","parameters":"","commandType":"Text","commandTimeout":30,"newLine":"\r\n","commandText":"DROP DATABASE `mysql`;","EventId":{"Id":20102,"Name":"Microsoft.EntityFrameworkCore.Database.Command.CommandError"},"SourceContext":"Microsoft.EntityFrameworkCore.Database.Command","Service":"Academy"}}
Exception thrown: 'MySqlConnector.MySqlException' in Microsoft.EntityFrameworkCore.Relational.dll
An exception of type 'MySqlConnector.MySqlException' occurred in Microsoft.EntityFrameworkCore.Relational.dll but was not handled in user code
Access to system schema 'mysql' is rejected.`

**Comment by HofmeisterAn** [comment]
I see, this does not make much sense. What is your suggestion? Renaming the default database to something else like `test`?

**Comment by ghost** [comment]
Exactly. In my project I just called it `TestDatabase`, but anything other than the system schemas should work.

**Comment by HofmeisterAn** [comment]
👍 Would you like to contribute and submit a PR with the change? I propose `test` as default database name.

**Comment by ghost** [comment]
Sure, had to figure out how to create a PR from a fork, but its up now. Please have a look, and let me know if I have to change anything :)
