### ISSUE TITLE
[Enhancement]: Add InfluxDB module

### ISSUE THREAD

**Issue by MelomanG** [testcontainers/testcontainers-dotnet#950]
### Problem

There is no support for the InfluxDB container.

### Solution

Introduce the InfluxDB module.

### Benefit

We will be able to run integration tests for services that use InfluxDB.

### Alternatives

No alternatives.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
Thank you for addressing the issue. I appreciate your interest in contributing. I'd like to share some information about the module API. You can find a brief guide on how to implement a module [here](https://dotnet.testcontainers.org/modules/#implement-a-module). Our existing modules are also good points of reference, and you can find them [here](https://github.com/testcontainers/testcontainers-dotnet/tree/develop/src).

Given that there's an existing Java module, I suggest familiarizing yourself with its implementation. This will help you consider the configurations in a way that aligns with .NET practices. The Java implementations typically include best practices for module (container) configurations.

**Comment by eddumelendez** [comment]
[InfluxDB](https://github.com/testcontainers/testcontainers-java/blob/main/modules/influxdb/src/main/java/org/testcontainers/containers/InfluxDBContainer.java) implementation in Testcontainers for Java already supports v1 and v2. I would suggest to support v2 and see if v1 is needed. In Java, both are supported for historical reasons

**Comment by MelomanG** [comment]
I have already prepared the code but cannot push the branch from localhost or create a new branch from GitHub. Could you give me a hand with it?

**Comment by HofmeisterAn** [comment]
You cannot push to the testcontainers/testcontainers-dotnet repository. You need to fork the repository first and create a pull request ([Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)).

**Comment by MelomanG** [comment]
Thanks for the info! Sorry for that, first time :D
