### ISSUE TITLE
[Enhancement]: Reimplement support for log streaming via the `IOutputConsumer`

### ISSUE THREAD

**Issue by jacobjmarks** [testcontainers/testcontainers-dotnet#952]
### Problem

With the merging of #793, container log output can no longer be streamed (on an as-written basis) to a location of the developer's choice. Support for utilising the `IOutputConsumer` has been removed and "replaced" with a method which &mdash while also useful, and should be retained &mdash; serves a different purpose in fetching logs on an ad-hoc/point-in-time basis.

### Solution

Re-enable the support for the registered `IOutputConsumer` and remove the `Obsolete` attribute from relevant methods.

### Benefit

This change will allow consumers to stream the output from containers wherever they see fit, whether that be to the system console or elsewhere.

### Alternatives

I do not believe there are any alternatives to achieve this log streaming.

### Would you like to help contributing this enhancement?

~No~ Yes

**Comment by HofmeisterAn** [comment]
Thanks for raising the issue. As mentioned in the PR's comment, we can add the support again if it is a required feature. We just need to add the member [AttachAsync(string, IOutputConsumer, CancellationToken)](https://github.com/testcontainers/testcontainers-dotnet/blob/af7f253fa1bcbc572d587dc0e5e7a55a91efaa24/src/Testcontainers/Clients/ITestcontainersClient.cs#L84-L91) again. However, I would still not consider the output consumer in the default wait strategy, I saw too many wrong configurations. Simply passing a string to the wait strategy (without the dependent stream) is much easier.

Are you interesting in adding the support again?

**Comment by jacobjmarks** [comment]
What are some examples of these wrong configurations? I'm interested in utilising the `IOutputConsumer` outside of the context of wait strategies entirely. I'll take a closer look however to confirm the feature acts in the way I assume.
