### ISSUE TITLE
[Enhancement]: Support customizing the Wait Strategy timeout

### ISSUE THREAD

**Issue by jacobjmarks** [testcontainers/testcontainers-dotnet#953]
### Problem

It is currently not possible to configure the timeout for wait strategies. Even though this looks to be supported, via [`WaitStrategy.WaitUntilAsync()`](https://github.com/testcontainers/testcontainers-dotnet/blob/762feda35d4dd9778d86a0c2b50202e8abbb163e/src/Testcontainers/Configurations/WaitStrategies/WaitStrategy.cs#L66C36-L66C36), a hardcoded `Timeout.InfiniteTimeSpan` exists [here](https://github.com/testcontainers/testcontainers-dotnet/blob/762feda35d4dd9778d86a0c2b50202e8abbb163e/src/Testcontainers/Containers/DockerContainer.cs#L441C22-L441C22). Support for modifying this value should be available via the public APIs.

See related #827 

### Solution

Add suitable support for defining a timeout value for a given wait strategy and utilise this during their execution.

### Benefit

Allows consumers to set timeouts for wait strategies. This is critical to ensure erroneous strategies do not cause the application to hang, waiting forever.

### Alternatives

I do not believe there are any alternatives, other than re-implementing existing `internal` wait strategies to add necessary timeout support.

### Would you like to help contributing this enhancement?

Yes

**Comment by HofmeisterAn** [comment]
I agree, and it also bothers me. As you mentioned, there is already an issue, and there is a [branch](https://github.com/testcontainers/testcontainers-dotnet/compare/feature/refactor-wait-strategy-api) with most of the needed changes. IIRC I was not completely happy with them and lacked feedback.

> I do not believe there are any alternatives, other than re-implementing existing `internal` wait strategies to add necessary timeout support.

You can use a [CancellationTokenSource](https://learn.microsoft.com/dotnet/api/system.threading.cancellationtokensource) incl. a timeout and pass the token to `StartAsync(CancellationToken)` to cancel the start.

**Comment by jacobjmarks** [comment]
Closing as duplicate.
