### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by B-OPS-HUB** [testcontainers/testcontainers-dotnet#954]
### Testcontainers version

3.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

윈도우

### Host arch

x64

### .NET version

6.0

### Docker version

```shell
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:28:08 2023
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:18:42 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.4)
  compose: Docker Compose (Docker Inc., v2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.19)
  init: Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.2)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.9.0)
```

### What happened?

When using testcontainer, there is a phenomenon in which it is executed once more after it is terminated.

I wonder why.

I was able to know more about the above phenomenon because the execution time was long while testing with logstash.

Is there any way to solve it?

And sometimes, there is a container called testcontainer as it is.

**Comment by HofmeisterAn** [comment]
> When using testcontainer, there is a phenomenon in which it is executed once more after it is terminated.

I apologize, but I am having trouble understanding what you mean. Could you provide more information? If possible, sharing a code snippet or a reproducer that demonstrates the issue would be very helpful.

**Comment by HofmeisterAn** [comment]
I will close this issue. I cannot help without more information. Do not hesitate to reopen it again in case you have additional information.
