### ISSUE TITLE
[Bug]: test run before testcontainers elastic container is finished starting/healthy

### ISSUE THREAD

**Issue by LGmatrix13** [testcontainers/testcontainers-dotnet#955]
### Testcontainers version

Elastic package - 3.3.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host arch

x86

### .NET version

6

### Docker version

```shell
4.20.1
```

### Docker info

```shell
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 14
  Running: 2
  Paused: 0
  Stopped: 12
 Images: 28
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.15.90.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.598GiB
 Name: docker-desktop
 ID: 83bf66ce-9214-48cd-af7c-95a908e1215e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

### What happened?

I am trying to start this elastic search container and wait for it to be healthy. Elastic typically needs 1-2 minutes before being available since requests are make to it via http:

```
            elasticsearchContainer = new ElasticsearchBuilder()
                .WithImage("docker.elastic.co/elasticsearch/elasticsearch:8.8.1")
                .WithPortBinding(9200)
                .WithEnvironment("xpack.security.enabled", "false")
                .WithWaitStrategy(
                    Wait.ForUnixContainer()
                    .UntilContainerIsHealthy()
                    )
                .Build();
```

However, tests start immediately and as a result, fail when they are not supposed to. If I start this same image with the same parameters and wait for elastic to run healthy, it works without an issue. This could be a bug with the elastic package, or maybe I am just doing something wrong?

**Comment by LGmatrix13** [comment]
I've tried both the until health and until http success on "/"

**Comment by jacobjmarks** [comment]
This may be due to your defined wait strategy, i.e. `UntilContainerIsHealthy`. This does not consider the status of anything inside the container but rather looks at the health of the container itself (using [Docker's HEALTHCHECK capability](https://docs.docker.com/engine/reference/builder/#healthcheck))\*. [See relevant documentation here](https://dotnet.testcontainers.org/api/wait_strategies/#wait-until-the-container-is-healthy).

> \* Edit: Docker's HEALTHCHECK can be used to assert the health of services within the container; but is obviously only effective when defined. I do not believe the image used defines a HEALTHCHECK.

I would just remove your usage of the `.WithWaitStrategy()` extension method and let the default strategy as part of the `ElasticsearchBuilder` be used instead; which you can find [here](https://github.com/testcontainers/testcontainers-dotnet/blob/762feda35d4dd9778d86a0c2b50202e8abbb163e/src/Testcontainers.Elasticsearch/ElasticsearchBuilder.cs#L77).

**Comment by LGmatrix13** [comment]
@jacobjmarks Same issue occurs, which is why I tired to implement my own wait strategy. Test finish and fail before elastic even finishes starting...

If it helps, the tests that are failing are those that write to elastic and then read that recently added record from elastic... 
I run a refresh on the indices to be sure elastic can read what has been written, but it doesn't help :/ 
If I print out the health status of elastic in between tests it says there are 0 indices and 0 shards, which means elastic is isn't working...

**Comment by jacobjmarks** [comment]
I've done some more digging. I've used the following program to assert the HTTPS endpoint is available after the container starts.

``` csharp
using System.Text;
using Testcontainers.Elasticsearch;

var container = new ElasticsearchBuilder()
    .WithImage("docker.elastic.co/elasticsearch/elasticsearch:8.8.1")
    // .WithEnvironment("xpack.security.enabled", "false")
    .Build();

await container.StartAsync();

var esHttpsEndpoint = container.GetConnectionString();

Console.WriteLine($"Pinging {esHttpsEndpoint} ...");

using var httpClient = new HttpClient(new HttpClientHandler
{
    // bypass SSL issues
    ServerCertificateCustomValidationCallback = (_, _, _, _) => true,
});

// configure basic authentication
var credentials = $"{ElasticsearchBuilder.DefaultUsername}:{ElasticsearchBuilder.DefaultPassword}";
httpClient.DefaultRequestHeaders.Authorization = new("Basic", Convert.ToBase64String(Encoding.UTF8.GetBytes(credentials)));

using var response = await httpClient.GetAsync(esHttpsEndpoint);
response.EnsureSuccessStatusCode();

var responseContent = await response.Content.ReadAsStringAsync();
Console.WriteLine(responseContent);
```

<details><summary>See output</summary>
<p>

```
[testcontainers.org 00:00:00.10] Connected to Docker:
  Host: npipe://./pipe/docker_engine
  Server Version: 20.10.17
  Kernel Version: 5.10.102.1-microsoft-standard-WSL2
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 15.55 GB
[testcontainers.org 00:00:00.27] Docker container e230292c3882 created
[testcontainers.org 00:00:00.41] Start Docker container e230292c3882
[testcontainers.org 00:00:01.82] Wait for Docker container e230292c3882 to complete readiness checks
[testcontainers.org 00:00:01.83] Docker container e230292c3882 ready
[testcontainers.org 00:00:01.88] Docker container f82c3f5e66d4 created
[testcontainers.org 00:00:01.89] Copy tar archive to "/" to Docker container f82c3f5e66d4
[testcontainers.org 00:00:02.01] Start Docker container f82c3f5e66d4
[testcontainers.org 00:00:03.41] Wait for Docker container f82c3f5e66d4 to complete readiness checks
[testcontainers.org 00:00:26.81] Docker container f82c3f5e66d4 ready
Pinging https://elastic:elastic@127.0.0.1:56560/ ...
{
  "name" : "f82c3f5e66d4",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "lBa0W-glQgGayAYZ4SiM7Q",
  "version" : {
    "number" : "8.8.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "f8edfccba429b6477927a7c1ce1bc6729521305e",
    "build_date" : "2023-06-05T21:32:25.188464208Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

</p>
</details> 



What I have observed (with both the default 8.6.1 and 8.8.1 images) is that setting the environment variable `xpack.security.enabled` to `false` caused the following error when making the HTTPS request (observed via Postman):

    Error: write EPROTO 67057928:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../../../src/third_party/boringssl/src/ssl/tls_record.cc:242

cc @HofmeisterAn

@LGmatrix13 I would try &mdash; at the least &mdash; removing your `.WithEnvironment("xpack.security.enabled", "false")` call.

**Comment by jacobjmarks** [comment]
I would also, in general, ensure your tests are suitably waiting for `await elasticsearchContainer.StartAsync()` to complete before starting.

**Comment by LGmatrix13** [comment]
@jacobjmarks I'm using nunit and starting the container with an `OneTimeSetup` and stopping it with `OneTimeTeardown`. Theoretically, nunit should start `OneTimeSetup` at the beginning, wait, then continue. But maybe it is not? I'm also running my tests in parallel, but I get the same results if I turn that off.

**Comment by jacobjmarks** [comment]
If it's within NUnit's `OneTimeSetup` that should be fine. How are your tests attempting to communicate with the ES instance and what is the specific error message you are getting when they attempt to do so? A more complete example will be useful.

**Comment by LGmatrix13** [comment]
The tests try to test the full lifestyle, so I make an http request to various endpoints that makes nest queries to elastic. There's no exceptions, but whenever I have tests that write to elastic via my api endpoints, the data doesn't get saved. I've added print statements between when I write/read and elastic is telling me there's 0 shards to work with... 

Maybe I could provide something more detailed in the morning. Thanks for the help!

**Comment by HofmeisterAn** [comment]
I agree with @jacobjmarks comments. Usually, overriding the default module configuration is not necessary. I do not think the Elasticsearch image utilizes Docker's health check API. Please stick to the default module configuration (pinning the image version is fine).

    _ = new ElasticsearchBuilder().Build();
    
Testcontainers for .NET does not extract the SSL certificate from the container like [Java](https://github.com/testcontainers/testcontainers-java/blob/8465795ab9067447ca8b7d3e307cadcec8de377a/modules/elasticsearch/src/main/java/org/testcontainers/elasticsearch/ElasticsearchContainer.java#L129-L132). Therefore, your client must [accept](https://github.com/testcontainers/testcontainers-dotnet/blob/762feda35d4dd9778d86a0c2b50202e8abbb163e/tests/Testcontainers.Elasticsearch.Tests/ElasticsearchContainerTest.cs#L23) untrusted certificates.

> Maybe I could provide something more detailed in the morning. Thanks for the help!

I think more information or a reproducer is necessary. I do not see an issue with the configuration of the module yet.

**Comment by LGmatrix13** [comment]
@HofmeisterAn Here's an example:
It's just using `new ElasticsearchBuilder().Build()`

and `StartAsync`

```
public class Post {
public string name {get; set;}
public int age {get; set;}
}
```

```
[Test]
        public async Task WriteToElasticThenRead()
        {
            ElasticClient elasticClient = new ElasticClient(new ConnectionSettings());

            await elasticClient.UpdateAsync<Post>("1", u => u
                .Index("Posts")
                .Doc(new Post
                {
                    name = "Name",
                    age = 20
                }) 
                .DocAsUpsert()
            );

await elasticClient.Indices.RefreshAsync();

            var response = await elasticClient.GetAsync<Post>("1", u => u
                .Index("Posts")
            );

            var post = response?.Source;

            Assert.AreEqual(post.name, "Name");
            Assert.AreEqual(post.age, 20);
        }
```

I'm geting a `System.NullReferenceException : Object reference not set to an instance of an object.` since post is null because elastic couldn't actually save the data in the query before the get. If I run this same test with an elastic instance that has been running, it works... Honestly not sure what could be wrong here 😅

**Comment by HofmeisterAn** [comment]
> Honestly not sure what could be wrong here 😅

It is `null` because your code does not add the object to Elastic. If you look into the update response value, you will notice (note: you need to set the server certificate callback too):

    invalid_index_name_exception Reason: "Invalid index name [Posts], must be lowercase"
    
My test runs fine with a lowercase index. This issue does not relate to tc-dotnet.

**Edit** This is my example:

```csharp
public sealed class GitHub : IAsyncLifetime
{
  private readonly ElasticsearchContainer _elasticsearchContainer = new ElasticsearchBuilder().Build();

  public Task InitializeAsync()
  {
    return _elasticsearchContainer.StartAsync();
  }

  public Task DisposeAsync()
  {
    return _elasticsearchContainer.DisposeAsync().AsTask();
  }

  [Fact]
  public async Task Issue955()
  {
    // Given
    var clientSettings = new ElasticsearchClientSettings(new Uri(_elasticsearchContainer.GetConnectionString()));
    clientSettings.ServerCertificateValidationCallback(CertificateValidations.AllowAll);

    var client = new ElasticsearchClient(clientSettings);

    var index = Guid.NewGuid().ToString("D");

    var post = new Post();

    // When
    _ = await client.UpdateAsync<Post, Post>(index, post.Id, u => u.Doc(post).DocAsUpsert())
      .ConfigureAwait(false);

    var response = await client.GetAsync<Post>(index, post.Id)
      .ConfigureAwait(false);

    // Then
    Assert.Equal(1, response.Source.Id);
  }

  private sealed class Post
  {
    private static int _counter;

    public int Id { get; set; } = Interlocked.Increment(ref _counter);
  }
}
```

**Comment by LGmatrix13** [comment]
Okay, makes sense! But I don't have access to `ElasticsearchClientSettings`. So I'm doing it this way: 
```
            ElasticClient elasticClient = new ElasticClient(new ConnectionSettings().ServerCertificateValidationCallback(CertificateValidations.AllowAll));
            await elasticClient.UpdateAsync<Post>(Guid.NewGuid().ToString("D"), u => u
                .Index("posts")
                .Doc(new Post
                {
                    name = "Name",
                    age = 20
                })
                .DocAsUpsert()
            );

            await elasticClient.Indices.RefreshAsync();

            var response = await elasticClient.GetAsync<Post>(Guid.NewGuid().ToString("D"), u => u
                .Index("posts")
            );

            var post = response?.Source;

            Assert.AreEqual(post.name, "Name");
            Assert.AreEqual(post.age, 20);
```
I'm only using the regular NEST package. Looked at the logs on docker and it's closing the connection do to an untrusted certificate... so that appears to be the issue. I'm binding the container to port 9200 without random hosts, so I don't think I need to pass a connection string. The logs show the request is going through, anyways... Does anything look wrong on my connection settings? Thanks for you help btw, I really appreciate it!

**Comment by LGmatrix13** [comment]
Okay, changed my `ElasticBuilder` to the following, and now everything works:
```
            var elasticContainer = new ElasticsearchBuilder()
                .WithEnvironment("xpack.security.transport.ssl.enabled", "false")
                .WithEnvironment("xpack.security.enabled", "false")
                .WithImage("docker.elastic.co/elasticsearch/elasticsearch:8.8.1")
                .WithPortBinding(9200)
                .Build();
```

Disabling ssl was the key, I think. I'm going to sick with this for now so I don't have to inject a new elastic singleton into the API I'm testing. Thanks again for your guidance @jacobjmarks and @HofmeisterAn!

**Comment by HofmeisterAn** [comment]
> I'm only using the regular NEST package

I am not familiar with the package, but your client must accept untrusted certificates. Otherwise, you can extract the certificate from the container (like Java does) to configure your client, but that is more complex. According to https://github.com/elastic/elasticsearch-net NEST is "outdated" too.

> I'm binding the container to port 9200 without random hosts [...]

This is considered as a [bad practice](https://dotnet.testcontainers.org/api/best_practices/), we do not recommend it.

> I don't think I need to pass a connection string

I think you need to use the connection string, since it contains credentials (username and password).
