### ISSUE TITLE
[Bug]: Invalid Slack workspace link?

### ISSUE THREAD

**Issue by jacobjmarks** [testcontainers/testcontainers-dotnet#956]
### Testcontainers version

n/a

### Using the latest Testcontainers version?

Yes

### Host OS

n/a

### Host arch

n/a

### .NET version

n/a

### Docker version

```shell
n/a
```

### Docker info

```shell
n/a
```

### What happened?

Seems like the Slack workspace link is no longer valid.

<img width="316" alt="image" src="https://github.com/testcontainers/testcontainers-dotnet/assets/19641427/9228f659-f827-4ade-b1f5-5afce4d1b36b">

### Additional information

Side note: May be worth adding a general "Other" Issue type to better cater for these more general issues which do not require the required technical form fields as part of the Bug and Enhancement Issues.

**Comment by HofmeisterAn** [comment]
I guess the DNS redirect for https://slack.testcontainers.org/ is outdated (the invitation link is not valid anymore). @kiview @mtremsal this is not intended, right? Can someone take a look at it? I think devs cannot join the TC OSS Slack workspace anymore. @jacobjmarks in the meantime you can use this [invitation](https://join.slack.com/t/testcontainers/shared_invite/zt-202vpgalg-Cqi_6qu0rlFXf624js6tYQ).

**Comment by HofmeisterAn** [comment]
I will close this issue. It looks like the link is working again.

**Comment by mtremsal** [comment]
For future reference, it looks like Slack invite links [expire every 400 new sign-ups](https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invitation-link-pre-ia). We're looking into a way to automate the process.
